### ISSUE TITLE
[Android] IntentAndroid cannot read property 'canopenurl' of undefined

### ISSUE THREAD

**Issue by leoabacade** [facebook/react-native#11278]
my code:

`var url = 'geo:'+this.state.locationLat+','+this.state.locationLng;

        
        IntentAndroid.canOpenURL(url, (supported) => {
            if (!supported) {
                console.log('Can\'t handle url: ' + url);
            } else {
                IntentAndroid.openURL(url);
            }
        });`

error:
![15354275_120300000977496341_573433347_o png](https://cloud.githubusercontent.com/assets/2664504/20856360/c0713d98-b947-11e6-864c-e5d47e5b11d7.jpeg)

**Comment by rmevans9** [comment]
What version of RN are you running?

**Comment by rmevans9** [comment]
I am assuming this is RN >= 0.37.0. If so please check the breaking changes under 0.37.0

https://github.com/facebook/react-native/releases/tag/v0.37.0

**Comment by damusnet** [comment]
@facebook-github-bot answered

**Comment by leoabacade** [comment]
after upgrade to 0.38, IntentAndroid ( for opening google map )is not working any more
but it was functionally @ RN version 0.28
right now I switch to Linking [https://facebook.github.io/react-native/docs/linking.html](url) to open the map

not sure I should ask this question @ stackoverflow, since it looks like a bug

**Comment by leoabacade** [comment]
@rmevans9, thank you

**Comment by dimoreira** [comment]
I'm using react-native version 0.42.3 with Android and receiving the similar error:

`undefined is not a function (evaluating 's.Linking.openUrl(e)')`

I saw in the source for the 0.42.3 version that the `Linking.openURL` method is already implemented. Why can I use with Android?
