### ISSUE TITLE
Mac OSX Error: Watchman error: fileData.mtime_ms.toNumber 

### ISSUE THREAD

**Issue by andpor** [facebook/react-native#23750]
Running builds in Android Studio on MacOS X 10.13.6 or command line I get the following error:

jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: fileData.mtime_ms.toNumber is not a function. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.

Tried increasing file descriptors - did not help

## Code Example
without a reproduction link are likely to stall.

This is not code related.

## Environment
[skip envinfo]
react-native info does not seem to work. info parameter is unknown for RN 0.42.3
0.42.3

**Comment by andpor** [comment]
Scanning 972 folders for symlinks in /Users/andrzej/Documents/Projects/ComposerMobile/node_modules (18ms)

  Unrecognized command 'info'
  Run react-native --help to see list of all available commands

**Comment by hramos** [comment]
0.42.3 is quite old, we're up to 0.59 (in release candidate phase) these days. I don't know if there's enough detail in your issue for us to be able to assist.
