### ISSUE TITLE
Unresolved reference 'ReactNativeApplicationEntryPoint', Unresolved reference 'loadReactNative'

### ISSUE THREAD

**Issue by sanketpipaliya208** [facebook/react-native#52922]
### Description

e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:7:27 Unresolved reference 'ReactNativeApplicationEntryPoint'.
e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:36:5 Unresolved reference 'loadReactNative'. FAILURE: Build failed with an exception. * What went wrong:

### Steps to reproduce

Update react-native@0.79.2 to react-native@0.80.2 and try to run in android 

### React Native Version

0.80.2

### Affected Platforms

Runtime - Android

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: macOS 15.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 106.63 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.0
    path: ~/.nvm/versions/node/v20.18.0/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 11.1.0
    path: ~/.nvm/versions/node/v20.18.0/bin/npm
  Watchman:
    version: 2025.03.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK:
    API Levels:
      - "33"
      - "34"
      - "35"
      - "36"
    Build Tools:
      - 34.0.0
      - 35.0.0
      - 35.0.1
      - 36.0.0
    System Images:
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2025.1 AI-251.25410.109.2511.13752376
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.14
    path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 19.1.1
    wanted: 19.1.1
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.80.2
    wanted: 0.80.2
  react-native-macos:
    installed: 0.78.4
    wanted: ^0.78.0-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
npx react-native run-android
info A dev server is already running for this project on port 8081.
info Launching emulator...
error Failed to launch emulator. Reason: It took too long to start and connect with Android emulator: Medium_Phone_API_35. You can try starting the emulator manually from the terminal with: /Users/codeedocuserm2pro/Library/Android/sdk/emulator/emulator @Medium_Phone_API_35.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

> Configure project :react-native-mmkv
[react-native-mmkv] Thank you for using react-native-mmkv ❤️
[react-native-mmkv] If you enjoy using react-native-mmkv, please consider sponsoring this project: https://github.com/sponsors/mrousavy

> Configure project :shopify_react-native-skia
react-native-skia: node_modules/ found at: /Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/node_modules
react-native-skia: RN Version: 80 / 0.80.2
react-native-skia: isSourceBuild: false
react-native-skia: PrebuiltDir: /Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/node_modules/@shopify/react-native-skia/android/build/react-native-0*/jni
react-native-skia: buildType: debug
react-native-skia: buildDir: /Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/node_modules/@shopify/react-native-skia/android/build
react-native-skia: node_modules: /Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/node_modules
react-native-skia: Enable Prefab: true
react-native-skia: aar state post 70, do nothing

> Task :app:compileDebugKotlin FAILED

[Incubating] Problems report is available at: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.14.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
460 actionable tasks: 6 executed, 454 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:7:27 Unresolved reference 'ReactNativeApplicationEntryPoint'.
e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:36:5 Unresolved reference 'loadReactNative'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:7:27 Unresolved reference 'ReactNativeApplicationEntryPoint'.
e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:36:5 Unresolved reference 'loadReactNative'. FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 6s.
info Run CLI with --verbose flag for more details.
```

### MANDATORY Reproducer

https://github.com/sanketpipaliya208

**Comment by migueldaipre** [comment]
Hey @sanketpipaliya208,  please add a valid reproducer using our [Reproducer Template](https://github.com/react-native-community/reproducer-react-native/generate).

I just created a new project and it works fine.

**Comment by Taiguz** [comment]
@sanketpipaliya208, I had the  same error when trying to upgrade to the latest react native version.
Deleting node_modules, yarn.lock and './gradlew clean' fixed for me.

**Comment by ts-sravan** [comment]
> ### Description
> e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:7:27 Unresolved reference 'ReactNativeApplicationEntryPoint'. e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:36:5 Unresolved reference 'loadReactNative'. FAILURE: Build failed with an exception. * What went wrong:
> 
> ### Steps to reproduce
> Update react-native@0.79.2 to react-native@0.80.2 and try to run in android
> 
> ### React Native Version
> 0.80.2
> 
> ### Affected Platforms
> Runtime - Android
> 
> ### Output of `npx @react-native-community/cli info`
> ```
> System:
>   OS: macOS 15.0
>   CPU: (10) arm64 Apple M2 Pro
>   Memory: 106.63 MB / 16.00 GB
>   Shell:
>     version: "5.9"
>     path: /bin/zsh
> Binaries:
>   Node:
>     version: 20.18.0
>     path: ~/.nvm/versions/node/v20.18.0/bin/node
>   Yarn:
>     version: 1.22.22
>     path: /opt/homebrew/bin/yarn
>   npm:
>     version: 11.1.0
>     path: ~/.nvm/versions/node/v20.18.0/bin/npm
>   Watchman:
>     version: 2025.03.10.00
>     path: /opt/homebrew/bin/watchman
> Managers:
>   CocoaPods:
>     version: 1.16.2
>     path: /opt/homebrew/bin/pod
> SDKs:
>   iOS SDK:
>     Platforms:
>       - DriverKit 24.0
>       - iOS 18.0
>       - macOS 15.0
>       - tvOS 18.0
>       - visionOS 2.0
>       - watchOS 11.0
>   Android SDK:
>     API Levels:
>       - "33"
>       - "34"
>       - "35"
>       - "36"
>     Build Tools:
>       - 34.0.0
>       - 35.0.0
>       - 35.0.1
>       - 36.0.0
>     System Images:
>       - android-35 | Google Play ARM 64 v8a
>     Android NDK: Not Found
> IDEs:
>   Android Studio: 2025.1 AI-251.25410.109.2511.13752376
>   Xcode:
>     version: 16.0/16A242d
>     path: /usr/bin/xcodebuild
> Languages:
>   Java:
>     version: 17.0.14
>     path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/javac
>   Ruby:
>     version: 2.6.10
>     path: /usr/bin/ruby
> npmPackages:
>   "@react-native-community/cli":
>     installed: 19.1.1
>     wanted: 19.1.1
>   react:
>     installed: 19.1.0
>     wanted: 19.1.0
>   react-native:
>     installed: 0.80.2
>     wanted: 0.80.2
>   react-native-macos:
>     installed: 0.78.4
>     wanted: ^0.78.0-0
> npmGlobalPackages:
>   "*react-native*": Not Found
> Android:
>   hermesEnabled: true
>   newArchEnabled: true
> iOS:
>   hermesEnabled: true
>   newArchEnabled: true
> ```
> 
> ### Stacktrace or Logs
> ```
> npx react-native run-android
> info A dev server is already running for this project on port 8081.
> info Launching emulator...
> error Failed to launch emulator. Reason: It took too long to start and connect with Android emulator: Medium_Phone_API_35. You can try starting the emulator manually from the terminal with: /Users/codeedocuserm2pro/Library/Android/sdk/emulator/emulator @Medium_Phone_API_35.
> warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
> info Installing the app...
> 
> > Configure project :react-native-mmkv
> [react-native-mmkv] Thank you for using react-native-mmkv ❤️
> [react-native-mmkv] If you enjoy using react-native-mmkv, please consider sponsoring this project: https://github.com/sponsors/mrousavy
> 
> > Configure project :shopify_react-native-skia
> react-native-skia: node_modules/ found at: /Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/node_modules
> react-native-skia: RN Version: 80 / 0.80.2
> react-native-skia: isSourceBuild: false
> react-native-skia: PrebuiltDir: /Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/node_modules/@shopify/react-native-skia/android/build/react-native-0*/jni
> react-native-skia: buildType: debug
> react-native-skia: buildDir: /Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/node_modules/@shopify/react-native-skia/android/build
> react-native-skia: node_modules: /Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/node_modules
> react-native-skia: Enable Prefab: true
> react-native-skia: aar state post 70, do nothing
> 
> > Task :app:compileDebugKotlin FAILED
> 
> [Incubating] Problems report is available at: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/build/reports/problems/problems-report.html
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> For more on this, please refer to https://docs.gradle.org/8.14.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
> 460 actionable tasks: 6 executed, 454 up-to-date
> 
> info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 
> 
> e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:7:27 Unresolved reference 'ReactNativeApplicationEntryPoint'.
> e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:36:5 Unresolved reference 'loadReactNative'.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugKotlin'.
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
>    > Compilation error. See log for more details
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 6s
> error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:7:27 Unresolved reference 'ReactNativeApplicationEntryPoint'.
> e: file:///Users/codeedocuserm2pro/Documents/github/canvas_editor_project/canvas_editor_5/android/app/src/main/java/com/canvas_editor/MainApplication.kt:36:5 Unresolved reference 'loadReactNative'. FAILURE: Build failed with an exception. * What went wrong:
> Execution failed for task ':app:compileDebugKotlin'.
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org. BUILD FAILED in 6s.
> info Run CLI with --verbose flag for more details.
> ```
> 
> ### MANDATORY Reproducer
> https://github.com/sanketpipaliya208
> 
> ### Screenshots and Videos
> _No response_

+1

**Comment by sanketpipaliya208** [comment]
> [@sanketpipaliya208](https://github.com/sanketpipaliya208), I had the same error when trying to upgrade to the latest react native version. Deleting node_modules, yarn.lock and './gradlew clean' fixed for me.

Just follow this steps to reproduce

1. create project with react-native@0.79.2
2. update project manually to react-native@0.80.2
3. run npx react-native clean, mark all list then yarn install
4. try to run in android

**Comment by el-lsan** [comment]
Facing the same issue after updating from 0.79.2 to 0.81.2

**Comment by draggie** [comment]
In version 0.80.1 i cannot find this file `com/facebook/react/tasks/GenerateEntryPointTask.kt` inside the react-native-gradle-plugin, adding this file manually as a patch solved the problem for me (just copy-paste the content from repository).
Additionally it had to be added here in ReactPlugin.kt
```kotlin
val generatePackageListTask =
        project.tasks.register(
            "generateAutolinkingPackageList", GeneratePackageListTask::class.java) { task ->
              task.autolinkInputFile.set(rootGeneratedAutolinkingFile)
              task.generatedOutputDirectory.set(generatedAutolinkingJavaDir)
 project.tasks
          .named("preBuild", Task::class.java)
          .dependsOn(generatePackageListTask, generateEntryPointTask)
```

**Comment by aurangs7** [comment]
Getting the same error:
`MainApplication.kt:49:5 Unresolved reference 'loadReactNative'. FAILURE: Build failed with an exception.`

**Comment by ShanavasPS** [comment]
You should add the below change in your `MainApplication.kt` file

`import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative
`

https://react-native-community.github.io/upgrade-helper/?from=0.79.5&to=0.81.4#RnDiffApp-android-app-src-main-java-com-rndiffapp-MainApplication.kt

**Comment by marcoj** [comment]
Same here, upgrade from 0.79.0 to 0.80.2

**Comment by marcoj** [comment]
Solved on my side.
In my case there were two conflicting react native versions defined in package.json.
Check if there's a "GenerateEntryPointTask.kt" file in node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks. If not, then your installed react native version is not the correct one.

**Comment by anonymze** [comment]
Hi,

I think i had the incorrect version of Gradle for sdk 53. Used 8.13, switched to 8.6 and now it works.
Rm -rf your node_modules and npx expo prebuild --clean your android repertory and it should work after that.

Check the distributionUrl on gradle-wrapper.properties

**Comment by Brma1048** [comment]
@marcoj but how did you get the correct version? Inside my package.json i have react-native 0.81.4

**Comment by marcoj** [comment]
> [@marcoj](https://github.com/marcoj) but how did you get the correct version? Inside my package.json i have react-native 0.81.4

I was upgrading to 0.80.2, so I sticked with that. The project had literally two react native versions declared in package.json (one in dependencies and another in peerDependencies). After that you can try running `npx react-native clean`
But also check if there's a "GenerateEntryPointTask.kt" file in node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks

**Comment by Gregoirevda** [comment]
Make sure @react-native/gradle-plugin is updated

**Comment by Brma1048** [comment]
@marcoj @Gregoirevda yes my problem was the @react-native/gradle-plugin

**Comment by aurangs7** [comment]
> Make sure @react-native/gradle-plugin is updated

You saved my peace of mind a lot, Thank you

**Comment by sanketpipaliya208** [comment]
So, what is final solution for this issue, let me know and we gonna close this issue....., ASAP

**Comment by jerryheir** [comment]
@Gregoirevda @Brma1048 update it to what version. I am currently on RN 0.80.2 and my @react-native/gradle-plugin version is  0.76.5

What version do I upgrade it to. I doubt 0.82.0 will work

**Comment by jerryheir** [comment]
@aurangs7 were you able to upgrade it. How were you able to do it?

**Comment by aurangs7** [comment]
@jerryheir 
I was on: 
`"react-native": "0.80.0"`

and I upgraded gradle-plugin to:
` "@react-native/gradle-plugin": "^0.80.0"`

For your case as you are on RN: 0.80.2
Please try with: "@react-native/gradle-plugin": "^0.80.2"

I'm not sure if that will work, but you can try it once.

**Comment by migueldaipre** [comment]
Closing due to lack of a consistent reproducer and community feedback.
