### PR TITLE
Backport: Bump fmt to 12.1.0 to fix Xcode 26.4 compilation  

### PR DESCRIPTION
**Pull request by HSRAKTU**
## Summary:                                                                                                                                                 
  Backport of #56099 to 0.83-stable.                                                                                                                          
                                                                                                                                                              
  fmt 11.0.2 fails to compile with Xcode 26.4 due to stricter `consteval`
  enforcement in Apple Clang. The fix landed in fmt 12.1.0                                                                                                    
  (https://github.com/fmtlib/fmt/pull/4065) and was merged to `main` via #56099.
                                                                                                                                                              
  This backport brings the same fix to the 0.83-stable branch so developers                                                                                   
  on React Native 0.83 / Expo SDK 55 can build with Xcode 26.4.                                                                                               
                                                                                                                                                              
  Resolves: https://github.com/facebook/react-native/issues/55601                                                                                             
                                                                 
  ## Changelog:                                                                                                                                               
  [GENERAL][FIXED] - Bump fmt to 12.1.0 to fix Xcode 26.4 compilation errors                                                                                  
                                                                            
  ## Test Plan:                                                                                                                                               
  - Same change as #56099 which was reviewed, tested, and merged to main
  - Verified iOS build succeeds with Xcode 26.4 after this bump on a production Expo SDK 54 app (uses same RN 0.81 fmt dependency)

### CODE REVIEW

**Comment by Izocel** [comment]
Please fix project won't build :(

**Comment by turban** [comment]
We're also experiencing this problem as described here: https://github.com/fmtlib/fmt/issues/4740#issuecomment-4224549503

**Comment by Izocel** [comment]
> We're also experiencing this problem as described here: [fmtlib/fmt#4740 (comment)](https://github.com/fmtlib/fmt/issues/4740#issuecomment-4224549503)

💥💥💥 IF THIS CAN HELP YA ;)

```
# Xcode 26 workaround: patch fmt to disable consteval
def patch_fmt_for_xcode26(installer)
  fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
  if File.exist?(fmt_base)
    content = File.read(fmt_base)
    unless content.include?('Xcode 26 workaround')
      patched = content.gsub(
        /^(#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL) 1/,
        "// Xcode 26 workaround: disable consteval\n\\1 0"
      )
      if patched != content
        File.chmod(0644, fmt_base)
        File.write(fmt_base, patched)
      end
    end
  end
end
```

image

image
