### ISSUE TITLE
Upgrade to RN 0.49 -  bundling failed: Error: require() must have a single string literal argument

### ISSUE THREAD

**Issue by forki** [facebook/react-native#16216]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

react-native.cmd info
Scanning folders for symlinks in D:\code\msu.Reading\node_modules (18ms)

Environment:
  OS:  Windows 10
  Node:  7.0.0
  Yarn:  1.0.2
  npm:  3.10.9
  Watchman:  Not Found

### Steps to Reproduce

1. having production app in RN 0.48
2. upgrade to RN 0.49 and react 16.0.0-beta.5

react-native run-android:

### Expected Behavior

Normal app start

### Actual Behavior

    error: bundling failed: Error: require() must have a single string literal argument
        at pushDependency (D:\code\msu.Reading\node_modules\react-native\node_modules\metro-bundler\src\JSTransformer\worker\extract-dependencies.js:39:13)
        at CallExpression (D:\code\msu.Reading\node_modules\react-native\node_modules\metro-bundler\src\JSTransformer\worker\extract-dependencies.js:50:9)
        at NodePath._call (D:\code\msu.Reading\node_modules\babel-traverse\lib\path\context.js:76:18)
        at NodePath.call (D:\code\msu.Reading\node_modules\babel-traverse\lib\path\context.js:48:17)
        at NodePath.visit (D:\code\msu.Reading\node_modules\babel-traverse\lib\path\context.js:105:12)
        at TraversalContext.visitQueue (D:\code\msu.Reading\node_modules\babel-traverse\lib\context.js:150:16)
        at TraversalContext.visitMultiple (D:\code\msu.Reading\node_modules\babel-traverse\lib\context.js:103:17)
        at TraversalContext.visit (D:\code\msu.Reading\node_modules\babel-traverse\lib\context.js:190:19)
        at Function.traverse.node (D:\code\msu.Reading\node_modules\babel-traverse\lib\index.js:114:17)

![image](https://user-images.githubusercontent.com/57396/31227630-d06c5f96-a9da-11e7-8d4b-3c7b3a5cab5a.png)

### Related 

https://github.com/realm/realm-js/issues/1342
https://github.com/realm/realm-js/pull/1346

**Comment by hackdie** [comment]
its fixed in the new version of realm ("realm": "1.13.0"). this is not reactnative issue

**Comment by forki** [comment]
I don't use realm

**Comment by hackdie** [comment]
which lib has the problem? i had the same issue in Realm and Moment. and both i needed to find a work around for them. you might need to find the require line and fix it. :/

**Comment by forki** [comment]
the screenshot is all I'm seeing

**Comment by jeremistadler** [comment]
@forki Are you using moment js? 
The bug is in the bundler: https://github.com/facebook/metro-bundler/issues/65

**Comment by forki** [comment]
react-native-modal-datetime-picker@^4.11.0:
      version "4.11.0"
      resolved "https://registry.yarnpkg.com/react-native-modal-datetime-picker/-/react-native-modal-datetime-picker-4.11.0.tgz#bd2eb3a21cda584c6a018b11f6aed4bf4d020aca"
      dependencies:
        moment "^2.18.1"
        prop-types "15.5.10"
        react-native-modal "3.1.0"

@jeremistadler so what should I do?

**Comment by 24ark** [comment]
@forki Try `moment:"git+https://github.com/tqc/moment.git#no-dynamic-import"`

**Comment by binchik** [comment]
I'm having the same issue with moment. I use react-native-datepicker, which uses moment as its subdependency. Is there a way I can point the react-native-datepicker's moment to the "git+https://github.com/tqc/moment.git#no-dynamic-import"?

**Comment by albinekb** [comment]
@binchik I think you need to fork `react-native-datepicker` to fix it..

**Comment by binchik** [comment]
@albinekb Yeah just did that, thanks.

**Comment by fungilation** [comment]
Same error reproduced. For me, I have the package `moment-timezone`. Was fine on RN 0.48.1.

**Comment by anwarhamr** [comment]
+1 this has broken so many dependencies.  I'm hosed until we have a fix.

**Comment by Nickersoft** [comment]
@anwarhamr Same.

**Comment by TGPSKI** [comment]
+1

**Comment by fungilation** [comment]
Metro Bundler breaks again.

**Comment by anwarhamr** [comment]
I reverted to 48.4 and working again.  I hope this is fixed soon.  💃

**Comment by forki** [comment]
ok is someone from RN team able to explain the strategy to fix it completely?

**Comment by willymulyana** [comment]
It's so recent, and I think should be fixed asap. By upgrading to `0.49.1`, on first build I got this error on load image with `require(imageLocation)`, and second build got complain from `moment`.

**Comment by forki** [comment]
it's happening when you require an image?! wtf 

/cc @alfonsogarciacaro looks like you had the right idea. unfortunately

**Comment by kyle-ssg** [comment]
Yep unfortunately moment.js has a require that isn't a string literal, will also be reverting until this gets sorted

**Comment by fungilation** [comment]
With @willymulyana 's example. Is dynamic imports correct Javascript? If so, there's no excuse for "it not being supported" especially when it breaks popular libs like Moment.

**Comment by forki** [comment]
@hramos any official statement from the RN team?

**Comment by alien3d** [comment]
scratch my head.. about it.. new changes break. Even like this still output error  . 
`  switch (name) {
                    case "en-au.js":
                        require_method('./locale/en-au.js');
                        break;
                    case "en-ca.js":
                        require_method('./locale/en-ca.js');
                        break;
                    case "en-ie.js":
                        require_method('./locale/en-ie.js');
                        break;
                    case "en-nz.js":
                        require_method('./locale/en-nz.js');
                        break;
                    case "my.js":
                        require_method('./locale/my.js');
                        break;
                    case "zh-cn.js":
                        require_method('./locale/zh-cn.js');
                        break;
                } `

**Comment by albinekb** [comment]
There's a lot more discussion about this here https://github.com/facebook/metro-bundler/issues/65

**Comment by johanschram** [comment]
@binchik 
I have the same issue and stupid question if there are, (i'm a beginner) but to install your fork, I have to do : 
npm install --save binchik/react-native-datepicker ? 
Probably not, has it doesn't work...

**Comment by gurudev51** [comment]
I am facing the same issue while using react-native-gifted-chat.
Hope it will be fixed soon.

**Comment by binchik** [comment]
@johanschram Yes, that should work. I use `yarn add binchik/react-native-datepicker` in my own project. Maybe there is another dependency using moment in your project?

**Comment by Crash--** [comment]
The issue is discussed here : https://github.com/facebook/metro-bundler/issues/65

You can apply the fix to the Metro Bundler : https://github.com/facebook/metro-bundler/pull/69

**Comment by forki** [comment]
@Crash-- shouldn't this be done in more general fashion? Like release a RN update or retract the current version?

**Comment by Crash--** [comment]
Of course yes! I just pointed out a global workaround for this issue until we find how to fix it in RN release

**Comment by patw0929** [comment]
+1
(Upgrade to 0.49.2)

**Comment by ippa** [comment]
git bitten by this as well

**Comment by dwilt** [comment]
For those of you who need to get unstuck right now and are only running into this issue with moment:

```
yarn remove moment; yarn add https://github.com/tqc/moment.git#no-dynamic-import
```

One [this PR](https://github.com/moment/moment/pull/4187) gets merged, you should be able to revert back to just the original moment

**Comment by forki** [comment]
@dwilt is moment also the reason why people can't use images anymore?

**Comment by dwilt** [comment]
@forki No, I don't believe so. I'm on RN 0.49.3 and haven't run into this issue that others have mentioned -- just the moment one. I'm using images all over my application too. Are you dynamically importing them?

```js
require(`${someVar}/file.png`)?
```

**Comment by johanschram** [comment]
@binchik : seems to be a npm issue. It worked perfectly with yarn. 
Thanks !

**Comment by mschipperheyn** [comment]
Another way to work around this issue is using yarn 1.0+ and in package.json

```
"resolutions": {
    "moment": "git+https://github.com/tqc/moment.git#no-dynamic-import"
  },
  "dependencies": {
    "moment": "^2.18.1",
[...]
```

**Comment by gurudev51** [comment]
In my case, moment is installed as dependency for react-native-gifted-chat.
I tried uninstall moment manually and then reinstalled https://github.com/tqc/moment.git#no-dynamic-import, but still get the same

**Comment by albinekb** [comment]
did you add
```
"resolutions": {
  "moment": "git+https://github.com/tqc/moment.git#no-dynamic-import"
}
```
to your package.json first? @gurudev51

**Comment by gurudev51** [comment]
Still the same issue, I can't see what's fixed here.

**Comment by zuoge85** [comment]
@mschipperheyn Still no problem solved

"resolutions": {
    "moment": "git+https://github.com/tqc/moment.git#no-dynamic-import"
  },
  "dependencies": {
    "antd-mobile": "^1.6.11",
    "async-validator": "^1.8.1",
    "dva-core": "^1.1.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "rc-form": "^1.4.8",
    "react": "^16.0.0-beta.5",
    "react-native": "^0.49.3",
    "react-native-snap-carousel": "^3.3.3",
    "react-native-webp": "^0.3.1",
    "react-navigation": "https://github.com/react-community/react-navigation.git",
    "react-redux": "^5.0.6",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.10.1"
  },

**Comment by ravendell** [comment]
Just put comment the require('./locale/' + name); in the \node_modules\moment.js

**Comment by richardgirges** [comment]
Hey everyone, you should be able to resolve this issue now by pointing to the new version of metro-bundler using Yarn's selective dependency resolutions. Here's an example of what it should look like in your `package.json`:

```
  "dependencies": {
    "react": "16.0.0-beta.5",
    "react-native": "0.49.3"
  },
  "resolutions": {
    "react-native/metro-bundler": "0.20.0"
  },
```

Read more about Yarn's selective dependency resolutions [here](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) if you'd like to understand why this would work, vs adding the new version of metro-bundler directly into your `dependencies` block.

**Comment by forki** [comment]
is there no way for FB to push a hotfix in RN?

**Comment by rizzomichaelg** [comment]
Looks like moment released a fix [hack]: 
https://github.com/moment/moment/blob/9483e2a49fd8479fb84f1e00d6a854f106abc950/moment.js#L1846

**Comment by richardgirges** [comment]
@forki I think it comes down to how many commits made it into the latest version of metro-bundler and whether or not additional breaking changes could be introduced by hot fixing RN. Will leave to @grabbou to weigh in on a potential hot fix.

**Comment by tonybennett** [comment]
Fixed in moment 2.19.0, working for me with RN 0.49.3.

https://github.com/moment/moment/blob/develop/CHANGELOG.md

**Comment by richardgirges** [comment]
There appears to be an issue with metro-bundler 0.20.0 right now so a hot fix to RN is probably not a good idea until that gets figured out. If your issue is with moment specifically, the new version of moment that @tonybennett called out is probably the safest route for now.

**Comment by ravendell** [comment]
nice so no need to put a comment on the require('./locale/' + name); in the \node_modules\moment.js

**Comment by zuoge85** [comment]
1. add "resolutions": {
    "moment": "2.19.0"
  },

2. delete "react-native/metro-bundler": "0.20.0"

To solve the

thank @tonybennett

**Comment by jspiers** [comment]
@gurudev51 
I'm having the same problem "require() must have a single literal argument" error in node_modules/moment/min/moment-with-locales.min.js

It looks like only "moment.js" was fixed in moment 2.19.0.
"min/moment-with-locales.min.js" still has a require() that RN 0.49 doesn't like.

**Comment by jeffreymendez1993** [comment]
upgrading to 0.49 is a pain going to wait till later versions since a handful of dependancies broke.

**Comment by danieloprado** [comment]
any update?

**Comment by machour** [comment]
Changing 
`import moment from 'moment/min/moment-with-locales.min';`
to 
`import moment from 'moment/min/moment-with-locales';`

seems to work for me.

**Comment by zuoge85** [comment]
Suggest ignoring this version and not upgrading to 4.9. X

release There are bugs

**Comment by azat-co** [comment]
I have this bug in RN 0.50.3

**Comment by krishnalelas** [comment]
I have this bug in RN 0.50.4

trying metro-bundler 0.22.1 resolutions using yarn. but getting this exception 

> this._opts.getModulesRunBeforeMainModule is not a function

 [https://github.com/facebook/metro/issues/101](url)

```
"resolutions": {
    "react-native/metro-bundler": "0.22.1",
  },
```

**Comment by krishnalelas** [comment]
Working on RN 0.51.0. Finally!  👍

**Comment by joaom182** [comment]
I have same issue with `<Image />` component from `react-native`.

Example:

```javascript
import {Image} from 'react-native';
...
const imageUri = '../../../assets/images/bg.png';
...
<Image source={require(imageUri)} />
```

And Metro bundler throw this Error:
`TransformError: require() must have a single string literal argument. (null)`

**Comment by araujobarret** [comment]
I am on RN 0.51 even with moment 2.19.0 and the bug persists.

**Comment by jpmoyn** [comment]
I have exact same error as @joaom182. Dynamic import for an `Image`

**Comment by forki** [comment]
@grabbou you closed this - but it still persists in RN 0.53

**Comment by kyle-ssg** [comment]
@joaom182 @jpmoyn This is not a bug, dynamic image imports via require has never been supported.

See https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources

**Comment by forki** [comment]
@jpmoyn the problem is that require now only accepts string literals - not strings that have been computed. that used to work.

**Comment by kyle-ssg** [comment]
@forki Sorry but I'm going to have to correct you, I found out this 2-3 years ago attempting to use computed strings. This is due to the way react native packages assets and is not a require related issue. See this 3 year old doc https://github.com/facebook/react-native/blob/0.5-stable/docs/Image.md

**Comment by forki** [comment]
@kyle-ssg I have code, with UI Tests, that work /shrug

**Comment by kyle-ssg** [comment]
For requiring images ? Well I'd love to see how you managed that 😄

**Comment by jeffreymendez1993** [comment]
Upgrade to 0.53.0 a couple things changed but, everything is smooth!

**Comment by forki** [comment]
@kyle-ssg I have a theory about why it may have worked for us. What if the image files were already bundled? Then the "static marker" would not be needed, right? Then `require` may have just worked as no-op and would have transported the computed file name to the image component. With the change that now `require` only accepts literals, this behaviour broke. Does this sound plausible?

**Comment by mtrabelsi** [comment]
For guys having troubles with images - to do dynamic import you need to require different images **in advance**  and based on some conditions later you put what you want:
```
function Arrow(prop) {
  const imgUpDirection = <Image source={require('./triangleUp.png')} />;
  const imgDownDirection = <Image source={require('./triangleDown.png')} />;
  const imgRightDirection = <Image source={require('./triangleRight.png')} />;
  let appliedDirection = imgUpDirection; // by default it is up
  if (prop.val === 0) {
    appliedDirection = imgRightDirection;
  } else if (prop.val < 0) {
    appliedDirection = imgDownDirection;
  }
  return (
    <Text>
        {appliedDirection}
    </Text>
  );
}
```

then

**Comment by rochapablo** [comment]
Just `import moment from 'moment';` worked for me.
