### ISSUE TITLE
Not able to generate archive when using a Pod file

### ISSUE THREAD

**Issue by compojoom** [facebook/react-native#14749]
I managed to update to 0.46 rc2 from 0.43 today and everything was looking ok. Building a debug or production release was working. However when I tried to create an archive I ran in the following error:
```
Undefined symbols for architecture armv7:
  "_JSNoBytecodeFileFormatVersion", referenced from:
      +[RCTJavaScriptLoader loadBundleAtURL:onProgress:onComplete:] in libReact.a(RCTJavaScriptLoader.o)
      +[RCTJavaScriptLoader attemptSynchronousLoadOfBundleAtURL:runtimeBCVersion:sourceLength:error:] in libReact.a(RCTJavaScriptLoader.o)
  "facebook::react::parseTypeFromHeader(facebook::react::BundleHeader const&)", referenced from:
      +[RCTJavaScriptLoader attemptSynchronousLoadOfBundleAtURL:runtimeBCVersion:sourceLength:error:] in libReact.a(RCTJavaScriptLoader.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
In my project I'm using react-native-maps and since I'm running google maps on iOS I have a podfile similar to this one:
https://github.com/airbnb/react-native-maps/blob/master/example/ios/Podfile

It turns out that when I remove the following lines

```
  pod 'React', path: '../../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
```

the archive is being built correctly. 

I've reproduced the error here:
https://github.com/compojoom/rn46crash/tree/7c34cf696cf940e21566d73b7e76365fb6aab677

As you can see the podfile just has the pod Yoga and pod React lines. 

To run the app, clone the repository and do `yarn`. Afterwards open the rn46crash.xcworkspace with XCode, assign a team to the project and build it. You should run in the specified error above.

I'm pasting this issue here and not in the react-native-maps repository as with RN 0.43 - I was able to create an archive with that pod configuration, that's why I think that there is something wrong in the RN package.

* React Native version: 0.46 rc2
* Platform: ios
* Development Operating System: macOS
* Build tools: Xcode 8.3.3

**Comment by litmanenPL** [comment]
It seems that adding **BatchedBridge** subspec resolves the issue.
I found it out based on **[React.podspec](https://github.com/facebook/react-native/blob/master/React.podspec)** file analysis. _JSNoBytecodeFileFormatVersion_ is defined in _JSCWrapper.cpp_

**Comment by tuckg** [comment]
@litmanenPL how to solve?

**Comment by litmanenPL** [comment]
@tuckg as mentioned above by adding **BatchedBridge**  React subspec in **Podfile**

```
pod 'React', path: '../../node_modules/react-native', :subspecs => [
   ...,
   'BatchedBridge',
   ...
  ]
```

**Comment by tuckg** [comment]
@litmanenPL Nice, It work

**Comment by icarus-sullivan** [comment]
@litmanenPL I have been staring at this for the last 3-4 days. You my friend, are awesome.

**Comment by ryancarlson** [comment]
Ah this! Thank you @litmanenPL !

**Comment by guilhermepontes** [comment]
Thank you @litmanenPL!!!

**Comment by jpamarohorta** [comment]
@litmanenPL solution fixed that error but now I'm getting `duplicate symbols for architecture armv7`. I suppose that happens because now I have 2 copies of React in the project, one from cocoapods and one in the Libraries themselves.

What can be done to fix this? Removing React from the Libraries (like it's suggested in [https://github.com/auth0/react-native-lock/issues/3](url)) ends up giving a lot of runtime errors.

**Comment by litmanenPL** [comment]
@jpamarohorta `duplicate symbols for architecture armv7` is probably caused by some issue with your project configuration and it's not related to the original issue from this ticket at all. So probably it can be fixed only by properly configuring your project. Configuring React via `cocoapods` should be enough - there is no need to add it as other libraries, subproject, etc.

**Comment by ArtyomCommander** [comment]
@litmanenPL  help me y i have problem :( 

ArchiveIntermediates/elBacan/BuildProductsPath/Release-iphoneos/libRCTWebSocket.a(RCTWebSocketModule.o)
ld: 424 duplicate symbols for architecture arm64

**Comment by dotansimha** [comment]
@ArtyomCommander remove the `libReact.a` and `RTCWebSocket` from your XCode project because if you added it in the Podfile, you don't need to include it in your project. Please try andsee it the error count is lower now.

**Comment by tehong** [comment]
@dotansimha Thanks you.  I upgraded to 0.48.4, I also encountered duplicated symbols between libReact.a and libRCTWebSocket.a.  With your advice, I removed the libRCTWebSocket.a from my xcode target's "Link Library with libraries" after putting the 'RCTWebSocket' in the pod 'React' subspecs.  Now I can both run debug and archive.

**Comment by ararog** [comment]
@tehong I don't have the same luck as you, I have to keep adding libs when running debug and removing when I'm about to run fastlane to build, archive and upload.

**Comment by rborn** [comment]
I have the same issue, cannot build the archive no matter what I try to put in the Podfile.
RN 0.50.3

**Comment by rborn** [comment]
I managed to make it work by linking in the xcode project the next 2 libs
<img width="721" alt="screen shot 2017-12-05 at 14 24 08" src="https://user-images.githubusercontent.com/406409/33609548-d1c2c1fa-d9c8-11e7-82c9-011170b8bac1.png">

the pod file stays "simple"

~~~
platform :ios, '9.1'
target 'App' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'GoogleMaps'
  pod 'React', :path => '../node_modules/react-native'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end
~~~

Now I can send the app to Testflight using fastlane 🎉

**Comment by brownieboy** [comment]
@rborn 's solution did it for me.  I just added the libs `libcxxreact.a` and `libjschelpers.a` to XCode as he said.  I also removed the `libReact.a ` as @dotansimha said, because I was also loading React in my Pod file.

**Comment by Andreyco** [comment]
Guys, are you having luck building "release" archive after importing `libcxxxreact.a`, `libjschelpers.a` and removing `libReact.a`? App build, opens, but screen stays blank.

**Comment by brownieboy** [comment]
@Andreyco,

Yes, I _am_ having that very problem.

It only happens when I build and archive, submit that archive to Test Flight, and then download the app from there.  When I built from Xcode and installed directly on my iPhone, it works fine.

I haven't, until now, had any clue what the cause might be because I was quite late introducing Test Flight into my process.  (Lesson learned there!)

**Comment by brownieboy** [comment]
So I've now added BatchedBridge to the React subspec in my Pod file.  I can now build, upload and then download from TestFlight, and the resulting app no longer hangs on the blank screen.

Here's how I changed my Pod file:
```
  pod 'React', path: '../node_modules/react-native', :subspecs => [
   'BatchedBridge'
  ]
```
So pretty much as @litmanenPL first said.   That was the only change that I made.

**Comment by Andreyco** [comment]
@brownieboy what RN version are you running? I believe `BatchedBridge` was deprecated in favour of `CxxBridge` which was causing me another troubles. Gonna give it another try after proper sleep, lol

**Comment by brownieboy** [comment]
@Andreyco,

React-Native 52.1 now, although I think I was on 51 when the problems first appeared.

**Comment by Andreyco** [comment]
This is madness... 
Despite `BatchedBridge` is legacy and `CxxBridge` should be used instead going with `CxxBridge` is no option for me. It has several dependencies (`folly`, `boost`, ...) which take forever to download (there is pending PR which replaces `boost` with `boost-for-react-native` and drops build time) and break our cloud builds (30m timeouts).

For now, I opt in removal of `React` as target

```shell
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target '{project}' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for {project}

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge',
    'DevSupport'
  ]

  target '{project}Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target '{project}-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for {project}-tvOS

  target '{project}-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by esutton** [comment]
@litmanenPL solved archive and @dotansimha solved duplicate symbols.  Thank you both!

@litmanenPL said add this to Podfile
````
pod 'React', path: '../../node_modules/react-native', :subspecs => [
   ...,
   'BatchedBridge',
   ...
  ]
````

@dotansimha said:
> remove the **libReact.a** and **RTCWebSocket** from your XCode project because if you added it in the Podfile, you don't need to include it in your project. 

I am using:
````
		"react": "^16.2.0",
		"react-native": "^0.51.0",
````

**Comment by msand** [comment]
@grabbou  @ide Would it be possible to get an example project with a working debug and release build, and at the same time possibility to archive? I've tried to get a plain react-native init, pod init, pod install working using 0.54.0 but no luck. Only way to get it working is with linking React manually and this hack: https://github.com/facebook/react-native/issues/15838#issuecomment-333455341
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```
Which kind of goes against to whole point of cocoapods.
If I don't link it manually I get this instead: https://github.com/facebook/react-native/issues/14925
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTReconnectingWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTPackagerConnection.o)
  "_OBJC_CLASS_$_RCTSRWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTInspectorPackagerConnection.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Taking use_frameworks! into use causes these:
https://github.com/facebook/react-native/issues/17893
https://github.com/facebook/react-native/issues/16039
https://stackoverflow.com/questions/48705250/react-native-ios-could-not-build-module-yoga-algorithm-file-not-found

**Comment by msand** [comment]
Managed to get use_frameworks building with the patches from here: https://github.com/facebook/react-native/pull/17764#issuecomment-367943213 but archiving fails with 0.54 with this: https://github.com/facebook/react-native/issues/18205

**Comment by tlloydukdev** [comment]
I'm getting the same issue @msand - I can't get debug, release and archive to work without manually adding/removing Link Binary with Libraries each time :/

**Comment by msand** [comment]
@tlloydukdev Found another workaround for the non use_frameworks case: https://github.com/facebook/react-native/issues/15838#issuecomment-372681307 Essentially a duplicate target for debugging with manually linked React Native modules, and using the xcodebuild cli to build release for simulator and archive for TestFlight / AppStore.
