### ISSUE TITLE
Failure in 0.4.0, for existing project and fresh project from init

### ISSUE THREAD

**Issue by awiss** [facebook/react-native#944]
When I upgraded my project to 0.4.0 I got this error.
```TransformError: {app}/node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js: Cannot find module ‘./docblock’```

Even a new project created from `react-native init` has this failure.

**Comment by mjw56** [comment]
Make sure flow and watchman are up to date and latest. Also, if you upgraded to 0.4.0 in an existing app, make sure any dependencies are using at least react native 0.4.0 or have it listed as a peerDependency.

**Comment by jhopper28** [comment]
I'm getting this same error on a new project, too—no other react projects installed. Both flow and watchman are up-to-date.

**Comment by bparadie** [comment]
I just ran into the same problem, but the error went away after closing the packager terminal window, cleaning the xcode project, and rebuilding. I didn't have to update `flow` nor `watchman`.

**Comment by joeferraro** [comment]
can confirm @bparadie's fix works for me

**Comment by coderdave** [comment]
I also ran into a `TransformError` on a fresh install and closing the package terminal window and rebuilding the project worked just as @bparadie noted. Any reason why this happened? Messed me up for a while.
