### ISSUE TITLE
Compilation issues with Xcode 12.4 / 12.5 when I upgraded to 0.61.4 to 0.64.2

### ISSUE THREAD

**Issue by sapramit** [facebook/react-native#32040]
Hi Folks 
I just upgraded to the latest Xcode 12.5,  React native v0.64.2

## Description
The build runs fine on Xcode 12.4, along with the legacy build system
 
The code compilation is failing, when I upgraded one of the frameworks to XcFramework. Moved to new build system from  legacy build system (due to XcFramework)

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UMModuleRegistryAdapter", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_UMModuleRegistryProvider", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

warning: no rule to process file '/Users/amit/Desktop/MQ/Src/BotSDKPods/Widgets/Resources/Fonts/Lato/OFL.txt' of type 'text' for architecture 'x86_64' (in target 'BotSDK' from project 'Pods')
warning: no rule to process file '/Users/amit/Desktop/MQ/Src/BotSDKPods/Widgets/Resources/Fonts/Lato/README.txt' of type 'text' for architecture 'x86_64' (in target 'BotSDK' from project 'Pods')
warning: Building for iOS Simulator, but the linked and embedded framework 'BotSDKFrameWork.framework' was built for iOS + iOS Simulator. (in target 'MobileApp' from project 'MobileApp')

XCBBuildService[20690:1633513] Failed to remove: /Users/amit/Desktop/MQ/Src/ios/build/Build/Intermediates.noindex/XCBuildData/87d76ffac8758796051e48db9f80b7b2-desc.xcbuild: unlink(/Users/amitsapra/Desktop/MQ/Src/ios/build/Build/Intermediates.noindex/XCBuildData/87d76ffac8758796051e48db9f80b7b2-desc.xcbuild): No such file or directory (2)
** BUILD FAILED **

## React Native version:
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 301.83 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.24.1 - ~/.nvm/versions/node/v10.24.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v10.24.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. pod install
2. yarn ios

## Expected Results
The build should be successful.
