### ISSUE TITLE
undefined is not a function(evaluating '_this.registerEvents()')

### ISSUE THREAD

**Issue by ericcumbee** [facebook/react-native#20791]
- [X ] Review the documentation: https://facebook.github.io/react-native
  - [X ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
      Memory: 757.11 MB / 7.93 GB
    Binaries:
      Yarn: 1.9.4 - C:\Users\ecumb\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809
```

## Description
<img width="784" alt="reproerror" src="https://user-images.githubusercontent.com/734209/44476038-9b46f980-a604-11e8-9d65-207a1b12a15d.png">

## Reproducible Demo
Create RN project using react-native init using version 0.57.0-rc0
react-native run-android 
kill the spawned bundler and relaunch using npm start to work around issue #20712

**Comment by dmead** [comment]
I have this exact error.

Worth mentioning that it's because i'm on 57-rc0 to escape the acessiblity bug in 56

Also worth mentioning that I'm here because 56 is the default configuration in webstorm.

Whats a stable version of react-native I can use to learn things?

**Comment by danielgindi** [comment]
I got this too. Replaced babel preset, deleted node_modules/.cache, nothing.

**Comment by donjo9** [comment]
Is this still a problem with rc2 ? because i used to have this issue, but dont with rc2

```
React Native Environment Info:
    System:
      OS: Windows 7
      CPU: x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      Memory: 1.09 GB / 11.92 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  1.5.0.0 AI-141.2456560
```

**Comment by danielgindi** [comment]
I do have this problem with rc2.

**Comment by kelset** [comment]
@danielgindi can you upload a repro? Just tested locally with the 0.57-branch (details here https://github.com/facebook/react-native/issues/20712#issuecomment-415417949 ) and I can't repro this issue.

**Comment by ericcumbee** [comment]
rc2 produces the same results on windows

**Comment by danielgindi** [comment]
@kelset well, creating a new project using `react-native` cli, then changing to 0.57.0-rc.2 and the new babel preset, results in a node_modules/react-native/index.js not found.
So I can't even get to that point where the `_registerEvents` is undefined.

In my own project, I tried to apply the commit for `util/Config.js`, then delete `node_modules/.cache` but that did not change anything.

**Comment by badaz** [comment]
Same problem here on 0.57.0-rc.2 build for android : _registerEvents is undefined

**Comment by donjo9** [comment]
What does the Metro instance output ?

**Comment by ericcumbee** [comment]
@donjo9 no errors reported on the metro instance just 
```
 DELTA  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::ffff:127.0.0.1 - - [24/Aug/2018:18:16:37 +0000] "GET /index.delta?platform=android&dev=true&minify=false&deltaBundleId=a4271ccc904b5058 HTTP/1.1" 200 69 "-" "okhttp/3.10.0"
 DELTA  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.
```

**Comment by danielgindi** [comment]
Seems like rc-3 solves the issue

**Comment by tamirrab** [comment]
I still get the same message on rc-3 :(

![simulator screen shot - iphone 6 - 2018-08-25 at 23 43 37](https://user-images.githubusercontent.com/17690064/44622430-cfe6d980-a8c0-11e8-831b-96c83df5f5b4.png)

**Comment by danielgindi** [comment]
Try deleting `node_modules/.cache`, and then doing `react-native run-ios --resetCache`

**Comment by donjo9** [comment]
i believe it must be some kind of caching issue, because i had the issue, but can't recreate with any of the rc, not clean install or upgrade from 0.56

**Comment by danielgindi** [comment]
@tamirrab Maybe it's time to get drastic. 
1. Make sure the you put rc.3 in your package.json
2. Delete `package-lock.json`
3. Delete `node_modules`
4. `npm i`
5. `react-native start --reset-cache`

**Comment by tamirrab** [comment]
Did it all
+ deleted my app on the emulator

unfortunately the same error :(

**Comment by tamirrab** [comment]
steps that i done:
watchman watch-del-all   
rm -rf $TMPDIR/react-native-packager-cache-* 
 rm -rf $TMPDIR/metro-bundler-cache-*      
rm -rf node_modules/                 
npm cache clean                         
npm cache verify        
npm start -- --reset-cache    

Still the same error

**Comment by donjo9** [comment]
do you have a repo that produces that error that we could test on?

**Comment by donjo9** [comment]
@joejordan i will ask you the same question ;) do you have a repository that produces this error, that we could clone and test on :)

**Comment by 164738777** [comment]
Same here....

Upgrade from 0.5.6 because of this [issue](https://github.com/facebook/react-native/issues/19953).

Then here is a new unresolved issue in 0.5.7...Fk..

**Comment by donjo9** [comment]
@164738777 same question ;) do you have a repository that produces this error, that we could clone and test on :)

**Comment by joejordan** [comment]
@donjo9 here's one. https://github.com/joejordan/0.57rc3-WindowsCrash

Was able to duplicate the issue on two systems.

**Comment by joejordan** [comment]
@gengjiawen that must have been generated by create-react-native-app because I don't think I touched that file. Regardless, I tried it with that preset and the 'undefined' red screen of death still appears upon launch.

**Comment by gengjiawen** [comment]
Can you try to initial a new project using rc3 ?

**Comment by chakrihacker** [comment]
@gengjiawen this issue exists in my windows 10 too, can you point on what files to look for, maybe I can give a try. Thanks

**Comment by gengjiawen** [comment]
check my previous comment, I have not tested it, maybe need more file to change.

**Comment by donjo9** [comment]
I found the following so far:

@joejordan s repo failed on my machine as well, changing the .babelrc and changing the 

```
-"babel-preset-react-native": "5.0.2",
+"metro-react-native-babel-preset": "0.43.5",
```

in package.json did nothing.
deleting node_modules before doing "yarn" or "npm install" had no effect.

What did work, was initial a new project with rc3 with `react-native init albums --version 0.57.0-rc.3` installing that app on my phone with `react-native run-android`, kill the bundler from the new project, and then running the bundler from the "faulty" project with `yarn start` or `npm run start`

**Comment by kelset** [comment]
By looking at the comments, I suggest you folks wait until the changelog for 0.57 is out, we'll try to have a list of manual steps you have to do to correctly upgrade your projects to 0.57 since a few things are changing.

Again, we are still on RC stage so don't rush into it.

**Comment by donjo9** [comment]
Might as well be the same :D
After my latest post i did a
`react-native start --reset-cache`
And now i cant seem to recreate the issue, not even with a fresh clone of @joejordan s repo

**Comment by donjo9** [comment]
Sorry for keep spamming, but this got me from a clean git clone to a working app
`git clone https://github.com/joejordan/0.57rc3-WindowsCrash Test057rc3`
`cd Test057rc3`
`npm install`
`react-native upgrade` answering y to every question
Install 
```
platforms;android-27 Android SDK Platform 27
build-tools;27.0.3 Android SDK Build-Tools 27.0.3
```
with the Android SDK manager
`react-native run-android` this will still fail
kill bundler
`react-native start --reset-cache`

From this point on `react-native run-android` should work

**Comment by joe307bad** [comment]
I can also confirm some of @donjo9's process. Here is what got me from a clean git repo to a working app:

1.  Update Android SDK Build-Tools via Android SDK Manager
2. `react-native init MyApp2 --template typescript --version 0.57.0-rc.3`
3. `cd MyApp2`
4. `react-native upgrade`
5. Answer "y" to all questions
6. Point genymotion Android SDK to folder location for my Windows user (genymotion > Setting > ADB)
7. Restart computer
8. Open genymotion emulator (Samsung GS8 API 26)
9. `react-native run-android`

At this point the bundler booted up, the app installed on the emulator, and I was able to debug via chrome dev tools. I will update this later tonight when I can test on a different computer.

**Comment by brunolemos** [comment]
I'm having this issue on any project with 0.57 rc3, starting from scratch or upgrading.

**Comment by pontusab** [comment]
I can confirm that this works with the latest `0.57 rc4`:

`package.json`
```
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "metro-react-native-babel-preset": "^0.45.1",
```

`.babelrc’
```
"presets": ["module:metro-react-native-babel-preset"]
```

**Comment by haggholm** [comment]
@pontusab When you say that “this works”, do you mean that you can reproduce the issue or that it’s gone away? I am still seeing this error with `0.57.0-rc.4`.

**Comment by pontusab** [comment]
@haggholm had this issue `undefined is not a function(evaluating '_this.registerEvents()')` on `0.57.0-rc.2` but now with the configuration in `.babelrc` it works.

**Comment by yanivnizry** [comment]
after cache reset (react-native start --reset-cache) it worked for me also

**Comment by gengjiawen** [comment]
Looks resolved.

**Comment by donjo9** [comment]
@164738777 have you tried [this](https://github.com/facebook/react-native/issues/20791#issuecomment-416578394)

if so, do you have a repo that reproduces this error that we could try it with ?
