### ISSUE TITLE
iOS build failed in xCode 15.0.1 - duplicate symbols and linker command failed

### ISSUE THREAD

**Issue by ElliDy** [facebook/react-native#41329]
### Description

After updating xCode to 15.0.1 and react-native from 0.69.0 to 0.70.14, I face the following. When I run xCode build in debug mode for my app, the following issues appear:

39475 duplicate symbols
Linker command failed with exit code 1 (use -v to see invocation)

### React Native Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 288.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
    Yarn: 1.22.18 - ~/Projekte/node_modules/.bin/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
    Watchman: 2023.09.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

* set scheme to debug
* click play button in xCode and run my app on iPhone 15 Pro simulator

### Snack, screenshot, or link to a repository

<img width="1142" alt="Bildschirmfoto 2023-11-06 um 09 43 58" src="https://github.com/facebook/react-native/assets/3762504/8600f3b2-89cb-439e-a40d-1d75f59487de">

**Comment by ElliDy** [comment]
Looks like the issues are NOT solved by using react-native 0.70.14. The same issues appear, when I make the upgrade of react-native to this version. Would be very nice, if some one can help me out.

**Comment by ElliDy** [comment]
I changed what is proposed in post von tetar [here](https://stackoverflow.com/questions/77133361/no-template-named-unary-function-in-namespace-std-did-you-mean-unary-fun) on stack overflow, because I got the error as well before the two issues, I posted here.  I do not know, if there is a connection between that things.

**Comment by ElliDy** [comment]
Refered to [the post in the issue here](https://github.com/facebook/react-native/issues/39568#issuecomment-1762890606) I will close this issue, as with --verbose flag I got more hints about it and exactly this solution will hopefully match.

**Comment by Ahsanali012** [comment]
for 0.72.3 still facing this issue

**Comment by DeepikaSharma5** [comment]
I tried adding -ld64, but still the same issue. Unable to run or build the project. Before adding -ld64, it showed as 15 duplicate symbols. After adding -ld64, it shows as 15 duplicate symbols for architecture arm64 @ElliDy

**Comment by nicooo91** [comment]
> I tried adding -ld64, but still the same issue. Unable to run or build the project. Before adding -ld64, it showed as 15 duplicate symbols. After adding -ld64, it shows as 15 duplicate symbols for architecture arm64 [@ElliDy](https://github.com/ElliDy)

Hello, did you find a solution? I have the same problem with RN 0.76.6

**Comment by lufutu** [comment]
@nicooo91 hope this help https://github.com/callstack/react-native-pager-view/issues/958#issuecomment-2585640928, remove "@react-native-community/viewpager" work for me.
