### ISSUE TITLE
[Packager] Catch error on starting app version 0.5.0 cocoapods

### ISSUE THREAD

**Issue by bimawa** [facebook/react-native#1557]
```
URL: http://bimawa.local:8081/index.ios.bundle
 line: 1670
 message: Invariant Violation: Application EventLentView has not been registered."
2015-06-08 17:22:26.065 [error][tid:com.facebook.React.BridgeMethodQueue][RCTBridge.m:432] RCTDataManager.queryData was called with 4 arguments, but expects 3
```
![screen shot 2015-06-08 at 17 31 47](https://cloud.githubusercontent.com/assets/1393809/8034773/49f1e662-0e04-11e5-82ad-e848615c3f15.png)

**Comment by paramaggarwal** [comment]
Are you sure you did something similar to `AppRegistry.registerComponent('EventLentView', () => EventLentView);` in your `index.os.js`?

**Comment by bimawa** [comment]
Yes. May be something changed in RCT_EXPORT_MODULE. @paramaggarwal can u help me in slack private messages?

**Comment by JonasJonny** [comment]
Here you have some solutions http://stackoverflow.com/questions/29287987/invariant-violation-application-awesomeproject-has-not-been-registered-when-b.

I had similar issue after update and I have to init new project and copy my source code into.

**Comment by bimawa** [comment]
>I had similar issue after update and I have to init new project and copy my source code into.

Yea u right!
i roll out on v.0.4.2 and get new error:

```
 ERROR  Error while minifying JS
Transformed code line: "    );"
Module name (best guess): precomputeStyle
Unexpected token: punc ()) (line: 19167, col: 4, pos: 620877)
```
go experimenting more ...

**Comment by bimawa** [comment]
Tag 0.4.3 not describe in React.podspec research continues..

**Comment by bimawa** [comment]
on commit: =>'bb4de45d56aaa5816bece984fa554cbb2881cb04' working fine, except for one thing minifying: 

```
ERROR  Error while minifying JS
Transformed code line: "    );"
Module name (best guess): precomputeStyle
Unexpected token: punc ()) (line: 19167, col: 4, pos: 620877)
```

**Comment by bimawa** [comment]
update on tag 'v0.5.0' call this `(JS_DIR=`pwd`/ReactComponent; cd Pods/React; npm run start -- --root $JS_DIR)`
get fails:

```
../Pods/React/packager/packager.js:71
    options.root.forEach(function(root) {
                 ^
TypeError: Object true has no method 'forEach'
    at Object.<anonymous> (../Pods/React/packager/packager.js:71:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by bimawa** [comment]
I try this call `(cd Pods/React; npm run start --root '../../ReactComponent')` server launch success but after request root not found:

```
{ [NotFoundError: Cannot find entry file index.ios.js in any of the roots: ["../Pods/React"]] message: 'Cannot find entry file index.ios.js in any of the roots: ["../Pods/React"]',  name: 'NotFoundError',
  type: 'NotFoundError',  status: 404, errors:  [ { description: undefined, filename: undefined,lineNumber: undefined } ] }
```

how change root path now?

**Comment by bimawa** [comment]
Founded!!!! Somthing Wrong in new `parseCommandLine.js` replace this fail from tag v0.4.4 now woring all! Pls review this file guys: [parseCommandLine.js](https://github.com/facebook/react-native/blob/master/packager/parseCommandLine.js)

**Comment by paramaggarwal** [comment]
Ah I am also having an issue with this file when upgrading from 0.4.1 to 0.5.0. The error I get is that `source.root.forEach` is an `undefined` function - and on further analysis, `source.root` was coming as a boolean `true`, though it should be a string.

**Comment by bimawa** [comment]
@paramaggarwal yes and now i fix it local on first time.

**Comment by threepointone** [comment]
This is fixed in 0.6.0-rc with this commit https://github.com/facebook/react-native/commit/769efdfcefd55cfed4fc16752e06bea1e7604a00

**Comment by soliury** [comment]
I update to 0.6.0, also meet this problem.

**Comment by soliury** [comment]
Can anyone solve it ?

**Comment by bimawa** [comment]
@threepointone ye it not working for me.
@soliury how i write above, i just exchange parseCommandLine.js from v0.4.4 now i can work.

**Comment by soliury** [comment]
@bimawa ok, thank you .

**Comment by soliury** [comment]
@bimawa but, I have try, it failed again.

**Comment by bimawa** [comment]
@soliury  Are you sure that you were in tag v0.5.0 and replace `parseCommandLine.js` from v0.4.4 ?

**Comment by soliury** [comment]
oh, I use the tag v0.6.0-rc,

**Comment by soliury** [comment]
I have find the problem, the v0.6.0-rc don't support the es6 class, I create a new project, i change the example file to use `class xxx extends Component`, it will show this bugs.

**Comment by bimawa** [comment]
hmm ok i go try too thx

**Comment by soliury** [comment]
So, I think it's the problem of babel

**Comment by paramaggarwal** [comment]
Still getting this on `0.6.0rc` - happens for folks using a custom `--root` attribute on the packager.

```
/Users/Param/Documents/ios-app/Pods/React/packager/packager.js:71
    options.root.forEach(function(root) {
                 ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/Param/Documents/ios-app/Pods/React/packager/packager.js:71:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Process terminated. Press <enter> to close the window
```

I'm running package with a modified `launchPackager.command`.
```
#!/bin/bash

THIS_DIR=$(dirname "$0")
$THIS_DIR/Pods/React/packager/packager.sh --root $THIS_DIR/JS
echo "Process terminated. Press <enter> to close the window"
read
```

**Comment by paramaggarwal** [comment]
I confirm that using `--root` with the packager works again now in `v0.6.0rc` after previously working in `v0.4.1` for me.

**Comment by paramaggarwal** [comment]
Ok, everyone, this is the problem - when you update to `v0.6.0rc`, some of the `require()` methods have changed. For example `require('createReactIOSNativeComponentClass');` is now `var { requireNativeComponent } = require('react-native');`. The packager is actually failing internally because some of the `require()` calls are failing. This will need further debugging as to why packaging errors are not bubbling up and showing up in the terminal.

**Comment by soliury** [comment]
So how to solve it ?

**Comment by paramaggarwal** [comment]
@soliury by fixing all the `require()` calls. If a module that does not exist is inside `require()`, then it'll fail - otherwise it will work fine.

**Comment by browniefed** [comment]
@brentvatne appears this issue has been solved.
