### ISSUE TITLE
[0.59rc2 blocking] Can't compile React Native on iOS using `-force_load` instead of `-ObjC` any more

### ISSUE THREAD

**Issue by tomduncalf** [facebook/react-native#23645]
## 🐛 Bug Report

Our project can't use the `-ObjC` linker flag to discover/load all symbols as it causes "duplicate symbol" errors for some of the static libraries we use (`ObjC` is all-or-nothing flag, so we can't opt these out of it, and the "duplicate symbols" are valid as we depend on the same shared library from multiple other libraries). As RN depends on this behaviour, the alternative is to use `-force_load` for each library that needs to be loaded in this way and specify the path to the compiled (`.a`) library.

With 0.58 this compiles fine, but with 0.59rc2 it results in "duplicate symbol" errors for some Yoga references in `libReact.a`:

![screenshot 2019-02-25 at 18 10 14](https://user-images.githubusercontent.com/5458070/53359194-1ed20200-392a-11e9-9484-a5c4f5fee8c4.png)

Please let me know if you'd like more help looking into this issue or reproducing it - this would be a blocking issue for our project as we can't compile with `-ObjC`.

## To Reproduce

1. Remove `-ObjC` from  and add `-force_load libReact.a` to the "Linker Flags" section of Xcode, with the correct path to `libReact.a` (see below)

2. Clean and build, error will be displayed

I've created a repro case: https://github.com/tomduncalf/rn0.59-force-load-bug - in the interest of keeping the project simple, the path to `libReact.a` needs to be manually changed in "Linker Flags", you can discover it by going to `~/Library/Developer/Xcode/DerivedData` and looking for the directory starting `forceLoad59rc2-....` then replacing the existing one with this path (feels like there should be a `$(..)` variable pointing to this location but I've never found it!).

There is also a `rn@0.58` branch in that repo to show it compiles OK in the current release version - you may need to "Clean Build Folder" and/or clear the DerivedData folder to see the change when switching branches. 

## Expected Behavior
Project compiles with no errors as in 0.58

## Code Example
https://github.com/tomduncalf/rn0.59-force-load-bug

## Environment
```  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 126.19 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
      Yarn: 1.10.1 - ~/.yarn/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 10, 16, 23, 24, 26, 27, 28
        Build Tools: 28.0.0, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.1 => 16.8.1
      react-native: 0.59.0-rc.2 => 0.58.5
    npmGlobalPackages:
      react-native-cli: 2.0.1```

**Comment by hramos** [comment]
Thank you!

**Comment by grabbou** [comment]
@hramos do you know the status of this issue? Is there anyone working on it? We decided to hold with making 0.59 stable before there's more context here.

**Comment by kelset** [comment]
👋 @tomduncalf - can I ask you one thing? Is this issue reproducible if you test from master?

I feel that maybe also looking at the commit history for the file involved may help (maybe there have been subsequent commits that already fixed the issue but we didn't notice them)

**Comment by tomduncalf** [comment]
@kelset Going to check for you now!

**Comment by tomduncalf** [comment]
@kelset It still happens but I think I might know what is wrong... testing something out and I'll submit a PR if I can fix

**Comment by kelset** [comment]
@tomduncalf - that would be 🔥

Let us know 🤗

**Comment by tomduncalf** [comment]
So I tracked down a fix, but I think it needs looking at by someone intricately familiar with how the C++ side of React Native/Yoga to check that it wouldn't have any unintended side effects: https://github.com/facebook/react-native/pull/23823

**Comment by kelset** [comment]
That's awesome, thank you so much @tomduncalf - I've already tagged quite a few people over in the PR so that we can try to have it reviewed & merged by early next week and cherry pick before 0.59.0 🙏

**Comment by tomduncalf** [comment]
Happy to help @kelset, just `@` me if you have any further questions
