### ISSUE TITLE
WritableArray encountered a problem

### ISSUE THREAD

**Issue by bahientn9x** [facebook/react-native#27088]
I have a working module, but when I upgrade from 0.56 to 0.61, the module fails. After a specific check, the app crashed at WritableArray's PushMap function. I wonder if anything in version 0.61 has changed with regard to the module module

  ![image](https://user-images.githubusercontent.com/37149979/68068820-030dde00-fd8c-11e9-8444-2f001213f3f8.png)

React Native version:
  
![image](https://user-images.githubusercontent.com/37149979/68068845-289ae780-fd8c-11e9-8b67-9eca3b1ac804.png)

## Steps To Reproduce

1. 
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by CarstenHoyer** [comment]
This changed: https://github.com/facebook/react-native/blob/v0.61.4/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableNativeArray.java#L52-L57

Not sure how to work around this. You probably pushed a WriteableMap to the function, but now it expects a ReadableMap. My issue right now, is:

How do I convert a WriteableMap to a ReadableMap?

**Comment by CarstenHoyer** [comment]
Is this a bug?

```
WritableArray a = new WritableNativeArray();
a.pushMap(new ReadableNativeMap());
```
BeaconsAndroidModule.java:375: error: incompatible types: ReadableNativeMap cannot be converted to WritableMap
