### ISSUE TITLE
Runtime Error with Jest on 0.26.2

### ISSUE THREAD

**Issue by Bhullnatik** [facebook/react-native#7802]
Hey,

I tried upgrading our app to 0.26.2, but I'm faced with an issue when running tests with Jest (latest version):
```
 FAIL  src/utils/__tests__/NotificationsUtils-test.js
● Runtime Error
  - Error: Cannot find module 'ErrorUtils' from 'env.js'
        at Resolver.resolveModule (node_modules/jest-resolve/src/index.js:117:17)
        at Runtime._resolveModule (node_modules/jest-cli/src/Runtime/Runtime.js:214:32)
        at Object.<anonymous> (node_modules/react-native/jestSupport/env.js:22:28)
```

It seems to be coming from [`jestSupport/env.js`](https://github.com/facebook/react-native/blob/master/jestSupport/env.js#L22) but after that my knowledge of Jest is very limited but can't make much sense of it.

It doesn't work starting at `Jest@12.x.x`, previous versions work fine.

Any ideas?

**Comment by giantelk** [comment]
Ahh, I've spent hour's trying to get Jest working in v 0.26.2, I should of checked here 1st. 

My Stack Overflow Question: 
http://stackoverflow.com/questions/37474160/cannot-get-jest-react-native-working

@Bhullnatik so if I try Jest v11 it should work?

**Comment by Bhullnatik** [comment]
@giantelk Yes, it works for me with `Jest@11.x.x`.

**Comment by giantelk** [comment]
Can you post your `package.json`? Are you using require() or ES6 import in your test scripts, or something like:

```
jest
  .disableAutomock()
  .setMock('MyText', {})
  .setMock('React', {Component: class {}});
```

**Comment by cpojer** [comment]
Thank you for your patience. We launched Jest 14.0 with experimental react-native support:

* [Blog Post](http://facebook.github.io/jest/blog/2016/07/27/jest-14.html)
* [React-Native Tutorial](http://facebook.github.io/jest/docs/tutorial-react-native.html)

Please feel free to create new issues after trying out the new integration if any issues remain.

**Comment by bsy** [comment]
@cpojer is there an new version of `jest-cli` that goes with this version update? I'm currently getting the following error:

```
.../node_modules/jest-cli/src/lib/utils.js:189
  throw new Error('Unknown config option: ' + key);

Error: Unknown config option: preset
```

when I add the config to package.json:
```
  "jest": {
    "preset": "jest-react-native"
  },
```

**Comment by cpojer** [comment]
Yes, update to 14.0.
