### ISSUE TITLE
Failed to run on emulator after upgrading from 0.42.3 to 0.43.0

### ISSUE THREAD

**Issue by tuandt** [facebook/react-native#13287]
After upgrading from 0.42.3 to 0.43.0 I got this error when using ListView:
undefined is not a function (evaluating 'this.updater.enqueueCallback(this, callback, 'setState')')

Does anyone got the same error like this?

### Additional Information

* React Native version: 0.43.0
* Platform: Android
* Development Operating System: Windows
* Dev tools: Android Studio version

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by yunnywu** [comment]
I got this same issue when use ListView

**Comment by rom1k** [comment]
Did you find a solution? I'm getting this error also after a fresh install of react native. It works fine on my other computer and nothing in the project has changed.

**Comment by jneuendorf** [comment]
@rom1k Could you say what version the _old version_ of node was? I have v8.3.0 and still get the same error.
