### ISSUE TITLE
[RN 0.70.0] _reactNative.DeviceEventEmitter.removeListener is not a function after upgrade RN 0.64.0 => 0.70.0

### ISSUE THREAD

**Issue by phamthanh1003** [facebook/react-native#34644]
### Description

After upgrade RN from 0.64.0 to 0.70.0 i'm facing the render error. (image)
![IMG_532AA06BB309-1](https://user-images.githubusercontent.com/46913798/189330178-db1a1eef-a131-4969-86cb-66703e3ae583.jpeg)

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.32 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

The app was crash after i press button back to previous navigation.

### Snack, code example, screenshot, or link to a repository

![IMG_532AA06BB309-1](https://user-images.githubusercontent.com/46913798/189330866-5054a918-91ac-480c-bba6-a3a52806c904.jpeg)

**Comment by SaidKherif** [comment]
As i know, removeListener is deprecated in 0.70. You have to remove them and replace it by .remove().

If removeListener is use in a 3rd party library, you can try to update your lib to last version or try to patch it.

**Comment by kelset** [comment]
as pointed out by @SaidKherif, those deprecated methods were removed in 0.70: https://github.com/facebook/react-native/blob/main/CHANGELOG.md#removed

**Comment by anshif10** [comment]
> as pointed out by @SaidKherif, those deprecated methods were removed in 0.70: https://github.com/facebook/react-native/blob/main/CHANGELOG.md#removed

i have the same problem .
.when i'm press back error comes .


i changed

 const listener = AppState.addEventListener('change', handleAppStateChange);
    
to  this


        const listener = AppState.addEventListener('change', handleAppStateChange);
        listener.remove()

 but still error

![Screenshot_1664434157](https://user-images.githubusercontent.com/90393426/192959595-f3a57f23-9fc5-49b5-98e0-6832c380055e.png)

**Comment by anshif10** [comment]
> as pointed out by @SaidKherif, those deprecated methods were removed in 0.70: https://github.com/facebook/react-native/blob/main/CHANGELOG.md#removed

i have addEventListener. is this making problem?


         EventRegister.addEventListener('socketErrorMessageReceived', (data) => {
         
            showMessage({
              message: data.Message,
              type: "danger",
              position : 'bottom'
            });
         });

**Comment by jarapamikaella** [comment]
hi, I'm still experiencing this issue with the new react-native 0.70.0 version, is there any other issues that are causing this?

**Comment by Genking01** [comment]
My package version:  react native@0.71.3, react-native-modal@13.0.1

```
--- a/node_modules/react-native-modal/dist/modal.js
+++ b/node_modules/react-native-modal/dist/modal.js
@@ -453,10 +453,10 @@ export class ReactNativeModal extends React.Component {
         if (this.state.isVisible) {
             this.open();
         }
-        BackHandler.addEventListener('hardwareBackPress', this.onBackButtonPress);
+        this.backHandler = BackHandler.addEventListener('hardwareBackPress', this.onBackButtonPress);
     }
     componentWillUnmount() {
-        BackHandler.removeEventListener('hardwareBackPress', this.onBackButtonPress);
+        this.backHandler.remove();
         if (this.didUpdateDimensionsEmitter) {
             this.didUpdateDimensionsEmitter.remove();
         }
```
Please try to use the version of modal to match my package!
This fixed my environment.

**Comment by bzozoo** [comment]
In "react-native": "0.71.7", It is work well

**Comment by pratik007kumar** [comment]
In "react-native": "0.71.8", It is work well

**Comment by moustaouiSalaheddine** [comment]
**removeListener()** method is deprecated in react-native +0.70

in new version we use **subscription?.remove()**

**Solution** : [https://stackoverflow.com/a/76491163/14724559](https://stackoverflow.com/a/76491163/14724559)

it's Work ^^
