### ISSUE TITLE
Error: Requiring unknown module "202"

### ISSUE THREAD

**Issue by thanksmister** [facebook/react-native#11568]
### Description

Following the React Native Getting Starting guide for Android results in error Requiring unknown module "202" [https://facebook.github.io/react-native/docs/getting-started.html](url)

```
Error: Requiring unknown module "202".If you are sure the module is there, try restarting the packager or running "npm install". (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:152)

unknownModuleError@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:215:13
loadModuleImplementation@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:152:25
guardedLoadModule@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:133:37
_require@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:124:18
global code@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:72844:9
```

![image](https://cloud.githubusercontent.com/assets/142340/21363631/3c73aeee-c6cc-11e6-8a2e-a2b7f61341cb.png)

### Reproduction

Follow the steps in the Getting Started guide for Android and create a new project called AwesomeProject and then run the application in the emulator. 

### Solution

So far I am not able to resolve the issue. I tried npm install and made sure I had the latest react, but nothing fixes the issue.  I also tried with different Android API versions (23, 25).   I previously had another project that was working under 0.37 but that project has the same error
 after upgrading the project to 0.39.2.

### Additional Information

* React Native version: 0.39.2
* Platform: Android 
* Operating System: MacOS (Sierra)

**Comment by thanksmister** [comment]
Some more information. The same error occurs on both iOS and Android emulator.  By running Enable Hot Reload I received additional information for the error:

```
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false

Body:
{"message":"TransformError: /Users/mritchie/ReactNativeProjects/LocalTraderReact/index.android.js: Cannot find module 'babel-plugin-react-transform'","type":"TransformError","errors":[{}]}
onResponse
    DevServerHelper.java:323
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:761

```

![missing_babel](https://cloud.githubusercontent.com/assets/142340/21426495/f8bf6d92-c82d-11e6-8259-6c5ba6bf99d7.png)

**Comment by thanksmister** [comment]
Restarting packager fixed the issue.
