### ISSUE TITLE
fatal error: 'fbjni/fbjni.h' file not found

### ISSUE THREAD

**Issue by talentedman** [facebook/react-native#52104]
## Issue Title
**fatal error: 'fbjni/fbjni.h' file not found during Android build with NDK 27.1.12297006**

### Environment
- **React Native version**: 0.80.0
- **Platform**: Android
- **Operating System**: Windows
- **NDK version**: 27.1.12297006
- **Gradle version**: 8.14.1
- **Target architecture**: aarch64-none-linux-android24

### Description
When building a React Native project for Android, the compilation fails with a fatal error indicating that the `fbjni/fbjni.h` header file cannot be found. This occurs during the compilation of `react-native-gesture-handler` but the root cause appears to be in React Native's core files.

### Steps to Reproduce
1. Create a new React Native project (version 0.80.0)
2. Install `react-native-gesture-handler`
3. Attempt to build the Android project
4. The build fails during native compilation

### Expected Behavior
The project should build successfully without missing header file errors.

### Actual Behavior
Build fails with the following error:
```
fatal error: 'fbjni/fbjni.h' file not found
```

### Error Details
The error occurs in the React Native core file:
```
D:/code/app/AwesomeProject/node_modules/react-native/ReactCommon/react/renderer/core/State.h:11:10: fatal error: 'fbjni/fbjni.h' file not found
   11 | #include <fbjni/fbjni.h>
      |          ^~~~~~~~~~~~~~~
```

### Full Error Log
```bash
C:\Users\chenw\AppData\Local\Android\Sdk\ndk\27.1.12297006\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --sysroot=C:/Users/chenw/AppData/Local/Android/Sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgesturehandler_EXPORTS -ID:/code/app/AwesomeProject/node_modules/react-native/ReactCommon -isystem C:/Users/chenw/.gradle/caches/8.14.1/transforms/89ee2d71482aa90a74abf94579aa4b78/transformed/react-android-0.80.0-debug/prefab/modules/reactnative/include -isystem C:/Users/chenw/.gradle/caches/8.14.1/transforms/89ee2d71482aa90a74abf94579aa4b78/transformed/react-android-0.80.0-debug/prefab/modules/jsi/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D__BIONIC_NO_PAGE_SIZE_MACRO -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -O2 -frtti -fexceptions -Wall -Werror -std=c++20 -DANDROID -fno-limit-debug-info -fPIC -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_CFG_NO_COROUTINES=1 -DFOLLY_MOBILE=1 -DFOLLY_HAVE_RECVMMSG=1 -DFOLLY_HAVE_PTHREAD=1 -DFOLLY_HAVE_XSI_STRERROR_R=1 -MD -MT CMakeFiles/gesturehandler.dir/cpp-adapter.cpp.o -MF CMakeFiles\gesturehandler.dir\cpp-adapter.cpp.o.d -o CMakeFiles/gesturehandler.dir/cpp-adapter.cpp.o -c D:/code/app/AwesomeProject/node_modules/react-native-gesture-handler/android/src/main/jni/cpp-adapter.cpp

In file included from D:/code/app/AwesomeProject/node_modules/react-native-gesture-handler/android/src/main/jni/cpp-adapter.cpp:4:
In file included from D:/code/app/AwesomeProject/node_modules/react-native/ReactCommon/react/renderer/uimanager/primitives.h:14:
In file included from D:/code/app/AwesomeProject/node_modules/react-native/ReactCommon/react/renderer/core/ShadowNode.h:22:
D:/code/app/AwesomeProject/node_modules/react-native/ReactCommon/react/renderer/core/State.h:11:10: fatal error: 'fbjni/fbjni.h' file not found
   11 | #include <fbjni/fbjni.h>
      |          ^~~~~~~~~~~~~~~
```

### Additional Context
- This appears to be related to missing fbjni (Facebook JNI) headers in the build configuration
- The issue seems to affect third-party libraries that depend on React Native's core renderer components[[1]](https://ask.csdn.net/questions/7984984)
- Similar issues have been reported with other React Native projects[[3]](https://segmentfault.com/a/1190000016601700?sort=votes)

### Possible Solutions to Investigate
1. Check if fbjni headers are properly included in the React Native distribution
2. Verify CMake configuration for including fbjni paths
3. Ensure compatibility between NDK version 27.1.12297006 and React Native 0.80.0

### Labels
`Platform: Android` `Type: Bug` `Component: Build` `Needs: Triage`

### Steps to reproduce

"react-native-gesture-handler": "2.24.0"

android build

### React Native Version

0.80

### Affected Platforms

Build - Windows, Runtime - Android

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: Windows 11 10.0.26100
  CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
  Memory: 12.17 GB / 31.82 GB
Binaries:
  Node:
    version: 20.18.0
    path: ~\.nvmd\versions\20.18.0\node.EXE
  Yarn:
    version: 1.22.22
    path: ~\.nvmd\versions\20.18.0\yarn.CMD
  npm:
    version: 10.8.2
    path: ~\.nvmd\versions\20.18.0\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-35 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
IDEs:
  Android Studio: AI-243.22562.218.2431.13114758
  Visual Studio: Not Found
Languages:
  Java: 17.0.14
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 19.0.0
    wanted: 19.0.0
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.80.0
    wanted: 0.80.0
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
C:\Users\chenw\AppData\Local\Android\Sdk\ndk\27.1.12297006\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --sysroot=C:/Users/chenw/AppData/Local/Android/Sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dgesturehandler_EXPORTS -ID:/code/app/AwesomeProject/node_modules/react-native/ReactCommon -isystem C:/Users/chenw/.gradle/caches/8.14.1/transforms/89ee2d71482aa90a74abf94579aa4b78/transformed/react-android-0.80.0-debug/prefab/modules/reactnative/include -isystem C:/Users/chenw/.gradle/caches/8.14.1/transforms/89ee2d71482aa90a74abf94579aa4b78/transformed/react-android-0.80.0-debug/prefab/modules/jsi/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D__BIONIC_NO_PAGE_SIZE_MACRO -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O2 -frtti -fexceptions -Wall -Werror -std=c++20 -DANDROID -fno-limit-debug-info  -fPIC -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_CFG_NO_COROUTINES=1 -DFOLLY_MOBILE=1 -DFOLLY_HAVE_RECVMMSG=1 -DFOLLY_HAVE_PTHREAD=1 -DFOLLY_HAVE_XSI_STRERROR_R=1 -MD -MT CMakeFiles/gesturehandler.dir/cpp-adapter.cpp.o -MF CMakeFiles\gesturehandler.dir\cpp-adapter.cpp.o.d -o CMakeFiles/gesturehandler.dir/cpp-adapter.cpp.o -c D:/code/app/AwesomeProject/node_modules/react-native-gesture-handler/android/src/main/jni/cpp-adapter.cpp

In file included from D:/code/app/AwesomeProject/node_modules/react-native-gesture-handler/android/src/main/jni/cpp-adapter.cpp:4:
In file included from D:/code/app/AwesomeProject/node_modules/react-native/ReactCommon/react/renderer/uimanager/primitives.h:14:
In file included from D:/code/app/AwesomeProject/node_modules/react-native/ReactCommon/react/renderer/core/ShadowNode.h:22:
D:/code/app/AwesomeProject/node_modules/react-native/ReactCommon/react/renderer/core/State.h:11:10: fatal error: 'fbjni/fbjni.h' file not found
   11 | #include <fbjni/fbjni.h>
      |          ^~~~~~~~~~~~~~~
```

### MANDATORY Reproducer

https://github.com/talentedman/rn0.80.0-bug-fbjni-demo

### Screenshots and Videos

![Image](https://github.com/user-attachments/assets/c04804c8-1408-4736-8608-c0461413b0a2)

**Comment by talentedman** [comment]
> Warning
> 
> **Could not parse version**: We could not find or parse the version number of React Native in your issue report. Please use the template, and report your version including major, minor, and patch numbers - e.g. 0.76.2.

0.80.0

**Comment by migueldaipre** [comment]
Hey @talentedman, thanks for reporting this issue.

Does the error disappear when you remove the `react-native-gesture-handler` library?

The only version that supports RN 0.80 is this [one](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.26.0).

**Comment by talentedman** [comment]
> Hey [@talentedman](https://github.com/talentedman), thanks for reporting this issue.
> 
> Does the error disappear when you remove the `react-native-gesture-handler` library?
> 
> The only version that supports RN 0.80 is this [one](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.26.0).

thanks, solution
