### ISSUE TITLE
cocoapods: undefined method `end_with?' for nil:NilClass

### ISSUE THREAD

**Issue by regalstreak** [facebook/react-native#44714]
### Description

[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `end_with?' for nil:NilClass

### Steps to reproduce

Run 
`bundle exec pod install`
after upgrading to react-native 0.74.1 from 0.69.4 without a privacy manifest file

### React Native Version

0.74.1

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
➜  proteus git:(feat-rn-0.74.1) ✗ npx react-native info
warn Package @react-native-community/google-signin contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 225.00 MB / 32.00 GB
  Shell:
    version: 3.7.0
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 20.10.0
    path: ~/Library/Caches/fnm_multishells/13286_1717040337826/bin/node
  Yarn:
    version: 3.6.4
    path: ~/Library/Caches/fnm_multishells/13286_1717040337826/bin/yarn
  npm: Not Found
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Installing react-native-video (5.2.1)
Installing react-native-webengage (1.3.0)
Installing react-native-webview (11.26.0)
Installing simdjson (3.1.0-wmelon1)
Generating Pods project
Setting USE_HERMES build settings
Setting REACT_NATIVE build settings
[Ccache]: Ccache found at /opt/homebrew/bin/ccache
[Ccache]: Pass ':ccache_enabled => true' to 'react_native_post_install' in your Podfile or set environment variable 'USE_CCACHE=1' to increase the speed of subsequent builds
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `end_with?' for nil:NilClass

/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:83:in `block in get_privacyinfo_file_path'
/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:83:in `each'
/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:83:in `find'
/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:83:in `get_privacyinfo_file_path'
/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:10:in `add_aggregated_privacy_manifest'
/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/react_native_pods.rb:301:in `react_native_post_install'
/Users/regalstreak/dev/headout/proteus/ios/Podfile:104:in `block (3 levels) in from_ruby'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:149:in `message'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:183:in `integrate'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:170:in `install!'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/command/update.rb:63:in `run'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/bin/pod:23:in `load'
/Users/regalstreak/dev/headout/proteus/vendor/bundle/ruby/2.6.0/bin/pod:23:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

[!] [Codegen] warn: using experimental new codegen integration
```

### Reproducer

https://github.com/regalstreak/react-native

**Comment by regalstreak** [comment]
Looks like its already solved in main.
Patch to make it work:

```
diff --git a/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb b/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb
index 7600829..220d5d5 100644
--- a/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb
+++ b/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb
@@ -67,12 +67,10 @@ module PrivacyManifestUtils
     end
 
     def self.ensure_reference(file_path, user_project, target)
-        reference_exists = target.resources_build_phase.files_references.any? { |file_ref| file_ref.path.end_with? "PrivacyInfo.xcprivacy" }
+        reference_exists = target.resources_build_phase.files_references.any? { |file_ref| file_ref.path&.end_with? "PrivacyInfo.xcprivacy" }
         unless reference_exists
             # We try to find the main group, but if it doesn't exist, we default to adding the file to the project root – both work
-            file_root = user_project.root_object.main_group.children.find { |group|
-                group.class == Xcodeproj::Project::Object::PBXGroup && (group.name == target.name || group.path == target.name)
-            } || user_project
+            file_root = user_project.root_object.main_group.children.find { |group| group.class == Xcodeproj::Project::Object::PBXGroup && (group.name == target.name || group.path == target.name) } || user_project
             file_ref = file_root.new_file(file_path)
             build_file = target.resources_build_phase.add_file_reference(file_ref, true)
         end
@@ -80,11 +78,10 @@ module PrivacyManifestUtils
 
     def self.get_privacyinfo_file_path(user_project, targets)
         file_refs = targets.flat_map { |target| target.resources_build_phase.files_references }
-        existing_file = file_refs.find { |file_ref| file_ref.path.end_with? "PrivacyInfo.xcprivacy" }
+        existing_file = file_refs.find { |file_ref| file_ref.path&.end_with? "PrivacyInfo.xcprivacy" }
         if existing_file
             return existing_file.real_path
         end
-
         # We try to find a file we know exists in the project to get the path to the main group directory
         info_plist_path = user_project.files.find { |file_ref| file_ref.name == "Info.plist" }
         if info_plist_path.nil?
@@ -108,11 +105,12 @@ module PrivacyManifestUtils
                 if File.basename(file_path) == 'PrivacyInfo.xcprivacy'
                     content = Xcodeproj::Plist.read_from_path(file_path)
                     accessed_api_types = content["NSPrivacyAccessedAPITypes"]
-                    accessed_api_types.each do |accessed_api|
-                    api_type = accessed_api["NSPrivacyAccessedAPIType"]
-                    reasons = accessed_api["NSPrivacyAccessedAPITypeReasons"]
-                    used_apis[api_type] ||= []
-                    used_apis[api_type] += reasons
+                    accessed_api_types&.each do |accessed_api|
+                      api_type = accessed_api["NSPrivacyAccessedAPIType"]
+                      reasons = accessed_api["NSPrivacyAccessedAPITypeReasons"]
+                      next unless api_type
+                      used_apis[api_type] ||= []
+                      used_apis[api_type] += reasons
                     end
                 end
                 end
```
