### ISSUE TITLE
[0.66.1] enableTls12OnPreLollipop(client).build(); return error cannot find symbol

### ISSUE THREAD

**Issue by zarepp** [facebook/react-native#32478]
### Description

After upgrade to version 0.66.1, I'm facing issue with OkHttpClientProvider.enableTls12OnPreLollipop(client).build() which cannot find symbol. It is works on 0.64.3.

Environment: **ANDROID**

### Version

0.66.1

### Output of `react-native info`

info Fetching system and libraries information...

System:
    OS: macOS 12.0
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 90.30 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/myunifi/node_modules/.bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- use 0.66.1 version
- use OkHttpClientProvider.setOkHttpClientFactory(new OkHttpCertPin()) in MainActivity.java
- inside OkHttpCertPin use method OkHttpClientProvider.enableTls12OnPreLollipop(client).build();

**Comment by QureshiFaizan** [comment]
+1

**Comment by zarepp** [comment]
updated issue for android

**Comment by cortinico** [comment]
> After upgrade to version 0.66.1, I'm facing issue with OkHttpClientProvider.enableTls12OnPreLollipop(client).build() which cannot find symbol

What's the stacktrace?
