### ISSUE TITLE
[RCT_EXPORT_MODULE] Not working when React Native is installed as a node module

### ISSUE THREAD

**Issue by dsibiski** [facebook/react-native#2254]
I have a Bridge Module that needs to install React Native as a node_module for unit testing purposes. It has React Native as a `peerDependency` when used normally, but in order to test it on it's own, I include React Native as a node_module. (manually install it in Travis CI before running the tests).

This has worked fine in RN 0.6.0 <, however, it seems like it broke in 0.7.1 >.

In 0.7.1 > I am getting this error when trying to build the project without it being embedded in a parent project.

```
Undefined symbols for architecture x86_64:
  "_RCTRegisterModule", referenced from:
      +[RNUserDefaultsIOS load] in libRNUserDefaultsIOS.a(RNUserDefaultsIOS.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My module is here: https://github.com/dsibiski/react-native-userdefaults-ios

The problem can be replicated by installing the latest RN manually via `npm i react-native`...opening the `RNUserDefaultsIOS.xcworkspace` and trying to Build or Test the package.

Perhaps I'm going about testing my module all wrong, is there a better way to do this? I don't think there is much testing of Obj-C modules out in the wild right now, but it would be nice to have something defined so that it could get more popular.

**Comment by dsibiski** [comment]
The changes seem to have been added with this commit: https://github.com/facebook/react-native/commit/e9095b2f4277918c7b62d2e3dab3f77e79ca4776#diff-bac72910e72250822c478f2a68c2ace7

@tadeuzagallo Do you have any insights or thoughts on this?

**Comment by nicklockwood** [comment]
I think this is happening because your module previously didn't call any functions from React native core, so it happened to be testable without linking React, provided that the headers were reachable.

Now we've changed the registration system so that it calls an RN function, it needs React Native to be linked into the project in order to work.

You could fix this in a hacky way by just declaring an empty RCTRegisterModule function locally in your test project so that the linker can find it.

**Comment by dsibiski** [comment]
Thanks @nicklockwood, that makes sense, I'll try that out.

**Comment by dsibiski** [comment]
You helped me to see that I just needed to modify my test target to only include the pure Obj-C file that I was testing (since there were no tests that had anything to do with RN), works perfectly! No hacks needed! Thanks again @nicklockwood.

**Comment by nicklockwood** [comment]
No problem!

(FWIW, React Native now includes support for NSUserDefaults though, in the form of RCTSettings / Settings.js)

**Comment by tuckg** [comment]
I have the same problem, but project can run well if I add #import <React/RCTRootView.h> to AppDelegate.m, I dont know why
