### ISSUE TITLE
[ScrollView] Scrolling ends prematurely in ScrollViews embedded in a parent ScrollView

### ISSUE THREAD

**Issue by jordanna** [facebook/react-native#41]
You can see this behavior in the UIExplorer app's `<ScrollView>` example. Fling to initiate a scroll in an inner `ScrollView` and fling again (before scrolling ends) to increase scroll momentum. Often times, this causes the scrolling to stop.

I haven't had gone through all of the `ResponderEventPlugin` code yet, but I'm seeing that when `ResponderEventPlugin.extractEvents` is called, the `topLevelTargetID` is sometimes incorrect.

The touches that unintentionally stop scrolling appear to be associated with the parent `ScrollView` instead of the inner `ScrollView`'s content. I traced this down to `RTCScrollView._shouldDisableScrollInteraction` where `[self isDescendantOfView:JSResponder]` is sometimes `YES`. Forcing it to always return `NO` fixes the issue, but I'm pretty sure that's not the intention of this method :)

**Comment by nick** [comment]
Running into this issue too - I don't suppose there's been any progress here?

**Comment by jordwalke** [comment]
@vjeux, this is the kind of troubles we're having with native scroll views. The responder system solves it and I don't know how to solve it while using the UIScrollViews.

**Comment by nicholasstephan** [comment]
Any movement on this one? I have a similar example up on stack overflow (http://stackoverflow.com/questions/29756217/react-native-nested-scrollview-locking-up) that nobody has been able to answer.

**Comment by Shuangzuan** [comment]
@nicholasstephan Modify `node_modules/react-native/Libraries/Components/ScrollResponder.js`:
Line 136:
```
  scrollResponderHandleScrollShouldSetResponder: function(): boolean {
    return true; // this.state.isTouching;
  },
```

**Comment by magicismight** [comment]
Is there any progress here?

**Comment by spicyj** [comment]
Maybe with subclassing, you can make a `disableOffsetUpdates` like in the gist linked here:

https://twitter.com/andy_matuschak/status/559796157241507841

Not sure if that introduces significant lag.

**Comment by sahrens** [comment]
what do you think, @ide?  You seem to have the most experience with nesting and composing scroll views...

**Comment by PhilippKrone** [comment]
@ide @sahrens Any movement on this issue? I think i have exactly the same problem.

**Comment by ide** [comment]
I'm not actively looking into this. Based on what I've heard from other people and from reading this discussion, the solution could be quite hard or non-obvious without advanced knowledge of gesture systems. I have a thought regarding some of the discussion above...

> Do you know of a way to have UIScrollViews be disabled by default and then reenabled?

Might be possible through the gesture recognizers by adding a custom gesture recognizer that communicates with the JS layer. I think you can tell UIScrollView's private gesture recognizers to need this custom gesture recognizer to fail -- this might let JS allow/disallow the private gesture recognizers to become active.

**Comment by sahrens** [comment]
I think @andreic has been looking at this a bit?

**Comment by sghiassy** [comment]
I'm having this issue as well. Any insights into which files to start looking into first?

**Comment by Shimaa-Hassan** [comment]
any solution?

**Comment by brentvatne** [comment]
ping @andreic :smile: we need you

**Comment by bradens** [comment]
+1 Also hitting this nasty one.  Would look into it if I had more experience with gesture systems.

**Comment by amormysh** [comment]
+1

**Comment by dubert** [comment]
:+1:

**Comment by rxb** [comment]
For people looking for a temporary fix, I've had success with [Shuangzuan's comment ](https://github.com/facebook/react-native/issues/41#issuecomment-101958352) without any obvious ill-effects, though I'm sure the original code is there for a reason that I'm just not running into in my project.

**Comment by ericvicenti** [comment]
cc @spicyj @jordwalke, I heard we were close to a fix on this?

**Comment by jordwalke** [comment]
@ericvicenti: @spicyj Figured out a way to delay the activation of a UIKit gesture recognizer until JS tells it to activate. The final solution then, it to have all scroll views start out disabled, then wait for the JS responder system to tell them that they are enabled. Then all of the logic is perfectly controllable (and cross platform) in JS. The remaining work is to actually implement the starts-out-disabled-until-instructed-otherwise behavior for native UIKit scroll views, and then to build the gesture logic for detecting when a scroll view should become enabled in JS (that part is fairly trivial).

**Comment by alejomendoza** [comment]
+1 since I updated to 0.9.0

**Comment by adarshmuthappa** [comment]
Same error as @alejomendoza 
happens when I scroll a listview and since I updated to 0.9.0

**Comment by ide** [comment]
Do a deep clean of your git repo and make sure when you rerun npm install that you have only one copy of React Native at all. This is likely caused by version mismatches.

**Comment by adarshmuthappa** [comment]
Great I did what you said and it works now! Thanks!

**Comment by traviskochel** [comment]
I've been having a similar issue with nested ScrollViews locking up (in v 0.11.0). I tried all of the solutions above with no luck.

For me, the interim fix was to set the method below, in ScrollResponder.js, to false.

```
 scrollResponderHandleTerminationRequest: function(): boolean {
    // return !this.state.observedScrollSinceBecomingResponder;
    return false;
  },
```

It seems as though if I set a panResponder for `onResponderTerminationRequest` (or `onPanResponderTerminationRequest`) it gets ignored, and it's overridden by the above. 

I'm sure there is a good reason why this is the case though, so it'd be good to get an insiders thoughts. The hack seems to work though, and I have no problems switching between two ScrollViews.

The one side effect is I get this warning, when it would normally lock up. 
`Warning: ScrollView doesn't take rejection well - scrolls anyway`

**Comment by everfire130** [comment]
@traviskochel good!

**Comment by agmcleod** [comment]
I'm getting a similar error in 0.11, but only when i bundle js, not when i run it off the server. Cache maybe?

message: ReactInstanceHandles._getFirstCommonAncestorID is not a function. (In \'ReactInstanceHandles._getFirstCommonAncestorID(responderID,topLevelTargetID)\', \'ReactInstanceHandles._getFirstCommonAncestorID\' is undefined)'

**Comment by ide** [comment]
@agmcleod sounds like you are running JS that doesn't match your native binary.

**Comment by agmcleod** [comment]
@ide i did a clear in xcode, as well as deleted the main.bundlejs to be safe. I also did a non minified build to get that above error, so i know it is loading my latest file at least.

I also generated a new project to upgrade to 0.11, since the structure changed to support both ios & android.

**Comment by ide** [comment]
Can you check your node_modules to make sure there is only one copy of react-native? Conflicts can occur if you are using npm packages that have react-native in their dependencies.

**Comment by agmcleod** [comment]
@ide ah shoot that's the problem, was referencing an older fork of mine. My apologies, I thought i had changed that when i updated :)

**Comment by arianitu** [comment]
Does anyone know what breaks if you just return false in scrollResponderIsAnimating (ScrollResponder.js) 

It seems to fix the issue for me as well.

**Comment by bogdantmm92** [comment]
@arianitu that solves the problem indeed! Thanks

**Comment by webmanarmy** [comment]
Is anyone actively working on this? I find myself scanning each changelog hoping to see this has been fixed

**Comment by bradennapier** [comment]
+1 - running into the issue as well

**Comment by votive** [comment]
+1 - getting this issue when I have a horizontal scroll view nested in a list view.

**Comment by toddw** [comment]
+1 - I'm running into this issue.

**Comment by praisegeek** [comment]
+1 ran into this issue

**Comment by brentvatne** [comment]
So leaving this in an issue isn't doing much good it seems -- this issue has been open for a very long time now, so I'm going to move it over to ProductPains, please vote it up there if you still think that this is an important fix: https://productpains.com/post/react-native/scrolling-ends-prematurely-in-scrollviews-embedded-in-a-parent-scrollview/

**Comment by toddw** [comment]
I don't agree with the closing of this ticket. What is product pains? Who is going to look there for this? It seems to me that this issue has gotten a lot more attention recently and having it open is a good way for people to know that it is a known issue. Hopefully the extra attention here will help the right person who can fix it notice the issue. Is there a reason why this can't be fixed?

**Comment by arianitu** [comment]
I agree. I went to product pains and didn't understand what it was (and you have to sign up) It's probably better to just talk about development issues here? We're all on here already.

Nested scroll views are super common, so this issue is so big that I would never consider using react-native for a serious application until it's fixed. I'm considering migrating my current application to native because there doesn't seem to be a good solution to this.

If you return false in scrollResponderIsAnimating, you run into strange issues. You'll be scrolling in a nested scroll view, tap on the screen, and it will go into the item instead of stopping. It fixes the issue where it doesn't accelerate, but then touches go through when they're not suppose to.

What's the deal here, why is this not a higher priority?

**Comment by brentvatne** [comment]
@toddw @arianitu - thanks for your passion!

Take a look at the issue count: 815. Everything on here is getting buried quickly. This is issue #41 and it has been open for nearly a year. Clearly *something* isn't working with the approach of leaving an issue open until someone fixes it. Right now this issue is just one of 815 and more recent issues get more attention because they appear at the top of the issue feed.

> What's the deal here, why is this not a higher priority?

This isn't a higher priority for a simple reason: "If everything is a priority, nothing is a priority." What I mean by that is this: many other issues have people like yourselves (nothing against any of you, I totally understand where you're coming from) who believe that their issue should be the number one priority. And core developers on React Native also have their own priorities: product teams within Facebook, and our own companies (for those outside of Facebook). The open source community is one (very important) stakeholder.

So when it comes to open source, we don't have the bandwidth to fix every issue that comes up, so we want to focus on those issues that are impacting the greatest number of users. By using ProductPains we are able to get a better idea of what those issues are -- you can use some heuristics like total number of comments to take a guess at it on Github but we haven't had much luck with that. We tried this before: http://react-native-issues.divshot.io/ (this hasn't been updated for a couple of months because I found it wasn't very helpful -- maybe some people commented to help or other reasons).

@vjeux had the idea to use ProductPains a couple of weeks ago and shared it on Twitter: https://twitter.com/Vjeux/status/660858303468040192 -- we're just trying to find a way to make sense of all of the noise and better deal with the huge number of requests we get from the community. I'm very open to other ideas though, please feel free to suggest alternatives!

**Comment by ide** [comment]
We've added a few links to Product Pains to this repo's README. It's quite helpful to see all the upvotes and the most popular issues at a glance, while GitHub +1's just haven't addressed this need. Already the Product Pains version of this issue has 17 upvotes and will bubble up to the top compared to being permanently buried as issue #41 on GitHub.

When someone has a clear articulation of the issue and suggestions for a structurally correct fix, a GitHub issue will be much more actionable and likely to be addressed in a more timely way.

**Comment by mkonicek** [comment]
Github issues are not working well for us - we are a very small team and and need a way to prioritize. A good way to prioritize is to let people vote on issues and Product Pains lets you do exactly that.

You can get an estimate by sorting github issues by the number of comments but it's not that reliable: https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc

**Comment by toddw** [comment]
@brentvatne @ide @mkonicek fair enough, thanks for the explanations

**Comment by brentvatne** [comment]
@toddw - no problem :) thanks for weighing in on ProductPains!

**Comment by alizain** [comment]
<a href="http://dev-buildwithlove.elasticbeanstalk.com/facebook/react-native/issues/41/vote"><img src="http://dev-buildwithlove.elasticbeanstalk.com/facebook/react-native/issues/41.png" alt="BuildWithLove"></a>

**Comment by arianitu** [comment]
This has been fixed in this commit https://github.com/facebook/react-native/commit/67bf0f1a70aa6efc667a6fe4499ae7c2212332ff and should be coming to 0.17. Yay!

https://productpains.com/post/react-native/scrolling-ends-prematurely-in-scrollviews-embedded-in-a-parent-scrollview/

**Comment by toddw** [comment]
So stoked to see this fixed! Thanks so much!

**Comment by aksonov** [comment]
@arianitu I still see this issue in latest 0.19, why?

**Comment by Taakn** [comment]
+1 I still get it

**Comment by MrPluto** [comment]
+1

**Comment by jalliance** [comment]
+1

**Comment by maraujop** [comment]
I see this happenning in 0.20 too

**Comment by neverlan** [comment]
+1 seeing this issue too

**Comment by faceyspacey** [comment]
+1 still seeing this issue. is there really no workarounds? Disabling scrolling on the parent causes lots of jerkiness.

**Comment by Havi4** [comment]
+1,I see this issue in 0.22 too

**Comment by sandect** [comment]
+1,I see this issue in 0.22 too

**Comment by YashYash** [comment]
+1 still seeing it in .20 as well.

**Comment by neiker** [comment]
+1 in 0.30.0

**Comment by dgurns** [comment]
Still seeing the same issue in 0.41!

**Comment by joaosilva05** [comment]
+1, also happening in 0.41

**Comment by bintoll** [comment]
+1

**Comment by shukerullah** [comment]
+1, 0.48.3

**Comment by binchik** [comment]
+1, 0.51.0

**Comment by lishoulong** [comment]
+1, 0.50.3, And I try the following way ,but not use.

UPDATE: I find if the scroll view is currently animating and wants to become the responder, then it will reject. Line 189 in ScrollResponder.js. So I modify Line 340 and it work for me:

scrollResponderIsAnimating: function(): boolean {
  // var now = Date.now();
  // var timeSinceLastMomentumScrollEnd = now - this.state.lastMomentumScrollEndTime;
  // var isAnimating = timeSinceLastMomentumScrollEnd < IS_ANIMATING_TOUCH_START_THRESHOLD_MS ||
  //   this.state.lastMomentumScrollEndTime < this.state.lastMomentumScrollBeginTime;
  // return isAnimating;
    return false;
},

**Comment by koloff** [comment]
+ 1 0.53.0

**Comment by ahmad2smile** [comment]
20-godamn-18 and still solution by @Shuangzuan is working and had to do it.

**Comment by lumiasaki** [comment]
+1 0.52.0

My scenario is using a root view in a native view controller as a separated view on iOS platform, the root view contains a <ScrollView/> component as container view, the items which in scrollview are <TouchableWithoutFeedback/>. When I scroll the scrollview, before the `scrollViewDidEndDecelerating:` function of UIScrollView been invoked, I press some button pushing the current view controller to another one, the `scrollViewDidEndDecelerating:` function will never been invoked.

When I pop back to the previous view controller, I press down the <TouchableWithoutFeedback/> in <ScrollView/> will have no effect, because the `scrollResponderIsAnimating` function in ScrollResponder.js, will return true because of `this.state.lastMomentumScrollEndTime < this.state.lastMomentumScrollBeginTime`( last momentum scroll end time didn't set properly because `scrollViewDidEndDecelerating:` in UIScrollView not been invoked ) , the gesture system thought that scrollview was still animating, and then the scrollview will capture the response event, not pass it to <TouchableWithoutFeedback/>.

My solution is return false from `scrollResponderIsAnimating` directly, but I'm still looking for a better solution.
