### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/inject/Provider;

### ISSUE THREAD

**Issue by alen252** [facebook/react-native#29671]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
After I upgradereact native from 0.51.0 to 0.61.5, I start my app. Got a crash.

## React Native version:
0.61.5

FATAL EXCEPTION: create_react_context
    Process: com.xxx, PID: 31177
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/inject/Provider;
        at com.facebook.react.TurboReactPackage$1.iterator(TurboReactPackage.java:63)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:45)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.inject.Provider" on path: DexPathList[[zip file "/data/app/com.xxx-gAxA0yytGw1y7mJV1Dso1w==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx-gAxA0yytGw1y7mJV1Dso1w==/lib/arm, /data/app/com.xxx-gAxA0yytGw1y7mJV1Dso1w==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)

**Comment by safaiyeh** [comment]
Hi @alen252 thanks for the issue. For upgrade related issues, checkout https://github.com/react-native-community/upgrade-support.

Please leave an issue there!
