### ISSUE TITLE
Version 0.44.0 does not working

### ISSUE THREAD

**Issue by brimes** [facebook/react-native#13824]
When I updated to 0.44.0 my app broken.

The error is "Erro calling AppRegistry.runApplication"

And then when I update, get other error
"transform.forEach is not a function"

I created a new application and get de same problem.

When I go to the 0.43.4 version works fine.

**Comment by dobrienlzd** [comment]
print out the exact log please.  Erro  is clearly not a full reproduction of your error message.

**Comment by dobrienlzd** [comment]
also show the code for transform.forEach that is giving this error message.

**Comment by lanjie233** [comment]
@dobrienlzd 05-09 16:38:13.982 15873-15914/cn.miguche.shcs.internal E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                                          Process: cn.miguche.shcs.internal, PID: 15873
                                                                          java.lang.RuntimeException: Error calling AppRegistry.runApplication
                                                                              at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                              at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                              at android.os.Handler.handleCallback(Handler.java:739) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208) 
                                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/version-0440-does-not-working
