### ISSUE TITLE
Cannot find protocol declaration for 'NativeVibrationSpec'

### ISSUE THREAD

**Issue by MinaSamir11** [facebook/react-native#32404]
## Description
when running app on ios after upgrade to 0.66, I got these semantic error:
node_modules/react-native/Libraries/Vibration/RCTVibration.mm:16:28: Cannot find protocol declaration for 'NativeVibrationSpec'

node_modules/react-native/Libraries/Vibration/RCTVibration.mm:33:20: Use of undeclared identifier 'facebook'

## React Native version:
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 71.96 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.22.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. upgrade project to v0.66 and upgrade cocoa pods to 1.11.2 from m1 device, build succesfully
2. after that run project on my old MacBook pro, delete node_modules and podfile.lock and reinstall again dependencies.
3- Run project got build failed

## Expected Results
to build project successfully, after solving this error 👍 Cannot find protocol declaration for 'NativeVibrationSpec'
[
<img width="1280" alt="Screen Shot 2021-10-14 at 4 43 57 PM" src="https://user-images.githubusercontent.com/48614170/137340638-14a04974-f873-4b70-b3ab-2056c39895f8.png">
](url)

**Comment by userofgit001** [comment]
Whats the issue exactly?

Sent from my iPhone

On Oct 17, 2021, at 7:16 AM, Gabriel Moncea ***@***.***> wrote:

﻿
I have the same issue

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bachhuberdesign** [comment]
Also had this issue after upgrading from 0.64.2 -> 0.66.1. @gabrielmoncea's workaround did help

**Comment by xuanduyrn** [comment]
Same issue here

**Comment by Dovydastc** [comment]
Upgrading react-native to 0.61.3 fixed an issue for me!

**Comment by MinaSamir11** [comment]
for me issue resolved by updating to latest version react-native.

if issue still exist see this issue ticket solutions:
https://github.com/facebook/react-native/issues/32432
