### ISSUE TITLE
_reactNative.findNodeHandle is not a function

### ISSUE THREAD

**Issue by iggyfisk** [facebook/react-native#13688]
### Description

Importing `findNodeHandle` from `react-native` broke sometime in the last ~10 days. The function just isn't there anymore.

### Reproduction Steps and Sample Code

In a clean app from `react-native init`, import `findNodeHandle`:

```JavaScript
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  findNodeHandle
} from 'react-native';
```

And then call it:
```JavaScript
  componentDidMount() {
    findNodeHandle();
  }
```
This works fine in 0.43.4 (although the function call is rather pointless). On iOS with the latest master https://github.com/facebook/react-native#1a72d91cb29d24851bf8b8cf36e683740d3945d0 it redboxes, citing `(0, _reactNative.findNodeHandle) is not a function`. Probably Android as well but who even tests that platform.

### Additional Information

* React Native version: https://github.com/facebook/react-native#1a72d91cb29d24851bf8b8cf36e683740d3945d0
* Platform: Definitely iOS, most likely Android
* Development Operating System: macOS
* Dev tools: XCode 8.3.2

**Comment by iggyfisk** [comment]
Looks like @liuyunqiang possibly found the same bug but submitted a terrible issue https://github.com/facebook/react-native/issues/13637
