### ISSUE TITLE
[CI] Compilation of React-Native 0.8.0-rc.2 fails on CI services due to unknown selector for UIFont

### ISSUE THREAD

**Issue by Intellicode** [facebook/react-native#2074]
Since I've upgraded to 0.8.0-rc.2 I'm encountering the following errors while building the project with a build server:

```
/Users/distiller/xx/ios/node_modules/react-native/React/Base/RCTConvert.m:821:37: warning: undeclared selector 'systemFontOfSize:weight:' [-Wundeclared-selector]
    if ([UIFont respondsToSelector:@selector(systemFontOfSize:weight:)]) {
                                    ^
/Users/distiller/xx/ios/node_modules/react-native/React/Base/RCTConvert.m:822:22: error: no known class method for selector 'systemFontOfSize:weight:'
      font = [UIFont systemFontOfSize:fontSize weight:fontWeight];
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/distiller/xx/ios/node_modules/react-native/React/Base/RCTConvert.m:857:39: warning: undeclared selector 'systemFontOfSize:weight:' [-Wundeclared-selector]
      if ([UIFont respondsToSelector:@selector(systemFontOfSize:weight:)]) {
                                      ^
/Users/distiller/xx/ios/node_modules/react-native/React/Base/RCTConvert.m:858:24: error: no known class method for selector 'systemFontOfSize:weight:'
        font = [UIFont systemFontOfSize:fontSize weight:fontWeight];
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
```

Locally, it seems to build and run fine. I'm not sure what the solution should be here, but I guess there are a few options such as increasing the compilation target or fixing the build settings on my build server (I'm using CircleCI).

See also:
http://stackoverflow.com/questions/29345692/why-does-uifont-systemfontofsizeweight-not-crash-on-ios-8-0

**Comment by browniefed** [comment]
Are you capable of setting the version of xcode used? Based on documentation here https://circleci.com/docs/ios#software-versions it seems to have a compatible xcode version. I ran into this when upgrading to 0.8.0-rc and was running XCode 6.1and have since upgraded to 6.2 and no longer have these issues.

**Comment by Intellicode** [comment]
@browniefed that indeed seemed to be the problem. For Circle CI users, the following can be used to fix this issue:

```
machine:
  xcode:
    version: "6.3.1"
```

**Comment by rashthedude** [comment]
I'm having the same problem locally just trying to build it. It keeps on failing.

**Comment by browniefed** [comment]
@rashthedude same comment, make sure your XCode is up to date if you are getting this particular error.

**Comment by rashthedude** [comment]
@browniefed I'm in the midst of downloading and installing 6.3 but surely updates for react native shouldn't push the users to install the latest and greatest xcode which in many cases is not possible due Maverick or lower not supporting it.

**Comment by browniefed** [comment]
@rashthedude From my knowledge XCode is directly tied to certain IOS versions therefore yes you'll have to generally keep your XCode up to date to take advantage of react-native, and the latest IOS and IOS features.
I'm currently on Mavericks running 6.2 which is supported, however I do imagine in the future I'll need to upgrade to Yosemite and the most recent XCode.

**Comment by rashthedude** [comment]
@browniefed It does make sense having to be able to develop for the latest IOS needs a more refined Xcode. I hope Xcode 7 doesn't become a requirement anytime soon.
