### ISSUE TITLE
@babel/preset-typescript can not be found after upgrading React Native from 0.67.4 to 0.68.0

### ISSUE THREAD

**Issue by emclab** [facebook/react-native#33603]
### Description

After upgrading React Native from 0.67.4 to 0.68.0 on Big Sur, react-native run-android shows a red screen on android studio 2021.1.1 Patch 2 emulator after launch. And can not find @babel/preset-typescript. Remove and reinstall react-native-gesture-handler does not help.

```
error: node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: /Users/macair/Documents/code/js/xyz_app6/node_modules/react-native-gesture-handler/src/handlers/gestures/GestureDetector.tsx: Cannot find module '@babel/preset-typescript'
Require stack:
- /Users/macair/Documents/code/js/xyz_app6/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/@babel/core/lib/config/files/index.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/@babel/core/lib/index.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/metro-transform-worker/src/index.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/macair/Documents/code/js/xyz_app6/node_modules/jest-worker/build/workers/processChild.js
 BUNDLE  ./index.js 
```

### Version

0.68.0

### Output of `npx react-native info`

```
System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 24.36 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.0/13A5201i - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

use `npx react-native upgrade` to upgrade from 0.67.4 to 0.68.0. 

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2022-04-08 at 10 10 04 PM](https://user-images.githubusercontent.com/946013/162602074-c4263281-1560-4a41-acaf-7ca571d49d18.png)

Here is the part of `package.json`:

```
"dependencies": {
    "@ethersproject/shims": "^5.6.0",
    "@react-native-community/toolbar-android": "^0.2.1",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-native-picker/picker": "^2.4.0",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.1.1",
    "crypto-js": "^4.1.1",
    "ethers": "^5.6.1",
    "react": "17.0.2",
    "react-native": "0.68.0",
    "react-native-blob-util": "^0.14.1",
    "react-native-confirmation-code-field": "^7.3.0",
    "react-native-device-info": "^8.5.1",
    "react-native-easy-grid": "^0.2.2",
    "react-native-elements": "^3.4.2",
    "react-native-encrypted-storage": "^4.0.2",
    "react-native-flash-message": "^0.2.1",
    "react-native-gesture-handler": "^2.3.2",
    "react-native-get-random-values": "^1.7.2",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-image-picker": "^4.7.3",
    "react-native-loading-spinner-overlay": "^3.0.0",
    "react-native-modal": "^13.0.1",
    "react-native-reanimated": "^2.5.0",
    "react-native-redash": "^16.2.3",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.2.2",
    "react-native-screens": "^3.13.1",
    "react-native-vector-icons": "^9.1.0",
    "rn-alioss": "^0.2.5",
    "socket.io-client": "^4.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },

```
