### ISSUE TITLE
Android release build with proguard enabled throws exception at start

### ISSUE THREAD

**Issue by dgladkov** [facebook/react-native#6624]
I get following exception on my release APK with proguard enabled after upgrading RN to 0.22.+. Disabling proguard solves the issue.

```
java.lang.NoSuchMethodError: no non-static method "Lcom/facebook/react/bridge/queue/NativeRunnable;.<init>(Lcom/facebook/jni/HybridData;)V"
   at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
   at com.facebook.react.bridge.CatalystInstanceImpl.callFunction(CatalystInstanceImpl.java:189)
   at com.facebook.react.bridge.JavaScriptModuleRegistry$JavaScriptModuleInvocationHandler.invoke(JavaScriptModuleRegistry.java:97)
   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
   at $Proxy5.emit(Unknown Source)
   at com.facebook.react.modules.appstate.AppStateModule.sendAppStateChangeEvent(AppStateModule.java:73)
   at com.facebook.react.modules.appstate.AppStateModule.onHostResume(AppStateModule.java:51)
   at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:147)
   at com.facebook.react.ReactInstanceManagerImpl.moveToResumedLifecycleState(ReactInstanceManagerImpl.java:559)
   at com.facebook.react.ReactInstanceManagerImpl.moveReactContextToCurrentLifecycleState(ReactInstanceManagerImpl.java:904)
   at com.facebook.react.ReactInstanceManagerImpl.setupReactContext(ReactInstanceManagerImpl.java:728)
   at com.facebook.react.ReactInstanceManagerImpl.access$800(ReactInstanceManagerImpl.java:104)
   at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:210)
   at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:183)
   at android.os.AsyncTask.finish(AsyncTask.java:636)
   at android.os.AsyncTask.access$500(AsyncTask.java:177)
   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5254)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by charpeni** [comment]
@facebook-github-bot label android

**Comment by satya164** [comment]
Yeah, currently enabling proguard breaks the build. Would be great if someone could look into fixing this. cc @mkonicek

**Comment by dgladkov** [comment]
I tried manually adding both `com.facebook.react.bridge.queue.NativeRunnable` and `com.facebook.jni.HybridData` as proguard exceptions even though they are both annotated with `@DoNotStrip` but had no luck. Will investigate it more today

**Comment by satya164** [comment]
Thanks for looking into it. Much appreciated.

**Comment by dgladkov** [comment]
Found the problem. `NativeRunnable` has a private constuctor that must be annotated with `@DoNotStrip`. Will add a pull request now, temporary solution is to add following line to your app proguard rules
```
-keep class com.facebook.react.bridge.queue.NativeRunnable { *; }
```

**Comment by xiaobuu** [comment]
Finally found this issue. Saved my day.

**Comment by cpunion** [comment]
The problem is still exists. I created a project with `react-native init TestRN23`, so it installed `react-native@0.23.1`. Run `npm install` and add `@DoNotStrip` to `NativeRunnable.java`:

```
$ find . -iname NativeRunnable.java
./node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/queue/NativeRunnable.java
```

proguard-rules.pro was copied from master: https://gist.github.com/cpunion/f0712cae8ad552f9d49db86cc60ebeb4

```
$ cat `find . -iname NativeRunnable.java` | grep -B 3 -A 3 "private NativeRunnable"
  private final HybridData mHybridData;

  @DoNotStrip
  private NativeRunnable(HybridData hybridData) {
    mHybridData = hybridData;
  }
```
Then I added proguard, build and run release version, app crashed:
```
E/AndroidRuntime(10770): Process: com.testrn23, PID: 10770
E/AndroidRuntime(10770): java.lang.NoSuchMethodError: no method with name='<init>' signature='(Lcom/facebook/jni/HybridData;)V' in class Lcom/facebook/react/bridge/queue/NativeRunnable;
E/AndroidRuntime(10770): 	at com.facebook.react.bridge.ReactBridge.setGlobalVariable(Native Method)
E/AndroidRuntime(10770): 	at com.facebook.react.bridge.CatalystInstanceImpl.initializeBridge(CatalystInstanceImpl.java:127)
E/AndroidRuntime(10770): 	at com.facebook.react.bridge.CatalystInstanceImpl.access$200(CatalystInstanceImpl.java:39)
E/AndroidRuntime(10770): 	at com.facebook.react.bridge.CatalystInstanceImpl$1.call(CatalystInstanceImpl.java:96)
E/AndroidRuntime(10770): 	at com.facebook.react.bridge.CatalystInstanceImpl$1.call(CatalystInstanceImpl.java:91)
E/AndroidRuntime(10770): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:73)
E/AndroidRuntime(10770): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(10770): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10770): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime(10770): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(10770): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
E/AndroidRuntime(10770): 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by dgladkov** [comment]
@cpunion RN Android does not build from source code by default because it's quite slow and requires Android NDK installed in order to build JavaScriptCore. You need to either update to 0.24 RC or follow this guide to set up your gradle script to compile RN Android from source:
https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by dgladkov** [comment]
@cpunion of course much easier solution would be to add a line to your project proguard config that I mentioned here:
https://github.com/facebook/react-native/issues/6624#issuecomment-200840621

**Comment by cpunion** [comment]
@dgladkov Thanks so much, it works find.

**Comment by iegik** [comment]
http://stackoverflow.com/questions/42872700/proguard-app-crash-caused-by-java-lang-nosuchfielderror-no-lcom-facebook-jni

**Comment by iegik** [comment]
Add also
```
-keep class com.facebook.react.cxxbridge.ModuleRegistryHolder { *; }
```

**Comment by mkonicek** [comment]
Uh the Proguard config files are quite fragile. We have to keep adding stuff to them. Having a test on Circle CI that runs Proguard would help. Could anyone add that test?

Could you please send a pull request adding the lines to the default RN Proguard config, such as:

    -keep class com.facebook.react.cxxbridge.ModuleRegistryHolder { *; }

**Comment by iegik** [comment]
I`l do that
