### ISSUE TITLE
Cannot find module react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js

### ISSUE THREAD

**Issue by JB-CHAUVIN** [facebook/react-native#34248]
### New Version

0.64

### Old Version

0.69.2

### Build Target(s)

iOS iPhione 13 iOS 15.5

### Output of `react-native info`

System:
    OS: macOS 12.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 139.32 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
    Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 26, 30, 32
      Build Tools: 29.0.2, 29.0.3, 32.0.0, 32.1.0
      System Images: android-26 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: https://github.com/facebook/react-native#0.69-stable => 0.69.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Hello, after an upgrade I can't build anymore.

The XCODE error is : 
Error: Cannot find module 'XXX/node_modules/react-native/packages/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js'

The folder "node_modules/react-native/packages/react-native-codegen" exists, but it's not built.

When I build it manually with the following command, it's working : 
```
cd node_modules/react-native/packages/react-native-codegen
yarn build
```

**Comment by cortinico** [comment]
Are you building from source by any chance?

> cd node_modules/react-native/packages/react-native-codegen

You should not even have this folder at all.

> Error: Cannot find module 'XXX/node_modules/react-native/packages/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js'

What is happening is that some script is accessing the wrong path:

- node_modules/react-native/packages/react-native-codegen

instead of

- node_modules/react-native-codegen

Not sure what is going on but feels like a half-done version update?

**Comment by shwanton** [comment]
I had this issue on RNDesktop when upgrading from 0.64 -> 0.66
The `pod install` step should build this folder but for some reason it wasn't working, even after repeatedly deleting `Pods` and re-installing.

What eventually worked was nuking both `Pods` & `build` folder

```
cd packages/rn-tester
bundle exec pod deintegrate
rm -rf ./build
bundle exec pod install
```
