### ISSUE TITLE
Android: Fatal JNI exception in Yoga during launch

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#11705]
Here's the error message that crashes during app launch:

`JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/yoga/YogaNode;.jni_YGNodeStyleGetFlexBasis(J)F"`

It appears to have been introduced by 16359ec8eeb601f9e9e20a0cc01b6c4e46627d3a.

cc @woehrl01 @emilsjolander

**Comment by ericvicenti** [comment]
Is there a test that we could add that would catch problems like this? Seems like a pretty glaring issue that should be caught in CI

**Comment by rigdern** [comment]
Cleaning the build in Android Studio fixed the issue for me. People building React Native from source might hit this when upgrading React Native. Is there anything we can do to prevent people from ever hitting this?

**Comment by XepherJin** [comment]
I encountered this issue today when upgrading React Native to 0.41 and rebuild the project fixed it.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-fatal-jni-exception-in-yoga-during-launch
