### ISSUE TITLE
Upgrading jest from 25.5.4 to 26.1.0 gives missing "InitializeCore" error.

### ISSUE THREAD

**Issue by joshuapinter** [facebook/react-native#29516]
## Description
After upgrading `jest` and `babel-jest` from 25.5.4 to 26.1.0, I then get the following error message when running my `jest` tests: 

```
 FAIL  __tests__/Helpers.test.js
  ● Test suite failed to run

    Cannot find module 'InitializeCore' from 'node_modules/react-native/jest/setup.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
      at Object.<anonymous> (node_modules/react-native/jest/setup.js:3:15)
```

I'm on `react-native` version 0.59.10. 

## React Native version:
```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.15.5
      CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
      Memory: 84.27 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 15, 17, 22, 23, 25, 26, 27, 28, 29
        Build Tools: 26.0.0, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3
        System Images: android-15 | Google APIs Intel x86 Atom, android-17 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-macos-cli: 2.0.1
      react-native-unified-contacts: 2.0.0-pre.2
```

## Steps To Reproduce
1. Upgrade `jest` and `babel-jest` from 25.5.4 to 26.1.0. 

2. Run jest tests. 

## Expected Results
Tests run normally as they did prior to the upgrade.

## Snack, code example, screenshot, or link to a repository:
_n/a_

**Comment by joshuapinter** [comment]
As per @SimenB from [this Issue](https://github.com/facebook/jest/issues/10331#issuecomment-665117972), it [appears](https://github.com/facebook/jest/pull/8535#issuecomment-646525824) Jest 26 supports React Native 0.61+. 

I'll leave this open for some confirmation but it would also be nice to be able to find this version compatibility somewhere so others don't have to dig around for comments and end up wasting your guys' time with Issues, etc. :)
