### ISSUE TITLE
Error when upgrading to 0.39.0; process.stdin.setRawMode is not a function error

### ISSUE THREAD

**Issue by kenma9123** [facebook/react-native#11346]
### Description

So I was trying to upgrade my react-native library from `0.38.0` to `0.39.0`. I was expecting to prompt me about changes, replace and what not. But all I got is this kind of error and the CLI prompt just exit.

```
$ react-native upgrade
Upgrading project to react-native v0.39.0
Check out the release notes and breaking changes: https://github.com/facebook/react-native/releases/tag/v0.39.0
android\app\build.gradle has changed in the new version.
Do you want to keep your android\app\build.gradle or replace it with the latest version?
If you ever made any changes to this file, you'll probably want to keep it.
You can see the new version here: H:\Git\React-Native\AppTest\node_modules\react-native\local-cli\templates\HelloWorld\android\app\build.gradle
Do you want to replace android\app\build.gradle? Answer y to replace, n to keep your version:

process.stdin.setRawMode is not a function
```

### Additional Information

* React Native version: 0.38.0
* Platform: Android
* Operating System: Windows

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by jetpack3331** [comment]
@kenma9123 It happend me too.
I think its happen on MINGW64 terminal. I run that command in VScode (bash) and it was ok.
