### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_RCTPushNotificationManager"

### ISSUE THREAD

**Issue by sweetest** [facebook/react-native#5612]
mac osx 10.11.1
node.js 4.2.4
xcode 7.2
react 0.18-rc

+
target device: 6s plus, ios 9.2

I got this error when I tried to use PushNotificationIOS, following the tutorial document in official web page.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTPushNotificationManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by poyannabati** [comment]
Getting the same error on v0.19, was working on v0.18.1

**Comment by bartolkaruza** [comment]
@sweetest I had the same issue because I forgot to properly manually link the RCTPushNotification project. Following these steps resolved it; https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

@poyannabati Maybe you have to do it again after upgrading?

**Comment by nickmaxwell10** [comment]
@bartolkaruza You nailed it.  That solved the issue for me after upgrade to 0.23.
@poyannabati, did that do it for you too?

**Comment by ggharry** [comment]
`<select your project target>` -> `Build Phases` -> `Link Binary With Libraries` -> `Press +` -> `Make sure all libraries under "Workspace" have been added`

![screen shot 2016-05-07 at 12 26 52 am](https://cloud.githubusercontent.com/assets/1697380/15079330/72834278-13ea-11e6-816e-8755d47d403e.png)
