### ISSUE TITLE
[React native 0.68.1 + React 18] TypeError: dispatcher.useSyncExternalStore is not a function.

### ISSUE THREAD

**Issue by xiongemi** [facebook/react-native#33696]
### Description

Got `TypeError: dispatcher.useSyncExternalStore is not a function` error after upgrade React Native to 0.68.1 and React to 18.

If I just render the presentational component, it looks fine. As soon as I use the function connect from React-Redux, it throws an error.

Error:
```
TypeError: dispatcher.useSyncExternalStore is not a function. (In 'dispatcher.useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot)', 'dispatcher.useSyncExternalStore' is undefined)

This error is located at:
    in Connect(Search) (at App.tsx:42)
```
"react-redux": "8.0.1",
"redux-logger": "^3.0.6",
"@reduxjs/toolkit": "1.8.1",

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.90 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: 7.0.3 => 7.0.3 
    react: 18.0.0 => 18.0.0 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- I got a repo working fine with React 17 and React Native 67, after I did the upgrade, it throws the above error.

**Comment by TheRav3n** [comment]
Same here, solved by downgrading to React 17.0.2

**Comment by souna23** [comment]
Any updates pls I have the same issue, I want keep using react 18

**Comment by nucleartux** [comment]
stable react-native version is not supporting react 18 yet

**Comment by fortmarek** [comment]
> stable react-native version is not supporting react 18 yet

This is correct. Expect React 18 support in 0.69.

**Comment by xiongemi** [comment]
just a question: when would it be supported then?

**Comment by fortmarek** [comment]
Hey @xiongemi 👋 

We have [just released](https://github.com/facebook/react-native/releases/tag/v0.69.0-rc.0) the first release candidate for 0.69.0. You can find more details about the release in the discussion [here](https://github.com/reactwg/react-native-releases/discussions/21) where you can also provide us with any possible feedback 🙌

**Comment by BobDev1** [comment]
> Hey @xiongemi wave
> 
> We have [just released](https://github.com/facebook/react-native/releases/tag/v0.69.0-rc.0) the first release candidate for 0.69.0. You can find more details about the release in the discussion [here](https://github.com/reactwg/react-native-releases/discussions/21) where you can also provide us with any possible feedback raised_hands

@fortmarek Hello
It helped, thanks. But now during build process receiving new Invariant Violation errors (ViewPropTypes, AppRegistry and other modules are deprecated). Is there any solution for this one? @deprecated-react-native-prop-types package didn't helped. Thanks in advance :-)

**Comment by fortmarek** [comment]
Hey @BobDev1 - could you add the issue to the discussion [here](https://github.com/reactwg/react-native-releases/discussions/21) and give some more details about the project? (ideally, providing reproducible steps)

**Comment by cortinico** [comment]
> Hey @xiongemi 👋
> We have [just released](https://github.com/facebook/react-native/releases/tag/v0.69.0-rc.0) the first release candidate for 0.69.0. You can find more details about the release in the discussion [here](https://github.com/reactwg/react-native-releases/discussions/21) where you can also provide us with any possible feedback 🙌

To echo what @fortmarek said here: the first version with React 18 support will be 0.69.
More on this here:
- https://github.com/facebook/react-native-website/pull/3092

**Comment by kockok** [comment]
Why is the issue closed? I still got this error unless downgrading to react 17.0.2, does that mean we could only use react 18 only if react-native 0.69 is out?

**Comment by cortinico** [comment]
> does that mean we could only use react 18 only if react-native 0.69 is out?

Yes that's correct 👍 
You can read more on how React & React Native versions interact here:
https://github.com/facebook/react-native/blob/main/Libraries/Renderer/README.md
