### ISSUE TITLE
Module imports as an empty Object which results in TypeError: is not function in 0.14.2

### ISSUE THREAD

**Issue by agolovenko** [facebook/react-native#4254]
After upgrading from 0.13.1 to 0.14.2 some of module dependencies get resolved into empty objects. This results in TypeError when calling a method from imported module.

'use strict';
var API = require('./api');
var Settings = require('./settings');
var Storage = require('./storage');
...
API.loadTranslations()  // throws TypeError: API.loadTranslations is not a function(…)

So here for instance API is an empty Object and other modules are imported correctly. This behaviour changes form module to module and there seem to be no pattern so I can't provide an example or a snippet. There are of course a lot of circular dependencies and anonymous calls in the code but everything worked fine until this version upgrade.

**Comment by ide** [comment]
Eliminate your dependency cycles or write your modules in a way that is resilient to cycles. The empty object is the default value of the "exports" object. To clarify -- this is how JavaScript modules work, and React Native implements the spec / this issue isn't specific to RN.

**Comment by agolovenko** [comment]
Yeah, you were right. Sorry for bothering=)
