### ISSUE TITLE
OP-SQLite cannot build with 0.74RC and bridgeless

### ISSUE THREAD

**Issue by ospfranco** [facebook/react-native#43204]
### Description

Hi, I'm trying to test the library against the latest RC and also trying to get bridgeless to work. So far I'm facing two issues with the included example app in my library repo.

## iOS:

It seems the codegen script is expecting the src files to be in node_modules, but the builder-bob template links the dependency directly via `react-native.config.js`:

```ts
// react-native.config.js
const path = require('path');
const pak = require('../package.json');

module.exports = {
  dependencies: {
    [pak.name]: {
      root: path.join(__dirname, '..'),
    },
  },
};
```

And I get the following error when trying to install the pods:

<img src="https://github.com/facebook/react-native/assets/1634213/cfe54ff1-4d78-4428-b30a-9b438e196b77" width="400"/>

## Android

After turning on all the flags (and bumping the minSDK to 23) I get a compilation error but no output to what is wrong:

<img src="https://github.com/facebook/react-native/assets/1634213/06c09c60-ca63-4daa-b517-5343cf5e7cd4" width="400"/>

### Steps to reproduce

If you want to take a look yourself [here is the branch](https://github.com/OP-Engineering/op-sqlite/tree/bridgeless). Just install deps via `yarn` and then try to run the example app: `cd example && yarn android` or the equivalent iOS commands.

### React Native Version

0.74.0-rc.0

### Affected Platforms

Build - MacOS

### Areas

Bridgeless - The New Initialization Flow

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 2.49 GB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 4.0.2
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.0
    path: /Users/osp/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    Android NDK: 26.0.10792818
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/osp/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0-rc.0
    wanted: ^0.74.0-rc.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
```


### Stacktrace or Logs

```text
Pasted above
```

### Reproducer

https://github.com/OP-Engineering/op-sqlite/tree/bridgeless

**Comment by cipolleschi** [comment]
Hi @ospfranco, thanks for the issue.

For Android, we are aware that codegen and autolinking are not working with the RC.0 as we needed a commit that landed right after the branch cut. It should be solved in RC1

For iOS, @dmytrorykun, can you provide any insight? I remember that we had a similar report of `react-native.config.js` not being picked up by Codegen, but I remember we fixed that already. 🤔

**Comment by ospfranco** [comment]
For Android, I'm not sure this is the error I'm seeing? seems it doesn't like that I use the CallInvokerHolderImpl reference and it fails the compilation? How am I supposed to get a hold of the CallInvoker?

```kotlin
package com.op.sqlite

import com.facebook.react.bridge.ReactContext
import com.facebook.react.turbomodule.core.CallInvokerHolderImpl

class OPSQLiteBridge {
    private external fun installNativeJsi(
        jsContextNativePointer: Long,
        jsCallInvokerHolder: CallInvokerHolderImpl,
        docPath: String
    )

    private external fun clearStateNativeJsi()
    fun install(context: ReactContext) {
        val jsContextPointer = context.javaScriptContextHolder!!.get()
        val jsCallInvokerHolder =
            context.catalystInstance.jsCallInvokerHolder as CallInvokerHolderImpl
        // Trick to get the base database path
        val dbPath =
            context.getDatabasePath("defaultDatabase").absolutePath.replace("defaultDatabase", "")
        installNativeJsi(
            jsContextPointer,
            jsCallInvokerHolder,
            dbPath
        )
    }

    fun clearState() {
        clearStateNativeJsi()
    }

    companion object {
        val instance = OPSQLiteBridge()
    }
}
```

**Comment by cortinico** [comment]
> For Android, I'm not sure this is the error I'm seeing? seems it doesn't like that I use the CallInvokerHolderImpl reference and it fails the compilation? How am I supposed to get a hold of the CallInvoker?

You're seeing this error because you're using `CallInvokerHolderImpl` which is annotated as `FrameworksAPI`. This is a more advanced API that should be used only if you know what you're doing.

1. Can I ask you why do you need to access `CallInvokerHolderImpl`. 
2. What's your use case? 
3. What does the `installNativeJsi` method does?

For the time being, you can overcome this build failure by annotating your class with:

```kotlin
import com.facebook.react.common.annotations.FrameworkAPI

@OptIn(FrameworkAPI::class)
class OPSQLiteBridge {
  ...
}
```

**Comment by ospfranco** [comment]
The methods on op-sqlite run in a different thread, therefore to return the data to JS without crashing the JS context I need to schedule the callback. I have used this extensively on other client modules whenever there needs to be async work that does not block the JS thread, e.g. authentication/fingerprint callbacks.

**Comment by ospfranco** [comment]
After adding the annotation I'm getting the following exception when trying to access the callinvokerholderimpl:

```
2024-02-28 08:24:19.849  2370-2475  OPSQLite                com.op.sqlite.example                E  Install exception: java.lang.UnsupportedOperationException: There is no Catalyst instance in bridgeless mode.
```

**Comment by ospfranco** [comment]
Trying iOS again, and added a console.log on the paths being expanded, indeed it seems it looks in node_modules and then in a prepended path

<img src="https://github.com/facebook/react-native/assets/1634213/ae8f312d-729e-4d23-b7be-922afd6ed59e" width="400" /> 

I guess this is correct on a normal installation but on a library setup where the dependency is not explicitly declared on the package.json but instead linked via `react-native.config.js` and via tsconfig paths... it will never find the source

**Comment by dmytrorykun** [comment]
@ospfranco sorry, I forgot to post an update here. iOS has been fixed https://github.com/facebook/react-native/pull/43210
The fix will be available in the next RC.

**Comment by ospfranco** [comment]
Thanks in the mean time I will patch it

**Comment by dmytrorykun** [comment]
@ospfranco `pod install`?

**Comment by ospfranco** [comment]
Tried a nuke of pods and caches and still getting the same error. 

Getting this error because of importing the RCTBridge+Private header apparently? But without it I don't have access to the runtime and callInvoker types.

<img src="https://github.com/facebook/react-native/assets/1634213/0b9b1023-f899-4810-82e7-803d6bb0ab7c" width="400"/>
<img src="https://github.com/facebook/react-native/assets/1634213/eb270224-8963-4fca-b4cb-3eba81da8c38" width="400" />

**Comment by philIip** [comment]
> After adding the annotation I'm getting the following exception when trying to [access the callinvokerholderimpl](https://github.com/OP-Engineering/op-sqlite/blob/bridgeless/android/src/main/java/com/op/sqlite/OPSQLiteBridge.kt#L18):
> 
> ```
> 2024-02-28 08:24:19.849  2370-2475  OPSQLite                com.op.sqlite.example                E  Install exception: java.lang.UnsupportedOperationException: There is no Catalyst instance in bridgeless mode.
> ```
> 
> What would be the correct way to access the callinvoker on bridgeless?

hi!!! for android, in new architecture, we will be recommending to use RuntimeExecutor:

https://github.com/facebook/react-native/blob/c3b0a8f1626939cf5c7b3864a5acf9d3dad26fb3/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L219

it should be a simple drop in replacement and it is forward compatible so it will work in bridge as well

**Comment by philIip** [comment]
> Tried a nuke of pods and caches and still getting the same error.
> 
> Getting this error because of importing the RCTBridge+Private header apparently? But without it I don't have access to the runtime and callInvoker types.
> 
> <img alt="" width="400" src="https://private-user-images.githubusercontent.com/1634213/308601214-0b9b1023-f899-4810-82e7-803d6bb0ab7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzYwOTEsIm5iZiI6MTcwOTEzNTc5MSwicGF0aCI6Ii8xNjM0MjEzLzMwODYwMTIxNC0wYjliMTAyMy1mODk5LTQ4MTAtODJlNy04MDNkNmJiMGFiN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMTU1NjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQyMTMyNTUyMjQ2MDc5ZDNlZDU0NzdlMjEzNTkwMDk1YzJlODUwNTM2OGM2MDU1MDdiZjY2MDI3ODkwNGViMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QbSzgP52PzoLBAQKUJo3CIc15sXLBf1fylNRbbueN0w"> <img alt="" width="400" src="https://private-user-images.githubusercontent.com/1634213/308602542-eb270224-8963-4fca-b4cb-3eba81da8c38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzYwOTEsIm5iZiI6MTcwOTEzNTc5MSwicGF0aCI6Ii8xNjM0MjEzLzMwODYwMjU0Mi1lYjI3MDIyNC04OTYzLTRmY2EtYjRjYi0zZWJhODFkYThjMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMTU1NjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZhYmYwYjVmY2Q3OGFiODc2ZGVkZjc2MjlhMWU2MDJhMTQyY2ZkMDY1NGMzNmJhOGJlYmE1NWU0MzIwMDU3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8ivevN1bAy5cvAQruvHi20nDmFOlOLv4Ug6-ZLPOzc8">
> Edit: ah right bridgeless... so what's the correct way to get access to the jsiRuntime?

for iOS, accessing the raw runtime should be backwards compatible. this build issue seems like something else. dmitry is currently looking at it

**Comment by ospfranco** [comment]
@philIip is there a RuntimeExecutor for iOS as well? this is a shared module between iOS and Android, setting up conditional compilation with two different classes will be really painful.

**Comment by ospfranco** [comment]
- where am I supposed to access the Runtime executor from? It would be massively helpful to get snippets for all this stuff, since I'm not familiar with the internal classes.
- I meant that if the callinvoker is only available on ios but not on android then my shared C++ code doesn't work

**Comment by philIip** [comment]
hi @ospfranco, i have posted https://github.com/reactwg/react-native-new-architecture/discussions/160! please let me know if any of these options do not fit with your use case

**Comment by ospfranco** [comment]
ok, that helps a bit, but it seems the runtimeExecutor is platform-dependent? At least from my quick reading through that discussion it seems to take a obj-c closure. My modules are a shared C++ codebase, which means I have shared calls that use the jsCallInvoker.

Here is an example of a JSI Host Function doing work in another C++ thread, then scheduling work via the call invoker to return data to JS.

https://github.com/OP-Engineering/op-sqlite/blob/main/cpp/bindings.cpp#L318

It is also not clear to me at all how to keep compatibility with the old modules as it seems I will either need a lot of conditional compilation to receive the correct objects.

**Comment by philIip** [comment]
got it!!! thanks for the code pointer! i think in this case, we want to eventually use a C++ TurboModule, but currently we don't have support for cross platform support for an iOS native module to embed a C++ TurboModule for example

as you saw in the post, we build the runtime pointer into the backwards compat layers but not the call invoker. i think that this helps inform that we probably should build the call invoker into those layers as well. we will prioritize that from our end, it's currently in flight!

**Comment by ospfranco** [comment]
I already gave my feedback in the original discussion. A C++ turbo module doesn't quite work for some use cases since, I not only need C++ but sometimes I also need access to functions or variables that are only available to native apis (database folder location, get secure bytes via keychain/hardware chip, etc.). So, I think it is still valuable to be able to access all the C++ entities from a native module so pure JSI bindings can be created. Thanks for taking the time to take a look though, and all the help!

**Comment by philIip** [comment]
> I already gave my feedback in the original discussion. A C++ turbo module doesn't quite work for some use cases since, I not only need C++ but sometimes I also need access to functions or variables that are only available to native apis (database folder location, get secure bytes via keychain/hardware chip, etc.). So, I think it is still valuable to be able to access all the C++ entities from a native module so pure JSI bindings can be created. Thanks for taking the time to take a look though, and all the help!

got it! let me move this discussion over there.

**Comment by ospfranco** [comment]
What do you mean with DI? 

The JNI way is pain in the ass to work with. Mapping and binding functions via funny strings and conversion between java classes and native C++ is cumbersome, but to get to the point, yeah, basically like that.

At least for my use case that's all I need. Another thing was the C++ module initialization. I haven't checked since the original bridgless announcement, but it was cumbersome, requiring user changes. I think callstack manager to migrate some of their libraries and also patch them in a way that requires no user changes to appdelegate but this is not documented anywhere.

**Comment by cortinico** [comment]
What's the status of this issue @ospfranco ? Is there anything we need to pick in an upcoming RC of 0.74?

**Comment by ospfranco** [comment]
I still haven't received any info on how to solve the issues. Basically still at square 0.

# iOS

I need more exact snippets on how to retrieve the call invoker for iOS (or in its absence the runtimeExecutor, which I didn't find any way to retrieve it from existing exposed classes)

https://github.com/facebook/react-native/issues/43204#issuecomment-1972586329

The problem with the runtime executor is that then my Android and iOS codebases will diverge. So I need to use one or the other.

# Android

I still did not manage to get a hold of the call invoker from the Bridgeless Android module.

https://github.com/facebook/react-native/issues/43204#issuecomment-1968380955

**Comment by arushikesarwani94** [comment]
For Android https://github.com/facebook/react-native/pull/43400 should fix accessing the JSCallInvoker in Bridgeless.

**Comment by philIip** [comment]
sorry for the delay! was out sick last week

this should be resolved when https://github.com/facebook/react-native/pull/43400 and https://github.com/facebook/react-native/pull/43314 get picked into 0.74!

**Comment by arushikesarwani94** [comment]
> For Android [#43400](https://github.com/facebook/react-native/pull/43400) should fix accessing the JSCallInvoker in Bridgeless.

https://github.com/facebook/react-native/pull/43424 as well to fix failing test.

**Comment by ospfranco** [comment]
Hey, I have a little bit of free time. What is the status of those patches? Are they merged, can I test a new version of 0.74 this weekend?

**Comment by cortinico** [comment]
> Hey, I have a little bit of free time. What is the status of those patches? Are they merged, can I test a new version of 0.74 this weekend?

We'll be doing RC4 with those 4 patches on Monday 👍

**Comment by ospfranco** [comment]
I just tried rc.4 and getting the following problems.

on iOS I get the following casting error:
![Oscar Franco Screen 001207](https://github.com/facebook/react-native/assets/1634213/a5c36694-dfcf-4010-80ec-652902a72123)

On Android it now compiles but it crashes on runtime when I try call the getInvoker method
![Oscar Franco Screen 001208](https://github.com/facebook/react-native/assets/1634213/55a38afb-2ce6-4c2c-89e9-337c77bad395)

Any suggestions?

**Comment by philIip** [comment]
@ospfranco, i have https://github.com/facebook/react-native/pull/43600 to help unblock iOS. can you try patching it and let me know what happens? i tried pushing a PR against your repo but got blocked by lefthook lol

**Comment by arushikesarwani94** [comment]
For Android, I couldn't repro due to gradle issues but from cursory look the crash is happening since the newly added catalyst instance for [Bridgeless](https://github.com/facebook/react-native/blob/15a5638c621cbec4a9fcb5ae94938120cdc32fae/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt#L165) is returning the interface `CallInvokerHolder` versus what [OPSQLiteBridge](https://github.com/OP-Engineering/op-sqlite/blob/b083c021adb3f634b282687fe9d5e07e3207d259/android/src/main/java/com/op/sqlite/OPSQLiteBridge.kt#L17) expects is an implementing class of this interface i.e. `CallInvokerHolderImpl`  which is why the cast is failing. 

Also, since `CallInvokerHolderImpl` is a `FrameworksAPI`: This API is provided only for React Native frameworks and not intended for general users, we recommend directly using the interface. LMK if this works.

**Comment by ospfranco** [comment]
@philIip thanks, I will give it a try when I can, this weekend.

@arushikesarwani94 you mean just casting to CallInvokerHolder? I will give it a try thanks

**Comment by ospfranco** [comment]
Just tried running it without the cast to Impl and I get this error.

![Oscar Franco Screen 001266](https://github.com/facebook/react-native/assets/1634213/9ec694bc-6b8f-41ca-b0c3-47d700acc229)

Would it be possible for you guys to run this yourselves? The branch is there and you don't need to do anything except a yarn install and then run:

https://github.com/OP-Engineering/op-sqlite/tree/bridgeless

**Comment by ospfranco** [comment]
@philIip I just tried to patch with your changes and I'm getting this error(s):

![Oscar Franco Screen 001305](https://github.com/facebook/react-native/assets/1634213/b7b99b1c-8361-461b-ad86-20e630da24c2)

I think my changes are correct, so don't know why am I getting that missing header error
![Oscar Franco Screen 001306](https://github.com/facebook/react-native/assets/1634213/33d6128b-1cca-4c96-9a89-e60b8efafe25)
![Oscar Franco Screen 001307](https://github.com/facebook/react-native/assets/1634213/204c823c-9d73-4f45-a1fa-e89926678063)

I changed both node_modules in the example project and parent folder

**Comment by arushikesarwani94** [comment]
@ospfranco I was able to repro the insta crash of OPSQLiteExample app locally just not with the same error as yours and rather as a SEG Fault as discussed in chat.
<img width="1496" alt="Screenshot 2024-03-25 at 5 25 17 PM" src="https://github.com/facebook/react-native/assets/76862293/7c629e9b-b2d6-4f1c-ab07-dde85278c9d0">

Both the `BridgelessCatalystInstance` & `CallInvokerHolder` are getting retrieved correctly upon debugging without needing any cast.

I was able to get past the app crash by updating the [cpp-adapter.cpp](https://github.com/OP-Engineering/op-sqlite/blob/bridgeless/android/cpp-adapter.cpp) to exactly the one on [main](https://github.com/OP-Engineering/op-sqlite/blob/main/android/cpp-adapter.cpp)
<img width="1072" alt="Screenshot 2024-03-26 at 4 09 07 PM" src="https://github.com/facebook/react-native/assets/76862293/859e28fc-5eb8-4e1d-9c88-b0e4c390beea">


Since you mentioned the change was not necessary for bridgeless as long as both the runtime and the invoker are there is all good, I think this should unblock you.

**Comment by ospfranco** [comment]
Thanks for the help @arushikesarwani94! The app is now building correctly! 🎉

Waiting for instructions regarding iOS

**Comment by philIip** [comment]
> Thanks for the help @arushikesarwani94! The app is now building correctly! 🎉
> 
> Waiting for instructions regarding iOS

@ospfranco, can you patch https://github.com/facebook/react-native/pull/43600? that should resolve your build error.

**Comment by ospfranco** [comment]
The screenshot I posted with the import error is after patching the changes of #43600. Let me try it again, maybe I did something wrong.

**Comment by ospfranco** [comment]
I re-applied the same changes again and I'm getting this:

![Oscar Franco Screen 001322](https://github.com/facebook/react-native/assets/1634213/d6866b5e-dc2d-4340-b4a0-f992e2e0f711)

**Comment by ospfranco** [comment]
I tried again, this time I created the patch using patch-package, you can see it here:

https://github.com/OP-Engineering/op-sqlite/pull/60/files#diff-b5757661684d7172a2bb6e4ced36e58fed8300e282b867167bf5ae03158f7191

Now getting this error:

![Oscar Franco Screen 001323](https://github.com/facebook/react-native/assets/1634213/e83fec3d-d6f4-4095-bb2c-8d7bd903c923)

**Comment by ospfranco** [comment]
I tried generating a patch-package with the changes but it failed to apply. Maybe some of these files are created on the install step? In any case, manually applying the changes to `node_modules/react-native` doesn't seem to work for me

Here is the patch file in case you want to check if I did it correctly:

https://github.com/OP-Engineering/op-sqlite/pull/60/files#diff-0c24a4c1e88df14537749bb451dbc3164819872c11700d39fa16f1abe54b1fdc

**Comment by philIip** [comment]
can you show me the stack trace that's pulling in RCTBridge+Inspector? you should be able to find it in the builds tab here, which should open the build logs:

<img width="237" alt="image" src="https://github.com/facebook/react-native/assets/5687023/e5d2758d-f464-4996-bd46-41339faaea07">

**Comment by ospfranco** [comment]
This is all I can find:

![CleanShot 2024-03-28 at 18 22 29@2x](https://github.com/facebook/react-native/assets/1634213/b7090e66-ce4f-4477-82f1-b660983afef2)

**Comment by philIip** [comment]
oooo got it, seems like a classic merge conflict lol.... PageTarget got renamed to HostTarget after 0.74 cut. i have to push a change directly to 0.74 that renames HostTarget back to PageTarget in RCTBridge (Inspector) :P

**Comment by ospfranco** [comment]
It seems now the error on node modules is gone, but still getting missing property when casting to CxxBridge

![CleanShot 2024-03-29 at 06 31 15@2x](https://github.com/facebook/react-native/assets/1634213/456d3c48-4cd7-4584-807e-914e0d360af9)

**Comment by philIip** [comment]
do you have the new architecture flag turned on? IIRC in your code you have the import to RCTBridge+Private gated by a compiler flag. you can remove that.

**Comment by ospfranco** [comment]
You are absolutely right, sorry, hard to keep track as I'm busy with paid work. Uncommenting it fixes it in the old arch, but I'm getting a undefined module on the new arch. Checking it now.

![CleanShot 2024-03-29 at 18 45 46@2x](https://github.com/facebook/react-native/assets/1634213/ed52faee-b269-4022-9d53-cdccd83679d0)

**Comment by ospfranco** [comment]
No type error, but on runtime the cxxbridge is not there

![CleanShot 2024-03-29 at 18 48 50@2x](https://github.com/facebook/react-native/assets/1634213/36dec292-57ea-411a-9a3b-c037fea9db26)

**Comment by philIip** [comment]
> You are absolutely right, sorry, hard to keep track as I'm busy with paid work. Uncommenting it fixes it in the old arch, but I'm getting a undefined module on the new arch. Checking it now.

no need to apologize! just figuring out one thing at a time

> No type error, but on runtime the cxxbridge is not there

cool i was just able to repro! :D let me get back to you!

<img width="425" alt="image" src="https://github.com/facebook/react-native/assets/5687023/153d1bbb-85f0-4282-b9b7-a36a45132f82">

**Comment by RSNara** [comment]
@ospfranco, I can explain why the cxxBridge is nil here!

Here's the goal: When people migrate to our stable apis (for turbomodules and fabric at least), we want them to cut ties with the backwards compatibility layers (i.e: this bridge proxy). That way, people only have to migrate once for the new architecture (i.e: when they adopt the stable apis). And after most people migrate migrate, as the framework authors, we can just sunset the backwards compatibility layers.

The solution here would be this: just undo the turbomodule migration work you did for this module that accesses the bridge. That way, it'll just become a legacy module going through the interop layer, and it'll have access to the bridge. Once we figure out the stable api for give modules access to the runtime (likely c++ turbomodule), you'll just have to re-write this completely. I hope that's fine!

**Comment by ospfranco** [comment]
I will give it a try, but this is not a normal turbo module. I just need to access the runtime so I can later bind c++ functions directly

**Comment by ospfranco** [comment]
@RSNara i also have to say: i won't migrate this module to c++ turbo module, because I need access to native apis, in this case getting the library folder path and on Android getting the databases path.

Same with other libraries I have, sometimes I call native apis from c++

Would this still work with the approach you suggested?

**Comment by huntie** [comment]
We've picked the requested change (https://github.com/reactwg/react-native-releases/issues/183) into the `0.74-stable` branch this morning. It will be part of 0.74 RC6, due out later today.

**Comment by ospfranco** [comment]
@philIip ok, I got it, it is cumbersome and I'm short on time, but I will try to get it soon a report how it goes. Thanks!

**Comment by ospfranco** [comment]
Ok, reverting to an old module works in all archs. Will close for now, and I guess we can have a discussion when old modules will be completely retired. Like I said, I don't really care about having to migrate to a C++ Turbo Module, as long as I get to call the native functions that's all I need.
