### ISSUE TITLE
TypeError: responder.scrollResponderScrollTo is not a function

### ISSUE THREAD

**Issue by harshmdr-devslane** [facebook/react-native#35567]
### Description

Hi,
I'm getting this error while run on ios ("React Native 0.68.2" and "native base:2.15.2")

TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({
x: x,
y: y,
animated: animated
})', 'responder.scrollResponderScrollTo' is undefined)

### Version

0.68.2

### Output of `npx react-native info`

TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({
x: x,
y: y,
animated: animated
})', 'responder.scrollResponderScrollTo' is undefined)

### Steps to reproduce

After upgrading react-native to 0.68.2

### Snack, code example, screenshot, or link to a repository

https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/519

**Comment by nibbles83** [comment]
Also seeing the same issue.

RN 67.4
native-base 2.15.2
react-native-keyboard-aware-scroll-view 0.9.5

This seems to fix it https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/519#issuecomment-1339468136
