### ISSUE TITLE
Can't make an iOS build [0.65.0]

### ISSUE THREAD

**Issue by realtril** [facebook/react-native#32046]
## Description
This is what i have in my `Podfile`
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.2'

target 'Test' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end


  pod 'React-Core', :path => '../node_modules/react-native'

end
```

## React Native version:
```
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 2.99 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.65.0 => 0.65.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
 pod update/pod install/pod install --repo-update

##Problem that i am facing
<img width="1014" alt="Screen Shot 2021-08-19 at 11 59 30 AM" src="https://user-images.githubusercontent.com/53015418/130042376-369050c2-a189-4f82-9dc8-a156cd8068f4.png">

## Expected Results
App should build without any issues.

**Comment by octsiri** [comment]
Have you try to delete the `Podfile.lock` and generate it again by `pod install`?

**Comment by realtril** [comment]
> Have you try to delete the `Podfile.lock` and generate it again by `pod install`?

Yes, of course

**Comment by luism3861** [comment]
> Have you try to delete the `Podfile.lock` and generate it again by `pod install`?

You've never delete Podfile.lock,

**Comment by realtril** [comment]
@smartameer have slightly updated Podfile due to your comment and deployment_target I receive
but now i have this problem while building

`Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')`

**Comment by YaoHuiJi** [comment]
> @smartameer have slightly updated Podfile due to your comment and deployment_target I receive
> but now i have this problem while building
> 
> `Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')`
> 
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> ```
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> IOS_VERSION = '11.0'
> 
> platform :ios, '11.0'
> 
> target 'test' do
>   config = use_native_modules!
> 
>   use_react_native!(
>     :path => config[:reactNativePath],
>     # to enable hermes on iOS, change `false` to `true` and then install pods
>     :hermes_enabled => false
>   )
> 
>    # Enables Flipper.
>   #
>   # Note that if you have use_frameworks! enabled, Flipper will not work and
>   # you should disable these next few lines.
>   use_flipper!({ 'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7',  'Flipper-RSocket' => '1.4.3' })
> 
> 
>   post_install do |installer|
>     react_native_post_install(installer)
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
>       end
>     end
> 
>   end
> 
> end
> ```

just the same  build error  after I upgrade RN from 0.64.0 to 0.65.0, changing deployment target of RCT-Folly does not work, only show this error

> Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')

**Comment by john-dufrene-dev** [comment]
Same error with fresh 0.65 version and xcode 12.5, RCT-FOLLY problem as mentionned before, impossible to build for release

**Comment by mikehardy** [comment]
Changing iPHONEOS_DEPLOYMENT_TARGET is an anti-pattern at this point.
Stop changing that build setting. Remove that part from your post-install.

**Comment by daveslutzkin** [comment]
@realtril @YaoHuiJi @john-dufrene-dev fix for me was described here:

https://github.com/facebook/flipper/issues/834#issuecomment-900550142

Basically you need to make sure that the deployment target for `RCT-Folly` stays at 9.0, but the comments there describe it better than me.

**Comment by daveslutzkin** [comment]
@mikehardy I think we started changing `iPHONEOS_DEPLOYMENT_TARGET` because otherwise we get warnings from Xcode. Have the warnings gone away or are they just bogus?

**Comment by john-dufrene-dev** [comment]
@daveslutzkin thanks for your answer, could you explain how to change that, I'm new with react native, thanks in advance

**Comment by realtril** [comment]
> @realtril @YaoHuiJi @john-dufrene-dev fix for me was as described here:
> 
> [facebook/flipper#834 (comment)](https://github.com/facebook/flipper/issues/834#issuecomment-900550142)
> 
> Basically you need to make sure that the deployment target for `RCT-Folly` stays at 9.0, but the comments there describe it better than me.

should i do something like that?

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '11.0'

target 'test' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  use_flipper!({ 'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7',  'Flipper-RSocket' => '1.4.3' })

  post_install do |installer|
    react_native_post_install(installer)
    case target.name
    when 'RCT-Folly'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end

  end

end
```

**Comment by mikehardy** [comment]
The warnings are still there, they are not bogus, but neither are they important.
The warnings are saying "hey, your iOS minimum for your apps is higher than your libraries"
Does that matter? Not at all.
Is it noisy? Yes.
Ask me how I know: I had this post_install, to quiet the noise, it was nice. But then the build started breaking like this, so I removed the post_install change, the build works, my logs are noisy again.

Build working >> noise :shrug:

**Comment by mikehardy** [comment]
My take on it now is: if it's possible that some libraries have version dependent behavior, and I was just trying to quiet noise but they actually depend on their build settings not changing, do I *really* know more than all the library authors? I do not. I should probably leave their build settings alone.

**Comment by john-dufrene-dev** [comment]
This is my change as mentionned on previous comment :

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'default' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'defaultTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7',  'Flipper-RSocket' => '1.4.3' })

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|  
      case target.name
      when 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end
end

```


With debug mode it's working, but when trying to build for release I have this error, if someone have an idea how to resolve that, I'm on a clean react-native project with xcode 12.5

<img width="1007" alt="Capture d’écran 2021-08-19 à 23 28 06" src="https://user-images.githubusercontent.com/25297943/130146680-91013577-fe67-4bf4-9c41-c39fa63988e5.png">

**Comment by daveslutzkin** [comment]
@john-dufrene-dev
> @daveslutzkin thanks for your answer, could you explain how to change that, I'm new with react native, thanks in advance

If your Podfile has a section that says something like this:
```
post_install do |installer|
  react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

Then either:

* Remove the section:
```
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
```

Or make it:
```
post_install do |installer|
  react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
  case target.name
    when 'RCT-Folly'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
```

**Comment by YaoHuiJi** [comment]
thanks, but no luck for me too, I changed the Podfile but got another error as @john-dufrene-dev mentioned above
`Thread-local storage is not supported for the current target`
I have checked the IPHONEOS_DEPLOYMENT_TARGET of "RCT_Folly" in xcode, it's 9.0

also I have a warning when I run "pod install"
[!] FBReactNativeSpec has added 1 script phase. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.
I just ignore it, don't know if it's the reason I got the error `Thread-local storage is not supported for the current target`

**Comment by mikehardy** [comment]
If you just do `npx react-native init TestProject && cd TestProject && yarn ios` it works, right?

Don't worry about the cocoapods warning about adding FBReactNativeSpec, that's *normal*. That's cocoapods warning you that a script was added, in case you have security concerns with the script.

In this case, it's a necessary part of react-native iOS compiling, so it's good to be aware (thanks Cocoapods!) but it's not a problem.

**Comment by luism3861** [comment]
> If you just do `npx react-native init TestProject && cd TestProject && yarn ios` it works, right?
> 
> 
> 
> Don't worry about the cocoapods warning about adding FBReactNativeSpec, that's *normal*. That's cocoapods warning you that a script was added, in case you have security concerns with the script.
> 
> 
> 
> In this case, it's a necessary part of react-native iOS compiling, so it's good to be aware (thanks Cocoapods!) but it's not a problem.

I always disabled flipper because has a lot of issues when you create a new project mostly version cocoa pods etc etc it is a good idea?

**Comment by mikehardy** [comment]
I think it used to be. I did the same. Now it appears that chunks of it are integral to the react-native build for iOS. I no longer think it can easily be avoided.

**Comment by smartameer** [comment]
@realtril this helped me,
After tweaking post_install it built successfully. I have commented some code, enable and try out if that works for you. For me enabling or disabling has the same affect.

```
post_install do |installer|
  react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
    # if target.name == "React"
    #   target.remove_from_project
    # end
    # target.build_configurations.each do |config|
    #   config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    # end
    if (target.name&.eql?('FBReactNativeSpec'))
      target.build_phases.each do |build_phase|
        if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
          target.build_phases.move(build_phase, 0)
        end
      end
    end
  end
end
```

**Comment by luism3861** [comment]
![image](https://user-images.githubusercontent.com/36824170/130260033-883b4322-dbec-4e7e-83e3-8d1a6da58756.png)
delete flipper in `Podfile` file, delete `Pods` and then install again `pod install` clean your Xcode and run again your app

**Comment by luism3861** [comment]
> ![image](https://user-images.githubusercontent.com/36824170/130260853-b8ca5bda-6f72-45dd-8f8e-7ffdc36ed2af.png)
> 
> delete flipper in `Podfile` file, delete `Pods` and then install again `pod install`, clean your Xcode and run again your app

**Comment by Noitham** [comment]
In my case, the issue still exists even though removing flipper

**Comment by mikehardy** [comment]
Parts of flipper are still included now no matter what in react-native 0.65 especially if you want hermes on ios.

Here's my full set of hacks.

```ruby
  post_install do |installer|
    react_native_post_install(installer)

    # Apple Silicon builds require a library path tweak for Swift library discovery or "symbol not found" for swift things
    installer.aggregate_targets.each do |aggregate_target| 
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
    end

     # Flipper requires a crude patch to bump up iOS deployment target, or "error: thread-local storage is not supported for the current target"
    # I'm not aware of any other way to fix this one other than bumping iOS deployment target to match react-native (iOS 11 now)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end
    end

    # ...but if you bump iOS deployment target, Flipper barfs again "Time.h:52:17: error: typedef redefinition with different types"
    # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
    # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
    `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
  end
```

**Comment by ryanSN** [comment]
This is what I had to do to get it all to work with Xcode 13, React Native 0.65.0 Also did a upgrade from 0.61.2
Commented out `use_flipper!()` but still got the `RCT-Folly` error, this allows the app to build and go on a ios 15 sim.

```ruby
post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        case target.name
        when 'RCT-Folly'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end

      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
  ```

**Comment by YaoHuiJi** [comment]
I tried 0.66 today,  now everything works even with default Podfile, you do not need those changes mentioned in this issue and you can enable Flipper too. a big thanks to all developers💗

**Comment by mikehardy** [comment]
@fkgozali this is closable

**Comment by fkgozali** [comment]
closing since we have addressed this in the latest release

**Comment by YaoHuiJi** [comment]
@realtril here is my Podfile, I replaced the target name to 'xxx', no other changes. I use realm-js, so I have to disable hermes.

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'xxx' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  target 'xxxTests' do
    inherit! :complete
    # Pods for testing
  end

   # Enables Flipper.
   #
   # Note that if you have use_frameworks! enabled, Flipper will not work and
   # you should disable these next few lines.
   #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
   use_flipper!()

   post_install do |installer|
     react_native_post_install(installer)
     __apply_Xcode_12_5_M1_post_install_workaround(installer)
   end
end
```

**Comment by realtril** [comment]
@YaoHuiJi thank you!
