### ISSUE TITLE
f.generateNewAnimationTag is undefined

### ISSUE THREAD

**Issue by Djakninn** [facebook/react-native#11323]
### Description

After upgrading to RN 0.38 from 0.34 my app crashes whenever something on the screen needs to be animated, from scrolling to changing the view(the first interaction crashes the app, pretty much). I get the following error: Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: f.generateNewAnimationTag is not a function.'

* React Native version: 0.34
* Platform: iOS
* Operating System: macOS

**Comment by Djakninn** [comment]
![screen shot 2016-12-06 at 11 35 36](https://cloud.githubusercontent.com/assets/22096006/20924195/33edd6b6-bba8-11e6-98e4-4cc229ab46fc.png)
^This is the stack trace

**Comment by Djakninn** [comment]
Fixed it, my problem was that I was overwriting the Animated component in my npm postinstall script.
