### ISSUE TITLE
[0.60.4] iOS Build is failing on empty project due to glog compilation error

### ISSUE THREAD

**Issue by gaykov** [facebook/react-native#25820]
It's impossible to build the newly created project with RN v0.60.4.

I'd like to mention that everything works fine with older versions, 0.59.10 in particular (I've tried the same steps I described below, but with `react-native init AwesomeProject --version 0.59.10` command).

I understand that this error is coming from `glog`, not from React Native, and might be related to the system configuration or something similar, but I think it's related because it's happening even in newly created projects.

React Native version:
```
System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 1.00 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

I experienced the issue while upgrading to RN 0.60, but it also fails an empty project. I simply followed the `Getting Started` guide and did:

1. `react-native init AwesomeProject`
2. `cd AwesomeProject`
3. `react-native run-ios`

And then build fails with the following message:

```
....

CompileC /path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/x86_64/signalhandler.o /path/projects/AwesomeProject/ios/Pods/glog/src/signalhandler.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target: glog)
    cd /path/projects/AwesomeProject/ios/Pods
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++14 -stdlib=libc++ -fmodules -fmodules-cache-path=/path/projects/AwesomeProject/ios/build/AwesomeProject/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/path/projects/AwesomeProject/ios/build/AwesomeProject/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mios-simulator-version-min=9.0 -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /path/projects/AwesomeProject/ios/build/AwesomeProject/Index/DataStore -I/path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/glog/include -I/path/projects/AwesomeProject/ios/Pods/Headers/Private -I/path/projects/AwesomeProject/ios/Pods/Headers/Private/glog -I/path/projects/AwesomeProject/ios/Pods/Headers/Public -I/path/projects/AwesomeProject/ios/Pods/Headers/Public/glog -I/path/projects/AwesomeProject/ios/Pods/glog/src -I/path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources-normal/x86_64 -I/path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources/x86_64 -I/path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/DerivedSources -F/path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/glog -Wno-shorten-64-to-32 -include /path/projects/AwesomeProject/ios/Pods/Target\ Support\ Files/glog/glog-prefix.pch -MMD -MT dependencies -MF /path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/x86_64/signalhandler.d --serialize-diagnostics /path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/x86_64/signalhandler.dia -c /path/projects/AwesomeProject/ios/Pods/glog/src/signalhandler.cc -o /path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/x86_64/signalhandler.o
In file included from /path/projects/AwesomeProject/ios/Pods/glog/src/signalhandler.cc:34:
In file included from /path/projects/AwesomeProject/ios/Pods/glog/src/utilities.h:73:
/path/projects/AwesomeProject/ios/Pods/glog/src/base/mutex.h:147:3: error: Need to implement mutex.h for your architecture, or #define NO_THREADS
# error Need to implement mutex.h for your architecture, or #define NO_THREADS
  ^
/path/projects/AwesomeProject/ios/Pods/glog/src/base/mutex.h:188:3: error: unknown type name 'MutexType'
  MutexType mutex_;
  ^
2


** BUILD FAILED **


The following build commands failed:
	CompileC /path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/x86_64/symbolize.o /path/projects/AwesomeProject/ios/Pods/glog/src/symbolize.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /path/projects/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/glog.build/Objects-normal/x86_64/vlog_is_on.o /path/projects/AwesomeProject/ios/Pods/glog/src/vlog_is_on.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

This error is coming from the following place in glog's code: https://github.com/google/glog/blob/master/src/base/mutex.h#L147, but can't get why it's happening.

**Comment by cristiankmb** [comment]
@gaykov Do you found any solutions for this? I have the same problem 😔

**Comment by gaykov** [comment]
@cristiankmb can you please share the result of running `react-native info` in your project's folder?

**Comment by cristiankmb** [comment]
@gaykov Sure:
System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 64.95 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by vishnuindrabalan** [comment]
Any solution for this?

**Comment by cristiankmb** [comment]
@vishnuindrabalan I was try run with react-native@0.59.10, isn't the best alternative but worked fine.

**Comment by cristiankmb** [comment]
Solution:
-Install Cocoa Pods
sudo gem install cocoapods
-In your Project Folder:
cd ios
pod install

**Comment by slavikdenis** [comment]
@cristiankmb this actually works. Don't you think as well, that this should be a part of the https://facebook.github.io/react-native/docs/getting-started.html as well ? Thank you for the solution.

**Comment by gaykov** [comment]
Pod installation is a part of initial project generation phase. If you run `react-native init AwesomeProject` it installs pods after generating initial structure.

@slavikdenis I see that you tagged a lot of issues, but looks like the errors are completely different, non of them are related to `glog` as described in this issue.

But I've tried installing pods manually after creating a new project, still no luck with glog compilation.

**Comment by vishnutechjini** [comment]
Solved this by removing my pod file and did 'pod install' again

**Comment by vishnuindrabalan** [comment]
Solved this by deleting pod file and generated again using 'pod install'

**Comment by slavikdenis** [comment]
@gaykov I didnt had the `glog` problem, but the ones I tagged before. Somehow, @cristiankmb 's solution solved them as well.

**Comment by cristiankmb** [comment]
@gaykov Maybe can do you another step that i done:
-Update Xcode
-Remove /Users/{your-user}/Library/Developer/Xcode/DerivedData
```
brew upgrade node
brew upgrade watchman
brew tap AdoptOpenJDK/openjdk
brew cask upgrade adoptopenjdk8
```
On your project
```
sudo gem install cocoapods
```
And finally on your /ios
```
pod install
```

I hope that can be useful. 👍🏾

**Comment by Cyphexl** [comment]
@gaykov If you ran `init` on a Windows device, and then switched to a Mac to debug on iOS, in this case the `pod install` phase is still required to do manually.

Also, every time after cloning a repo for build. Maybe it's still worth noting, at lease along with `npm i`?
