### ISSUE TITLE
Use of undeclared identifier 'SafeAreaViewProps'

### ISSUE THREAD

**Issue by sahildeliwala** [facebook/react-native#47927]
### Description

Getting below two errors after upgrading from 0.72.0 to 0.76.0
 - /node_modules/react-native/ReactCommon/react/renderer/components/safeareaview/SafeAreaViewShadowNode.h:24:42 Use of undeclared identifier 'SafeAreaViewProps'.
 - Unknown type name 'ConcreteViewShadowNode'.

### Steps to reproduce

After upgrading app, run `yarn ios` or build app from XCode.

### React Native Version

0.76.0

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.7
  CPU: (10) arm64 Apple M1 Pro
  Memory: 131.03 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.11.0
    path: ~/.nvm/versions/node/v22.11.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v22.11.0/bin/yarn
  npm:
    version: 10.9.0
    path: ~/.nvm/versions/node/v22.11.0/bin/npm
  Watchman:
    version: 2024.11.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/real/.rvm/gems/ruby-3.1.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/real/.rvm/rubies/ruby-3.1.2/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 14.1.1
    wanted: ^14.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.0
    wanted: 0.76.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
app/node_modules/react-native/ReactCommon/react/renderer/components/safeareaview/SafeAreaViewShadowNode.h:24:42 Use of 
undeclared identifier 'SafeAreaViewProps'

app/node_modules/react-native/ReactCommon/react/renderer/components/safeareaview/SafeAreaViewShadowNode.h:27:9 Unknown type name 'ConcreteViewShadowNode'; did you mean 'SafeAreaViewShadowNode'?
```

### Reproducer

n/a

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/ffcba005-25c4-49bf-93dd-150c5dead002)

**Comment by arhoads76** [comment]
I also see this error, and am using react-native 0.76.3.

**Comment by cipolleschi** [comment]
can you try to:
- remove node_modules
- run `bundle exec pod deintegrate`
- rerun `bundle exec pod install`
- try to build again?

Jumping from 0.72 to 0.76 is a huge jump, there are several changes that happened in the codegen, so my guess is that you have some stale artifacts/code that have not been regenerated properly.

**Comment by vivek25constants** [comment]
> can you try to:
> 
> - remove node_modules
> 
> - run `bundle exec pod deintegrate`
> 
> - rerun `bundle exec pod install`
> 
> - try to build again?
> 
> 
> 
> Jumping from 0.72 to 0.76 is a huge jump, there are several changes that happened in the codegen, so my guess is that you have some stale artifacts/code that have not been regenerated properly.

Already did this and still getting same error.

**Comment by cipolleschi** [comment]
Can you provide a valid reproducer for this?

**Comment by christianchen8** [comment]
having the same issue, is there any solution to this?

**Comment by cipolleschi** [comment]
Guys, commenting with same issues will not help here, sadly.


I need a reproducer to be able to investigate what's going on. Otherwise, the only thing I can say is to run the instructions I shared [here](https://github.com/facebook/react-native/issues/47927#issuecomment-2512275242).

Have a look also at any patches you might have, as suggested by @vtaxs [here](https://github.com/facebook/react-native/issues/47927#issuecomment-2541042380).

As soon as we have a reproducer, I'll spend some time on it, understanding what's happening.

**Comment by tamlyn** [comment]
For me, deleting `node_modules` didn't fix it, but blitzing all the caches with `npx react-native-clean-project` did. YMMV.

**Comment by trizerr** [comment]
I am on 0.72.5
For me this issue happened when I enabled fabric in podfile. Removing it fixed the issue
