### ISSUE TITLE
[FIXED in 0.71.6, 0.70.8, 0.69.9] Xcode 14.3 (14E222b) Build Failed with React Native 0.71.5

### ISSUE THREAD

**Issue by bahadiraraz** [facebook/react-native#36739]
### Description

```
The following build commands failed:
        CompileC /Users/bahadiraraz/Library/Developer/Xcode/DerivedData/mozzarellaui-gbkyyusquvgpyncsiuxkvfpzwcsu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-Codegen.build/Objects-normal/arm64/FBReactNativeSpec-generated.o /Users/bahadiraraz/WebstormProjects/mozzarella/mozzarellaui/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods')
(1 failure)
```
I encountered the same error in Xcode Version 14.3 (14E222b) released yesterday.

- "react-native": "0.71.5"

When I tried @travis-mark's solution issue #36635, it didn't work either. I also tried using 'M1' and other options instead of 'RC', but it still didn't work. 

### React Native Version

0.71.5

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 74.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.6.1 - /usr/local/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.5 => 0.71.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

 npx react-native init Project
 npx react-native run-ios      

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/48323786/229117383-72ac417a-4672-4a60-a01b-21a06f43251f.png)

**Comment by GennadiyVSG** [comment]
I have the same issue

**Comment by cortinico** [comment]
cc @cipolleschi

**Comment by shensven** [comment]
+1

**Comment by bahadiraraz** [comment]
> @bahadiraraz can you post your current project or Podfile? It's possible since ruby inside Xcode offers little assistance that you're missing a piece of the [patch](https://github.com/travis-mark/lrn/commit/015854716feadd61a904d5a603b027426472f863).
```Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'mozzarel' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'mozzarelTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

**Comment by travis-mark** [comment]
@bahadiraraz The patch is not present. Am I missing something?

**Comment by bahadiraraz** [comment]
no, this patch has not been added,because I get the same error if it is added

**Comment by Tapmeet** [comment]
ANy progress on this?

**Comment by coofzilla** [comment]
The [patch](https://github.com/travis-mark/lrn/commit/015854716feadd61a904d5a603b027426472f863)  that Travis posted worked for me. I copied and pasted the changes directly into my Podfile, then ran `pod install` from the `ios` directory.

Can anyone explain why this issue is happening? 🤔

**Comment by rajesh-vishwa** [comment]
The following build commands failed:
        CompileC /Users/apple/Library/Developer/Xcode/DerivedData/mobileApp-fczllhwjaxnfricexizepfgaveji/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-Codegen.build/Objects-normal/x86_64/FBReactNativeSpec-generated.o /Users/apple/Documents/book-my-ground/mobileApp/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods')
(1 failure)
]

**Comment by nilavassg** [comment]
+1 facing the same issue.

**Comment by omargera96** [comment]
Facing the same issue

**Comment by astrahov** [comment]
https://github.com/facebook/react-native/issues/36635

**Comment by cipolleschi** [comment]
Minimum fix coming soon, hopefully next week, but can't promise anything: https://github.com/facebook/react-native/pull/36759

**Comment by blakef** [comment]
Just to add to @cipolleschi, fixes should be picked for these versions:
- [0.69.9](https://github.com/reactwg/react-native-releases/discussions/55#discussioncomment-5496401)
- [0.70.8](https://github.com/reactwg/react-native-releases/discussions/56#discussioncomment-5496400)
- [0.71.6](https://github.com/reactwg/react-native-releases/discussions/60#discussioncomment-5496399)
- [0.72-RC1](https://github.com/reactwg/react-native-releases/discussions/54#discussioncomment-5496396).

**Comment by LukeIKG** [comment]
Same problem. anyone got it running? also after xcode update i cant run my app in xcode directly (error: /Users/User/Project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2063:46 'value' is unavailable: introduced in iOS 12.0). My deployment target is above 12.0 and it worked before the update. any ideas?

**Comment by slvssb** [comment]
> Same problem. anyone got it running? also after xcode update i cant run my app in xcode directly (error: /Users/User/Project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2063:46 'value' is unavailable: introduced in iOS 12.0). My deployment target is above 12.0 and it worked before the update. any ideas?

+1 Facing same with eas build

**Comment by cipolleschi** [comment]
> Minimum fix coming soon, hopefully next week, but can't promise anything: https://github.com/facebook/react-native/pull/36759

A fix is coming, we hope to be able to release patched versions next week.

Meanwhile, you can use the "patch" suggested [here](https://github.com/travis-mark/lrn/commit/015854716feadd61a904d5a603b027426472f863)

 Or use Xcode 14.2 tool chain with Xcode 14.3

**Comment by kelset** [comment]
👋 everyone!

We have just now finished rolling out new patch releases for the versions in the [release support window](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) to address this Xcode 14.3 problem 🎉

Check them out:
* https://github.com/facebook/react-native/releases/tag/v0.71.6
* https://github.com/facebook/react-native/releases/tag/v0.70.8
* https://github.com/facebook/react-native/releases/tag/v0.69.9

We'll close but unlock the issue now so that you can let us know if you still have issues - we are aware that there is a different problem going on for some users that needs to be fixed at the cocoapods level (https://github.com/facebook/react-native/issues/36762), so please be mindful in posting comments here that are not relevant to this specific problem.

**Comment by eifr-vault** [comment]
not sure if related to here but after upgrade to 0.71.6 im getting `error: Unable to load contents of file list: '/Target Support Files/Pods-Vault/Pods-Vault-frameworks-Debug-output-files.xcfilelist' (in target 'Vault' from project 'Vault')`

**Comment by alroniks** [comment]
I've done as described [here](https://github.com/facebook/react-native/issues/36690#issuecomment-1493765601) and it solved my issue

**Comment by blakef** [comment]
@joseAlvarezTenpo we aren't providing patches for [unsupported version](https://github.com/react-native-community/discussions-and-proposals/blob/ab17b2a366938e56d70278ced6e3f8d93fc666c5/proposals/0503-rn-versions-lifecycle-support.md#which-versions-are-currently-supported) of React Native.  Upgrade if you're able to or look at the change in the commit and apply it to your project.

**Comment by iRetray** [comment]
Same here! 😡

**Comment by angelozdev** [comment]
Facing the same issue. Do you know if this issue will be solved in lower versions, for example version 0.67?

**Comment by oniangel12933** [comment]
Please try following:
step 1:  sudo arch -x86_64 gem install ffi
step 2:  arch -x86_64 pod install

**Comment by muhammad-irfan-tkxel** [comment]
My React Native version is 0.67.4 and I'm facing the same issue. Can anybody hlep?

**Comment by talentedman** [comment]
> My React Native version is 0.67.4 and I'm facing the same issue. Can anybody hlep?

upgrade rn version 0.71.6  or use Xcode 14.2  or use Xcode 14.2 tool chain with Xcode 14.3

**Comment by igortice** [comment]
> > My React Native version is 0.67.4 and I'm facing the same issue. Can anybody hlep?
> 
> upgrade rn version 0.71.6 or use Xcode 14.2 or use Xcode 14.2 tool chain with Xcode 14.3

right, i download the 14.2 version, and i changed it in the 14.3 version, but now the error is another one, :(

![image](https://user-images.githubusercontent.com/1306646/230898374-198a9662-a0a2-48b6-a981-c3950a4259d6.png)

**Comment by jeisonng** [comment]
> > > My React Native version is 0.67.4 and I'm facing the same issue. Can anybody hlep?
> > 
> > 
> > upgrade rn version 0.71.6 or use Xcode 14.2 or use Xcode 14.2 tool chain with Xcode 14.3
> 
> right, i download the 14.2 version, and i changed it in the 14.3 version, but now the error is another one, :(
> 
> ![image](https://user-images.githubusercontent.com/1306646/230898374-198a9662-a0a2-48b6-a981-c3950a4259d6.png)

Try remove folder Pods and Podfile.lock.
Go to node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp and apply that change https://github.com/facebook/react-native/commit/52d8a797e7a6be3fa472f323ceca4814a28ef596
Run pod install againd and run project

Worked for me

**Comment by igortice** [comment]
> > > > My React Native version is 0.67.4 and I'm facing the same issue. Can anybody hlep?
> > > 
> > > 
> > > upgrade rn version 0.71.6 or use Xcode 14.2 or use Xcode 14.2 tool chain with Xcode 14.3
> > 
> > 
> > right, i download the 14.2 version, and i changed it in the 14.3 version, but now the error is another one, :(
> > ![image](https://user-images.githubusercontent.com/1306646/230898374-198a9662-a0a2-48b6-a981-c3950a4259d6.png)
> 
> Try remove folder Pods and Podfile.lock. Go to node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp and apply that change [52d8a79](https://github.com/facebook/react-native/commit/52d8a797e7a6be3fa472f323ceca4814a28ef596) Run pod install againd and run project
> 
> Worked for me

thanks friend for the help, but nothing yet, still unable to run

![SCR-20230410-hoe](https://user-images.githubusercontent.com/1306646/230937932-e8d80501-8878-449a-942d-aa855512343c.png)

**Comment by cipolleschi** [comment]
Hi @igortice! IIUC,  you are using React Native version 0.65, which is not supported anymore.

I strongly suggest you to update to a more recent version as it is likely that your error has been fixed there.

In any case, I also suggest you to try and open the luigi_jobs.xcworkspace in Xcode and try to build from there.

The attached screenshots are not useful as xcodebuild can fail with error 65 for many different reasons and it's nearly impossible help you properly without knowing what's going on.

Also, if you can provide a project that presents the same problems, with the minimum amount of code, this could help us pinpointing the problem.

**Comment by BrianAutomatize** [comment]
oddly changed version 
"dependencies": {
"react-native": "0.71.6"
}
and 
Podfile
platform :ios, '13' or platform :ios, '12.4'

still cannot launch 
"ios": "react-native run-ios",  from terminal
or launch from Xcode without seeing

error: 'value' is unavailable: introduced in iOS 12.0 d[@"prerelease"] = prerelease.has_value() ? @((double)prerelease.value()) : nil;
The following build commands failed:
        CompileC ... 0.compiler (in target 'React-Codegen' from project 'Pods')
(1 failure)
and in Xcode same thing
/mobile/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2063:46 'value' is unavailable: introduced in iOS 12.0

Have i missed something?

**Comment by cipolleschi** [comment]
@BrianAutomatize after updating react native to 0.71.6, you also have to:
- `yarn install`
- `bundle exec pod install`
To install the new dependencies.

Then, `yarn ios` (the equivalent of `npx react-native run-ios`) should work.

Another check you can do is to, make sure that the `React-Codegen` target in the Pods project in Xcode has iOS 12.4 as `iOS Deployment Target`:
<img width="1468" alt="Screenshot 2023-04-14 at 09 44 59" src="https://user-images.githubusercontent.com/11162307/231978725-73b9bc76-9acb-4373-83fc-8ff852c73aac.png">

**Comment by rohitgupta1996** [comment]
Issue is there for version 0.69.3 also

**Comment by cipolleschi** [comment]
@rohitgupta1996 the latest patch for 0.69 is [0.69.9](https://github.com/facebook/react-native/releases/tag/v0.69.9). I suggest you to update to that patch version, which should solve the issue.

**Comment by igortice** [comment]
i changed for 0.69.9 but now i have new problem
![image](https://user-images.githubusercontent.com/1306646/232560232-4c283a80-3bb8-4bb6-8c35-1a9a2775daed.png)

**Comment by smiley717** [comment]
![image](https://github.com/facebook/react-native/assets/80674675/7a0e296f-ada7-4cf3-a7af-d6b78f685dbd)


When I am trying to build for ios, I get this error.

`
System:
    OS: macOS 13.3.1
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 823.06 MB / 31.63 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

**Comment by cipolleschi** [comment]
Hi @smiley717, thanks for the question. There is no error specified in the Screenshot you took. It just says that it fails and where but not why.

I think you can search for `"error:"` in the log to understand what is the actual issue. 

As soon as you have it, you can post it again so I can try to help you here.

**Comment by smiley717** [comment]
```
                      ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2067:88: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"windowPhysicalPixels"] = windowPhysicalPixels.has_value() ? windowPhysicalPixels.value().buildUnsafeRawValue() : nil;
                                                                                       ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2069:88: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"screenPhysicalPixels"] = screenPhysicalPixels.has_value() ? screenPhysicalPixels.value().buildUnsafeRawValue() : nil;
                                                                                       ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2080:96: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"isIPhoneX_deprecated"] = isIPhoneX_deprecated.has_value() ? @((BOOL)isIPhoneX_deprecated.value()) : nil;
                                                                                               ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2288:68: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"prerelease"] = prerelease.has_value() ? @((double)prerelease.value()) : nil;
                                                                   ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2414:110: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"DEFAULT_BACKGROUND_COLOR"] = DEFAULT_BACKGROUND_COLOR.has_value() ? @((double)DEFAULT_BACKGROUND_COLOR.value()) : nil;
                                                                                                             ^
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /Users/user/Desktop/Work/synkbooks_app_v1/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
7 errors generated.

```
Hi @cipolleschi  Thank you for catching up my post and there are too long logs to copy, but try to find errors ( others are warning). 

it was working on the previous Mac 12, and just stop working with Mac13.4. so I was thinking of ruby-version

**Comment by cipolleschi** [comment]
Oh, I see. Actually, we already fixed that bug (introduced by Xcode) in 0.71.8. Just update your project to the last version of your minor and it will work!

**Comment by smiley717** [comment]
@cipolleschi  Sounds great! I will update my project to 0.71.8 (I am using 0.71.4 right now) :)

**Comment by toscalivia83** [comment]
I had the same error with react native 0.72.0
Works fine with 0.71.7

**Comment by cipolleschi** [comment]
Hi @toscalivia83, sorry to hear that. But are you sure?
The fix is in 0.72-stable: https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/scripts/cocoapods/codegen_utils.rb#L116

could you perhaps clean caches and retry reinstalling the pods?

**Comment by toscalivia83** [comment]
I did that twice and ran `rm -rf ~/Library/Developer/Xcode/DerivedData/* && rm -rf ~/Library/Caches/org.swift.swiftpm`
but the error remains the same

However I'm struggling to create the bundle on Android, I posted a question [here](https://stackoverflow.com/questions/76539368/failed-to-transform-react-native-0-71-0-rc-0-release-aar-com-facebook-reactrea) and this is the reason why I tried upgrading
If it all works on 0.72.0 at some point I'll let you know
And if you or anyone you know can help me fix this issue ^ that would be awesome, thanks!

**Comment by RikRah** [comment]
Could you check if this is set up properly?

1. Click on the Pods project on the left
2. Click on the React-Codegen target (could also have the icon of a temple 🏛️, doesn't matter)
3. Click on Build settings on top
4. filter for `ios deployment` 
5. What value is reported?

<img width="1511" alt="Screenshot 2023-06-23 at 12 29 22" src="https://github.com/facebook/react-native/assets/5502124/f63a7288-cce0-47ab-9593-c27259f0062b">

**Comment by cipolleschi** [comment]
Could you check if this is set up properly?

1. Click on the Pods project on the left
2. Click on the React-Codegen target (could also have the icon of a temple 🏛️, doesn't matter)
3. Click on Build settings on top
4. filter for ios deployment
5. What value is reported?

<img width="1480" alt="Screenshot 2023-06-23 at 12 31 47" src="https://github.com/facebook/react-native/assets/11162307/aeef5725-a01e-469f-a2bc-9a21e495e453">

**Comment by toscalivia83** [comment]
Hello, this is the ios deployment target I had specified: (ios 13.0)
<img width="1003" alt="Screenshot 2023-06-25 at 23 33 47" src="https://github.com/facebook/react-native/assets/19326704/b51864e5-2b5a-49f9-b4d9-4c2526b7844e">

It works on Android with react native version 0.72.0 now and I can create the bundle properly.
However it still does not work on iOS emulator or on my real device (I have an iPhone 7 on version 15.7.6). Even if I change this value you asked me to look at to iOS 12.4 as you did
Any other idea?

**Comment by toscalivia83** [comment]
It does not seem to complain about Codegen though
<img width="1109" alt="Screenshot 2023-06-26 at 00 01 49" src="https://github.com/facebook/react-native/assets/19326704/6ccbdee9-a395-4f92-beed-4cf97becfb09">

**Comment by toscalivia83** [comment]
Thanks for your reply @cipolleschi 
I've created an issue [here](https://stackoverflow.com/questions/76555672/error-reactcommon-turbomodulebinding-h-file-not-found-on-react-native-0-72-0-o) for this bug

**Comment by kenchoong** [comment]
you need to make sure your folder name is not having space 
folder name: 
code project ❌
code-project ✅

**Comment by jeffngugi** [comment]
I had to downgrade to 14.2 since I am running some other old project 0.66  and had so many issues. Upgrading to 14.3 once I update my RN projects

**Comment by MAgungHKM** [comment]
just need to make sure, is this fixed in `0.72.4`?

**Comment by Vasault** [comment]
unbelievable this issue still persist, i'm at 0.74 right now, and it came up out of nowhere

**Comment by mishalbutt114** [comment]
facing the same issue from past three days and unable to resolve
