### ISSUE TITLE
"index.js: Transformer.transform is not a function"

### ISSUE THREAD

**Issue by popdorin** [facebook/react-native#29301]
## Description
After upgrading react-native from 0.48.3 to 0.62.2 I get the error when running "react-native run-ios" command: "index.js: Transformer.transform is not a function". 
<img width="378" alt="Screenshot 2020-07-08 at 12 43 31" src="https://user-images.githubusercontent.com/22213775/86916871-e866e280-c12c-11ea-936d-74077b1b3d59.png">

## React Native version:
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 75.33 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by SudoPlz** [comment]
@popdorin  Why was this closed? Did you figure out the solution?

I'm experiencing the same issue.

Thanks

**Comment by popdorin** [comment]
@SudoPlz I'm not sure why this was closed but I didn't find the solution yet. I used the upgrade helper but I still get the same error.

**Comment by rgreen33** [comment]
I'm getting this same error on a new install (new MacBook Pro).  Did anyone find a solution?

**Comment by abouquet** [comment]
Same there ... Using upgrade helper to align versions, and still doesn't work

**Comment by rgreen33** [comment]
@abouquet I was finally able to get around the errors (after a lot of digging and searching).  As I mentioned, my issue started when I attempted to set my app up on a new laptop...which had the latest install of React Native (0.63).  Here are the steps that got me back up and running (once I made it past the transformer error, I started getting a swift error, so the steps below include the fix for that too):

1.  Pulled a fresh copy of my code from our on-prim GitHub server.
2.  Ran the following command to install my node modules:  npm install
3.  Ran the following command to install pods:  npx pod-install (from ios folder)
4.  Ran the following command on my project:  npx react-native upgrade
5.  Checked for outdated modules by running the following:  npm outdated
6.  Modified package.json file to update outdated modules and then ran:  npm install
7.  Once everything was updated, I deleted the node_modules folder and re-ran npm install to get a fresh install of all current modules.

Now, I turned my attention to the pod files
8.  With React Native 0.63, I created a new AwesomeProject app...so that I could get a copy of the new Podfile format.
9.  I deleted Podfile.lock file and entire Pods folder.
10.  I replaced my Podfile with the new formatted file from my newly created AwesomeProject app...replacing the app name throughout the file.
11.  Once the new Podfile was in place, I ran the following:  nix pod-install.

Now, this is where I started getting the swift linking errors.  You can read more about the details here (https://stackoverflow.com/questions/50096025/it-gives-errors-when-using-swift-static-library-with-objective-c-project/56187043#56187043).  To get around this, I had to do the following:
12.  Per the URL, I had to add an empty Swift file and let Xcode "Create Bridging Header".

I continued to get errors for my "tests", so I had to make one additional change.
13.  In Podfile, I added the following under my target 'projectTests":  inherit! :search_paths

The above steps worked for me.  Good luck!

**Comment by abouquet** [comment]
thanks @rgreen33  for your detailed explanation !

I will try theses steps asap.

**Comment by kmocorro** [comment]
Having similar issue on Windows.

**Comment by automatensalat** [comment]
For us this was caused by a version mismatch of the `metro-config` package. If you depend on this in your app to override some default metro configuration you should make sure it's the same version `react-native` depends on. 
In our case we upgraded to `react-native@0.63.2` and also upgraded `metro-config` to `0.61`, although `react-native` depended on `0.58`. This caused the metro version used by the react-native CLI to try to load a transformer module from a path that does not exist for `0.58`, returning `undefined` from the `require` call, leading to the error in question.

You can check which versions are required and installed by running `npm ls metro-config` or searching the `package-lock.json` file.

**Comment by answer-huang** [comment]
> For us this was caused by a version mismatch of the `metro-config` package. If you depend on this in your app to override some default metro configuration you should make sure it's the same version `react-native` depends on.
> In our case we upgraded to `react-native@0.63.2` and also upgraded `metro-config` to `0.61`, although `react-native` depended on `0.58`. This caused the metro version used by the react-native CLI to try to load a transformer module from a path that does not exist for `0.58`, returning `undefined` from the `require` call, leading to the error in question.
> 
> You can check which versions are required and installed by running `npm ls metro-config` or searching the `package-lock.json` file.

this save my life !

**Comment by jcczmetal** [comment]
Hey, I had the same issue. Here is my solution:

- If you are running npx react-native start, just stop it.
- Run npm outdated
- Updated in package.json the Wanted versions. Her is my configuration: ```"devDependencies": { "@babel/core": "^7.11.1", "@babel/runtime": "^7.11.2", "@react-native-community/eslint-config": "^1.1.0", "babel-jest": "^25.5.1", "eslint": "^6.8.0", "jest": "^25.5.4", "metro": "^0.61.0", "metro-core": "^0.61.0", "metro-react-native-babel-preset": "^0.59.0", "react-test-renderer": "16.13.1"   }```
- Then delete the node_modudes folder
- Run npm install
- Run npx react-native start
- Run npx react-native run-ios in new terminal.

**Comment by mrousavy** [comment]
I'm still experiencing this problem. No clean or install helped!

**Comment by acomia** [comment]
del %appdata%\Temp\react-native-* & cd android & gradlew clean & cd .. & del node_modules/ & npm cache clean --force & npm install & npm start -- --reset-cache

try to run this on your cmd.

It work for me.

**Comment by vjpr** [comment]
For an explanation of the issue see here: https://github.com/facebook/metro/issues/617

**Comment by MrCreeper1008** [comment]
I wasn't having this issue. Switched to pnpm and it happened. Tried to switch back and it's still happening. Cleaned everything I could and reinstalled modules, but the error still happens. Really frustrating.

**Comment by vjpr** [comment]
@MrCreeper1008 See https://github.com/pnpm/pnpm/issues/3010. There is a working repo using pnpm there.

**Comment by MrCreeper1008** [comment]
Thanks, I'll check it out.

**Comment by gabrielsaviank** [comment]
@answer-huang 
Oi mate. you talked a lot about the bug but didn't told us how to solve it. But I figured out: 
First I ran `npm ls metro-config`
Well I downgraded ` "metro-react-native-babel-preset": "0.59.0",` to  "metro-react-native-babel-preset": "0.58.0" in package.json.
Then I ran `npm install`
After that `pod install`
Then `npx react-native run-ios`
This worked for me.

**Comment by Kenny4444** [comment]
I am seeing this on android ... any one have any ideas on how to solve that? I tried updating all my packages.

Deps:
"dependencies": {
    "@invertase/react-native-apple-authentication": "^2.1.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/checkbox": "^0.5.7",
    "@react-native-community/cli-platform-android": "^4.13.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/app": "^10.5.0",
    "@react-native-firebase/auth": "^10.5.1",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "axios": "^0.21.1",
    "i18n-js": "^3.8.0",
    "install": "^0.13.0",
    "metro-config": "^0.65.0",
    "prettier": "^2.2.1",
    "prop-types": "^15.7.2",
    "react": "17.0.1",
    "react-devtools": "^4.10.1",
    "react-native": "0.63.4",
    "react-native-fbsdk": "3.0.0",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-google-signin": "^2.1.1",
    "react-native-localize": "^2.0.1",
    "react-native-oauth": "^2.1.18",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-svg": "^12.1.0",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.19.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest": "^26.6.3",
    "jetifier": "^1.6.6",
    "metro": "^0.65.0",
    "metro-react-native-babel-preset": "^0.65.0",
    "react-test-renderer": "17.0.1"
  },

**Comment by ngocdaothanh** [comment]
> npm ls metro-config

Thanks @gabrielsaviank for the hint, it helped me 👍 

In my case, I get the error "index.js: Transformer.transform is not a function" after updating from react-native from 0.63.4 to 0.64.0 (BTW, I use [npm-check-updates](https://github.com/raineorshine/npm-check-updates)).

After running the command, I see this:

```
└─┬ react-native-macos@0.63.23
  └─┬ @react-native-community/cli@4.14.0
    ├─┬ metro@0.59.0
    │ └── metro-config@0.59.0  deduped
    └── metro-config@0.59.0 
```

So, I'm using react-native-macos 0.63.23, and it's not compatible with react-native 0.64.0, and it caused the problem.

My solution is removing react-native-macos to fix the error "index.js: Transformer.transform is not a function".

**Comment by lucasfronza** [comment]
> npm ls metro-config

This helped me as well!

For anyone having issues upgrading to 0.64, the above showed me that my issue was with `@react-native-community/cli`. I had an incompatible version installed.

**Comment by DevenHurt** [comment]
> @react-native-community/cli

That's my issue as well. What exactly did you do to solve it? I can't quite figure it out.

**Comment by DevenHurt** [comment]
> > npm ls metro-config
> 
> This helped me as well!
> 
> For anyone having issues upgrading to 0.64, the above showed me that my issue was with `@react-native-community/cli`. I had an incompatible version installed.

That's my issue as well. What exactly did you do to solve it? I can't quite figure it out.

**Comment by glynnallen1704** [comment]
Also needed to upgrade CLI dependency.


@react-native-community/cli | react-native
-- | --
^5.0.0 (master) | ^0.64.0
^4.0.0 | ^0.62.0
^3.0.0 | ^0.61.0
^2.0.0 | ^0.60.0
^1.0.0 | ^0.59.0

**Comment by DevenHurt** [comment]
> Also needed to upgrade CLI dependency.
> 
> @react-native-community/cli	react-native
> ^5.0.0 (master)	^0.64.0
> ^4.0.0	^0.62.0
> ^3.0.0	^0.61.0
> ^2.0.0	^0.60.0
> ^1.0.0	^0.59.0

That worked. Thank you!

**Comment by ashnassadiyan** [comment]
i could fix this just running npm install 
and i  have removed metro.config.js

**Comment by aravi365** [comment]
Got the error : Tranformer is not a constructor after upgrading to 0.64.2 . Tried all those workarounds mentioned here, but none worked!

**Comment by am2619015** [comment]
> @answer-huang
> Oi mate. you talked a lot about the bug but didn't told us how to solve it. But I figured out:
> First I ran `npm ls metro-config`
> It'll tell you that there are some missing stuff about the babel 0.58.
> Following this I downgraded ` "metro-react-native-babel-preset": "0.59.0",` to "metro-react-native-babel-preset": "0.58.0" in package.json.
> Then I ran `npm install`
> After that `pod install`
> Then `npx react-native run-ios`
> This worked for me.

This works perfectly thanks
