### ISSUE TITLE
Testing using jest broken since 0.14.0

### ISSUE THREAD

**Issue by gethinwebster** [facebook/react-native#3999]
The `jestSupport/scriptPreprocess.js` file that is recommended for use in testing (see https://facebook.github.io/react-native/docs/testing.html#jest-tests) was removed in 0.14.0:

https://github.com/facebook/react-native/commit/54b1402c435832a2a98c9252c5f6dacaed631ffe

Using `preprocessor.js` instead doesn't work, because it makes assumptions about the folder structure, and therefore where `babel-core/package.json` can be found.

Can scriptPreprocess be added back in, or is there now a different recommendation for running tests?

**Comment by ashleydw** [comment]
I had the same problem. I solved it by removed `babel-core` from my `package.json` file (which I had in my file because I am using the hot loader [https://github.com/mjohnston/react-native-webpack-server]).

Once removed, `babel-core` will be installed into the `react-native` directory instead of the root `node_modules`.

**Comment by admmasters** [comment]
Hmm having done that I'm getting: "babel.Transformer is not a function".

**Comment by MicheleBertoli** [comment]
+1

**Comment by tadeuzagallo** [comment]
@admmasters Do you have any babel-plugin version 5 installed?

**Comment by MicheleBertoli** [comment]
I basically created a new react-native project, installed jest and get the following error:
`Error: ENOENT: no such file or directory, open '/Users/.../node_modules/react-native/node_modules/babel-core/package.json'`

Setup:
Mac OS v10.10.5
node v5.0.0
npm v3.4.0
react-native-cli v0.1.7
react-native v0.14.2
jest-cli v0.7.1

Config:
```
"jest": {
  "scriptPreprocessor": "node_modules/react-native/jestSupport/preprocessor.js",
  "setupEnvScriptFile": "node_modules/react-native/jestSupport/env.js",
  "testPathIgnorePatterns": [
    "/node_modules/",
    "packager/react-packager/src/Activity/"
  ],
  "testFileExtensions": [
    "js"
  ],
  "unmockedModulePathPatterns": [
    "promise",
    "source-map"
  ]
},
```

/cc @cpojer

**Comment by dshalom** [comment]
Im having the same issue too, my settings are: 
Mac OS v10.10.5
node v5.1
npm v3.5.0
react-native-cli v0.1.7
react-native 0.1.7
jest-cli v0.8.0

**Comment by adrienthiery** [comment]
As a quick-fix, if you have babel-core in your ```node_modules/``` folder, you can symlink your node_modules folder into ```node_modules/react-native/``` (```ln -s `pwd`/node_modules/ ./node_modules/react-native/``` from your root folder)

**Comment by ahanriat** [comment]
This issue comes with npm 3.x as it try to flatten dependencies ([see this article](http://dailyjs.com/2015/06/26/npm-3/)). You can resolve it by using the `v4.2.3` of **nodejs** (I've done this for my CI).

**Comment by ahanriat** [comment]
@ide I think you can close this issue :tada:

**Comment by masom** [comment]
@ahanriat RN engine specs says anything greater than 4. https://github.com/facebook/react-native/blob/master/package.json#L11

Installing or upgrading node on OS X results in a borked jest.

**Comment by ide** [comment]
Have people been able to get their own tests working with jest? Happy to close this but would like to point people at a blog post or similar resource if there's one available.

**Comment by masom** [comment]
@ide I got Jest running on 0.16.

NPM 2.x has to be installed. Won't work on vanilla NodeJS 5.x.

The docs only recommend using 2.x:
> If you are using Node 5.0 or newer, we recommend installing npm 2, which is much faster than npm 3. After installing Node, run npm install -g npm@2.

http://facebook.github.io/react-native/docs/getting-started.html

Babel also does not seem to be transforming properly.

Doing `require('../Something')` does not return the default export.

**Comment by gethinwebster** [comment]
@ide same here, managed to get it working by going back to NPM 2.x

@masom I believe that's due to the change to Babel 6 in 0.16: it used to return the default export as both `require(module).default` and plain `require(module)`, but now the first method is needed: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by masom** [comment]
@gethinwebster In the app itself doing:
```
import Something from './Something';
````

works but when executing with Jest something screws up the transform and this happens:
```
  - TypeError: _Something2.default is not a function
        at Spec.<anonymous> (App/Models/__tests__/User-test.js:10:14)
```

**Comment by gethinwebster** [comment]
Odd - pretty much the opposite behaviour to the behaviour to the related issue I saw! Probably worth opening a new issue for that, as it sounds like it's related to Babel 6 in 0.16, rather than the earlier changes to preprocessor.

**Comment by cpojer** [comment]
Yeah there are a bunch of new technologies that got shipped pretty quickly and we didn't have enough time to figure all of this out in jest. We'll add better npm3 mocking support to jest "soon" and fix the issue with babel's imports.

**Comment by ahanriat** [comment]
@masom Totally agree, as long as node 5.x is packaged by default with npm 3, there is a breaking change in the way node modules are arranged. At this point there are two solution:
- specify min required node version to 5.x and modify [this the preprocessor script](https://github.com/facebook/react-native/blob/0.16-stable/jestSupport/preprocessor.js#L29) to match npm 3 requirements
- specifify node version >= 4.x and < 5.x and let the preprocessor script as it is

**Comment by Andrewpk** [comment]
@ahanriat 👍

**Comment by pietropizzi** [comment]
@masom I have the exact same thing as you in RN 0.16: https://github.com/facebook/react-native/issues/4784

**Comment by pietropizzi** [comment]
@cpojer I think I narrowed it down to a bug in this babel plugin https://github.com/facebook/fbjs/blob/master/scripts/babel-6/inline-requires.js

If you  set `inlineRequires` to `false` in https://github.com/facebook/react-native/blob/master/jestSupport/preprocessor.js#L23 it works. Meaning that something in the aforementioned plugin must be what is causing it.

**Comment by cpojer** [comment]
The above issue about export default is unrelated to inline-requires. We are currently building a plugin to fix this but any help would be appreciated (we need someone to write a babel plugin :) ). The inline-require transform shouldn't be related to the export default issue. However, it might be an issue for your existing code.

We transform require statements (not imports) to be inline, which might break some of your tests and you have to fix them up manually. We've been using this transform for a long time though, did this just now get shipped with react-native?

**Comment by pietropizzi** [comment]
@cpojer The script I mentioned is quite new. It's first commit is on the 7th of November. It is the babel-6 version of the script, which has some slight differences from the babel-5 one.

I am using `require`s in my tests since there is an issue with `import` where the imported modules get hoisted to the to of the file and thereby get required before `jest.dontMock` calls.

It might still be that somehow our test-code is not handling the inline-requires too well. Not sure.

**Comment by cpojer** [comment]
babel 6 changed how modules are imported. If you are using `require` for something that is exported using `export default`, for now you'll have to do `require('Foo').default` in your test. I realize this sucks and I'd like to fix this using a custom transform for test-files only that doesn't hoist imports. This should solve all of our problems regarding imports.

**Comment by pietropizzi** [comment]
@cpojer that would be great! I'm already using the `require('Foo').default` in my tests. But inside those modules that are being required something goes wrong.

**Comment by cpojer** [comment]
Can you share a module that isn't working for you?

**Comment by grabbou** [comment]
To add in some context - I am also experiencing an issue when `inlineRequire` is set to true (after upgrading from 0.15 to 0.17).

With `true`:
```
ReferenceError: /src/auth/newPasswordForm.js: _immutable is not defined
        at Object.<anonymous> (src/auth/newPasswordForm.js:3:30)
```
```js
import {Map} from 'immutable'
```
is simply striped out from transformed code (the first line in the file). Setting it to `false` makes tests green again.

**Comment by akshaysmurthy** [comment]
I am on RN v0.17, node v5.1.0 and npm v2.14.15. I still get `Error: ENOENT: no such file or directory, open '/Users/.../node_modules/react-native/node_modules/babel-core/package.json'`

**Comment by ahanriat** [comment]
@akshaysmurthy you should try with node 4.x.x (packaged with npm 2), this way you won't have this problem :)

**Comment by anderson916** [comment]
@akshaysmurthy I overcome this issue by modifying **./node_modules/react-native/jestSupport/preprocessor.js**.

!(Instuctions)[https://github.com/facebook/react-native/commit/a3706411ab5c8e0d49ab3c1930d223fa40d38a7e]

**Comment by akshaysmurthy** [comment]
Thanks @anderson916, that worked!

**Comment by ahanriat** [comment]
\o/

**Comment by ColCh** [comment]
I have same issue , on __React Native v0.19.0__:

For this source:
```js
import {combineReducers} from 'redux';
export const SET_TIME = `Timer/SET__TIME`;
```
It gets transpiled to:
```js
Object.defineProperty(exports,"__esModule",{value:true});exports.appendTime=exports.APPEND_TIME=exports.setTime=exports.SET_TIME=undefined;

var SET_TIME=exports.SET_TIME='Timer/SET__TIME';
```

But if I change `inlineRequires` to `false`, script gets transpilled right:
```js
Object.defineProperty(exports,"__esModule",{value:true});exports.appendTime=exports.APPEND_TIME=exports.setTime=exports.SET_TIME=undefined;var _redux=require('redux');

var SET_TIME=exports.SET_TIME='Timer/SET__TIME';
```
(See that `var _redux=require('redux');` ?)

**Comment by cpojer** [comment]
The latest version of babel6 should have a way to add a separate transform pass, see: https://github.com/babel/babel/blob/master/CHANGELOG.md#a-traversal-per-preset-experimental

can you try putting the inline require transform into a separate pass, after all the others and show he output?

I'm currently working on fixing imports for jest 0.9 as well and hope this problem will go away.

**Comment by ColCh** [comment]
Patched _react-native/packager/transformer.js_:
```js

  //if (options.inlineRequires) {
  //  extraPlugins.push(inlineRequires);
  //}
  config.plugins = resolvePlugins(extraPlugins.concat(config.plugins));


  var babelConfig = Object.assign({}, babelRC, config);

  babelConfig.passPerPreset = true;
  babelConfig.presets = [ {"plugins":babelConfig.plugins}, {"plugins":[inlineRequires]} ];
  delete babelConfig.plugins;
  
  const result = babel.transform(src, babelConfig);
```

Transpilled script, for same source as below:
```js
Object.defineProperty(exports,"__esModule",{value:true});exports.default=

(0,require('redux').combineReducers)({
time:function(){var state=arguments.length<=0||arguments[0]===undefined?0:arguments[0];var action=arguments.length<=1||arguments[1]===undefined?{}:arguments[1];
switch(action.type){
case SET_TIME:
return action.time;
case APPEND_TIME:
return state+action.time;
default:
return state;}}});
```

But then ...
```
TypeError: (0 , require(...).combineReducers) is not a function
```
wtf?! this may be unrelated to this issue

**Comment by cpojer** [comment]
Just double checking, is `redux` in your `unmockedModulePathPatterns` list in your config?

**Comment by ColCh** [comment]
No, I find other way to require it:
```
jest.autoMockOff();
const TimerDuck = require(`../TimerDuck`);
jest.autoMockOn();
```

**Comment by cpojer** [comment]
I'll recommend doing that instead of disabling/enabling auto-mocking.

jest-cli@0.9.0-fb3 will be tagged soon as another beta for the new jest version. It will support proper transitive dependency unmocking for npm3, so that might also fix your issues. I'll tag it sometime this week :)

**Comment by ColCh** [comment]
I'd like to use:
```
jest.dontMock(`redux`);
jest.dontMock(`../TimerDuck`);
const TimerDuck = require(`../TimerDuck`);
```
But it returns mocked version of _redux_ on my source. 

I see commit 7b44ca in Jest . Nice! Waiting for npm publish :) 

And... what about inlineRequires?

**Comment by jsierles** [comment]
@gethinwebster @ColCh is this issue still relevant? Let me know if we can close it in favor of a PR or more specific issue.

**Comment by grabbou** [comment]
My tests still break because of some `import` statements in the code (but they used to work). Let me check that internally tomorrow and report back.

**Comment by cpojer** [comment]
I'm currently rewriting the documentation around Jest. The latest version of Jest and `babel-jest` have this issue resolved, but the integration with react-native isn't ideal yet. There'll be more info soon :)

**Comment by ColCh** [comment]
@jsierles my case works for me now

**Comment by cpojer** [comment]
Thank you for your patience. We launched Jest 14.0 with experimental react-native support:

* [Blog Post](http://facebook.github.io/jest/blog/2016/07/27/jest-14.html)
* [React-Native Tutorial](http://facebook.github.io/jest/docs/tutorial-react-native.html)

Please feel free to create new issues after trying out the new integration if any issues remain.
