### ISSUE TITLE
Issue after upgrading React Native from 0.73.9 to 0.78.2

### ISSUE THREAD

**Issue by MuhammedHarisMKS** [facebook/react-native#50725]
### Description

<img width="424" alt="Image" src="https://github.com/user-attachments/assets/f2a116b3-f3c1-4711-b9ed-580b459d1c12" />

I recently upgraded my React Native project from version 0.73.9 to 0.78.2. (with the help of [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper))

1. Ran ./gradlew clean – worked fine
2. Ran npx react-native run-android – build was successful

However, after launching the app, I get a red screen with the following error:
`[runtime not ready]: TypeError: e is not a function (it is undefined), js engine: hermes`

Stack trace includes:
`anonymous@2022:11756  
_createStore@2022:3700  
loadModuleImplementation@2:4186  
...`

Any idea what could be causing this? Could it be due to an incompatible library or a breaking change in RN 0.78?

### Steps to reproduce

1. upgrade 0.73.9 to 0.78.2.
2. then run react-native run-android

### React Native Version

0.78.2

### Affected Platforms

Runtime - Android

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: macOS 15.3.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 130.00 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.19.0
    path: ~/.nvm/versions/node/v20.19.0/bin/node
  Yarn:
    version: 1.22.18
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.19.0/bin/npm
  Watchman:
    version: 2025.03.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK:
    API Levels:
      - "23"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
      - 36.0.0
    System Images:
      - android-32 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.3 AI-243.24978.46.2431.13208083
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.1.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 11.3.10
    wanted: 11.3.10
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.78.2
    wanted: 0.78.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
no logs available
```

### Reproducer

nill

### Screenshots and Videos

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/13a2f81e-49b3-4860-8352-6e58ee9baa8d" />

**Comment by MuhammedHarisMKS** [comment]
> Warning
> 
> **Missing reproducer**: We could not detect a reproducible example in your issue report. Please provide either:
> 
> * If your bug is UI related: a [Snack](https://snack.expo.dev)
> * If your bug is build/upgrade related: a project using our [Reproducer Template](https://github.com/react-native-community/reproducer-react-native/generate)
> * Otherwise send us a Pull Request with the [RNTesterPlayground.js](https://github.com/facebook/react-native/blob/main/packages/rn-tester/js/examples/Playground/RNTesterPlayground.js) edited to reproduce your bug.

How can I give that. Because this is my existing project.

**Comment by MuhammedHarisMKS** [comment]
> Warning
> 
> **Could not parse version**: We could not find or parse the version number of React Native in your issue report. Please use the template, and report your version including major, minor, and patch numbers - e.g. 0.76.2.

current version - **0.78.2**
old version - 0.73.9

**Comment by MuhammedHarisMKS** [comment]
<img width="388" alt="Image" src="https://github.com/user-attachments/assets/29137f33-6b74-4c5b-acd7-baaef66cedfb" />

Now the error showing like this

**Comment by fempyrean** [comment]
@MuhammedHarisMKS I'm seeing a similar error after upgrading to 0.79.0. In my case, I suspect it has something to do with autolinking native libraries.

If you open up Android Studio and try to run Gradle Sync, does it work or does it throw any errors? Just wondering if both our issues are related.

I've attached an image of what I see when I try to run Gradle Sync. And this is one of the error messages I see:

```
CMake Error at /home/trickfinger/Studies/mobile/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:10 (add_subdirectory):
add_subdirectory given source
"/home/trickfinger/Studies/mobile/node_modules/@react-native-vector-icons/common/android/build/generated/source/codegen/jni/"
which is not an existing directory.
Call Stack (most recent call first):
/home/trickfinger/Studies/mobile/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:100 (include)
CMakeLists.txt:31 (include)
```

This one is from `react-native-vector-icons`, but this happens to many other libraries as well.

![Image](https://github.com/user-attachments/assets/c72c75d3-9d24-4dd7-9541-ea24721cdc2d)

**Comment by cipolleschi** [comment]
@MuhammedHarisMKS This is usually a native module crashing in the C++ layer. you have two alternatives to figure out the module that is crashing:
1. Run the iOS app in Xcode enabling the exception breakpoints. The app will stop as soon as the c++ module crashes and you can see the module name.
2. You can create a new project with 0.79 and add one dependency at the time until the project stops building. When this happens, you have found the module that is crashing.

**Comment by MuhammedHarisMKS** [comment]
> [@MuhammedHarisMKS](https://github.com/MuhammedHarisMKS) I'm seeing a similar error after upgrading to 0.79.0. In my case, I suspect it has something to do with autolinking native libraries.
> 
> If you open up Android Studio and try to run Gradle Sync, does it work or does it throw any errors? Just wondering if both our issues are related.
> 
> I've attached an image of what I see when I try to run Gradle Sync. And this is one of the error messages I see:
> 
> ```
> CMake Error at /home/trickfinger/Studies/mobile/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:10 (add_subdirectory):
> add_subdirectory given source
> "/home/trickfinger/Studies/mobile/node_modules/@react-native-vector-icons/common/android/build/generated/source/codegen/jni/"
> which is not an existing directory.
> Call Stack (most recent call first):
> /home/trickfinger/Studies/mobile/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:100 (include)
> CMakeLists.txt:31 (include)
> ```
> 
> This one is from `react-native-vector-icons`, but this happens to many other libraries as well.
> 
> ![Image](https://github.com/user-attachments/assets/c72c75d3-9d24-4dd7-9541-ea24721cdc2d)

In my case, Gradle Sync is works fine. Please check the following screenshots


<img width="1359" alt="Image" src="https://github.com/user-attachments/assets/77cd175b-d688-4545-bf87-38a2af0d4af4" />

<img width="1324" alt="Image" src="https://github.com/user-attachments/assets/48adb4ce-a33e-4e1d-8d8a-293392e5208f" />

**Comment by shubhanshubb** [comment]
In my case also app crashes after build successful
when i click on any button it stop working stuck in that screen

You can more detail in this issue: https://github.com/software-mansion/react-native-screens/issues/2870

**Comment by MuhammedHarisMKS** [comment]
> I'm seeing a similar error after upgrading to 0.79.0. In my case, I suspect it has something to do with autolinking native libraries.
> 
> If you open up Android Studio and try to run Gradle Sync, does it work or does it throw any errors? Just wondering if both our issues are related.
> 
> I've attached an image of what I see when I try to run Gradle Sync. And this is one of the error messages I see:

I can able find the exact same error 
removed the entire node_modules 
then re install through yarn 
Then I can able to see the same error u shared

<img width="1324" alt="Image" src="https://github.com/user-attachments/assets/62622501-13be-446a-872f-529844062bea" />

**Comment by shubhanshubb** [comment]
but I am facing in ios after xcode build

**Comment by cipolleschi** [comment]
I feel that we have two different issues here: one for android by @MuhammedHarisMKS, that looks like it is solved, and one on iOS from @shubhanshubb.

@shubhanshubb can you open a different issue, explaining what are you seeing and providing a reproducer please?
It makes it easier for us to understand what's going wrong in that way.

**Comment by sirius1888** [comment]
@fempyrean try to use ./gradlew generateCodegenArtifactsFromSchema after yarn install

**Comment by charitha-work** [comment]
What did yall do to solve this? I face this error now.
