### ISSUE TITLE
console.assert is not a function

### ISSUE THREAD

**Issue by BarinderGrewal** [facebook/react-native#26962]
I am using an NPM module [event-target-shim](https://www.npmjs.com/package/event-target-shim) in my app.
Everything was working fine till react-native 0.59, but when I upgraded to react-native 0.60, I started seeing below error in the red box:
> console.assert is not a function

![Screenshot_20191023-103920](https://user-images.githubusercontent.com/22869173/67360202-ee0e9f00-f582-11e9-887f-0c384e327a79.png)

event-target-shim module is using console.assert in their code but I think this error is related to react-native upgrade as the same code was working in react-native 0.59

React Native version: 0.60.0

System:
    OS: Windows Server 2016
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 41.64 GB / 63.90 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 16.0.4442984
  IDEs:
    Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.0 => 0.60.0

## Steps To Reproduce

1. Create a react-native app that uses event-target-shim as a dependency.
2. Try to run the app in android device, you will see the above error.

**Comment by rmariscal13** [comment]
I had the same problem, and i noticed that i had a piece of code like:
```
if (!__DEV__) {
  console.log('disabling console');
  console = {};
  console.log = () => {
  };
  console.error = () => {
  };
  console.warn = () => {
  };
}
```
that made console an empty object.
