### ISSUE TITLE
error: SyntaxError: .../node_modules/react-native/Libraries/Components/Touchable/Touchable.js: Unexpected token, expected "]" (25:45)

### ISSUE THREAD

**Issue by alexkendall** [facebook/react-native#34719]
### New Version

0.70.0

### Old Version

0.63.3

### Build Target(s)

iOS 16.0

### Output of `react-native info`

System:
    OS: macOS 13.0
    CPU: (8) x64 Apple M1
    Memory: 27.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/alex/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0
      System Images: android-25 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

1. Build the app using Xcode 14
2. yarn start --reset-cache
3. Error displays

**Comment by alexkendall** [comment]
<img width="535" alt="Screenshot 2022-09-19 at 8 06 07 PM" src="https://user-images.githubusercontent.com/8241866/191139921-963c8538-5316-4787-8dca-15a3f38aecd6.png">

**Comment by hemantgogia09** [comment]
+1 Same issue is happening to me

**Comment by ChaseApptentive** [comment]
Same for Android upgrading form `0.63.4`

**Comment by alexkendall** [comment]
By the way @here. I had to patch that file using the version from 0.69 with patch-package to get the latest version of react-native to compile after upgrading from 0.63.3

**Comment by bulatshafigullin** [comment]
Just upgraded from 0.63.4 to 0.70.1 and got this error
This helped me
`rm -fr node_modules`
`watchman watch-del-all`

**Comment by maximpostnikov** [comment]
Running into this error as well, upgraded from 0.67.3 to 0.70.3

**Comment by rmojsejkov** [comment]
Hello, solve this issue writing this in console:
rm -rf node_modules
rm yarn.lock
yarn

**Comment by dcangulo** [comment]
Issue persists when upgrading from 0.69.3 to 0.70.4

**Comment by xianguoGou** [comment]
I also had a similar problem

**Comment by aprakimble** [comment]
It's because babel core and runtime are out of date when you upgrade.

Even though the package.json specifies an earlier version when you start a new project from scratch it installs a newer version that works. I am sure all testing was done from scratch.

Force an update to:

"@babel/core": 7.20.5
"@babel/runtime": 7.20.6

The versions which came right from the lock files of a new install and it resolves the issue.

**Comment by lzbrady** [comment]
I upgraded from RN 0.63.4 to 0.70.6 and am still facing this issue.

- Upgrading @babel/core to 7.20.5 and @babel/runtime to 7.20.6 did not work for me. (Upgrade helper specifies these versions differently btw)
- `rm -rf node_modules/ && yarn && (cd ios && pod install) && watchman watch-del-all` did not work either

**Comment by robhogan** [comment]
This should be fixed in `main` by https://github.com/facebook/react-native/commit/3e19c9764634049731b4bf96dc1c716064394d62. @cortinico, might be worth picking the Babel updates into 71?

**Comment by irfanukani** [comment]
Can anyone help me solve this issue? I Mean What to do?

**Comment by dcangulo** [comment]
@irfanukani Run `yarn add @babel/core --dev`

**Comment by irfanukani** [comment]
@dcangulo I already did that.

![image](https://user-images.githubusercontent.com/57797732/207079863-f4789c2c-2da8-48f7-a4da-e3f124a16d39.png)

**Comment by gowravl** [comment]
Still getting the same error after upgrading to
"@babel/core": 7.20.5
"@babel/runtime": 7.20.6

**Comment by NETCHANOK61** [comment]
Can anyone help me solve this issue?

**Comment by gowravl** [comment]
Update these two dev dependencies to the below versions
"@babel/core": 7.20.5
"@babel/runtime": 7.20.6

Then delete your node modules and 
yarn install or npm install

It should start working.

**Comment by robhogan** [comment]
Changing `package.json` might not get what you want and shouldn't be necessary. The simplest thing to do, if you can, is to delete `yarn.lock` and run `yarn` again.

**Comment by maximpostnikov** [comment]
@robhogan it is a bad idea. this should be done only if package.json has fixed versions without ^

**Comment by robhogan** [comment]
Updating versions within your project's `package.json` will force an update to your top-level Babel but won't necessarily change the lockfile entry that locks Metro to a buggy version of Babel, so you may still get those buggy older versions nested within your `node_modules` - that's why that fix hasn't worked for some people in this thread. 

By deleting the lockfile, you'll allow Yarn to look up the latest versions of Babel that match Metro's dependencies, which today will be 7.20.x.

**Comment by raldred** [comment]
Seeing this issue after upgrading to 0.70 but only when running jest tests.
Running the app in simulator or on device works fine.

@babel/core: 7.20.12
@babel/runtime: 7.20.7

```
SyntaxError: node_modules/react-native/Libraries/Components/Touchable/Touchable.js: Unexpected token, expected "]" (25:45)

      23 |
      24 | const extractSingleTouch = (nativeEvent: {
    > 25 |   +changedTouches: $ReadOnlyArray<PressEvent['nativeEvent']>,
         |                                              ^
      26 |   +force?: number,
      27 |   +identifier: number,
      28 |   +locationX: number,

      at Object._raise (node_modules/jest-config/node_modules/@babel/parser/src/parser/error.js:60:45)
```

If I try to use the exact versions of babel runtime and core suggested earlier, I get a different issue (`Cannot find module '@babel/parser' to link`)

**Comment by bwindsor** [comment]
It sounds like this is probably solved in RN 0.71, but I'm on 0.70.7 and still getting issues. Adding this to my `package.json` solved it for me. See https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides for details of what this does.
```
"overrides": {
    "@react-native-community/cli": "^10.1.0"
}
```

**Comment by Coffeegerm** [comment]
Upgrading from 69 up to 70 and seeing the same error, however I am not seeing it in runtime but instead when running tests. 

I've gone ahead and updated both babel packages to the following:

@babel/core: 7.20.12
@babel/runtime: 7.20.7

But still seeing the issue present in tests.

@bwindsor I am going to try your solution to see if it will work in our current branch with the upgrade. Does your suggestion include clearing out the `yarn.lock` file to make sure the desired cli is picked up?

**Comment by Coffeegerm** [comment]
@bwindsor Dang, neither 

```
"overrides": {
    "@react-native-community/cli": "^10.1.0"
}
```

or

```
"overrides": {
  "react-native: {
      "@react-native-community/cli": "^10.1.0"
   }
}
```

have seemed to work. Not seeing any indication of the `yarn.lock` file getting updated for the new dependency version 😞

Has anyone else found a possible solution beyond a patch-package?

**Comment by RyanSpeciale** [comment]
ANYONE EVER SOLVE THIS ISSUE?

**Comment by RyanSpeciale** [comment]
working on a project that I took from RN 0.63.3 to 0.70.0 and I am now seeing this issue, I tried removing node modules and re-installing.

**Comment by hazemmuuhammed** [comment]
is there any ideal solution ?
