### ISSUE TITLE
Error :  Use of undeclared identifier 'YGValue' when building iOS

### ISSUE THREAD

**Issue by JB-CHAUVIN** [facebook/react-native#33976]
### Description

Hello,

I have the following error when building with the latest RN version.

I was just trying to upgrade... 
![iScreen Shoter - 2022-06-08 10:29:49 688](https://user-images.githubusercontent.com/8957878/172570383-e7406ae2-15e8-448e-a654-b509a6cea699.jpg)

```
Error :  Use of undeclared identifier 'YGValue' when building iOS
```

### Version

0.69-RC.6

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 1.71 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.0-rc.6 => 0.69.0-rc.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I tried to upgrade...

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by mfik** [comment]
Same!

**Comment by mfik** [comment]
Related #33815

**Comment by fortmarek** [comment]
Hey @JB-CHAUVIN 👋 

Would it be possible to add a sample or reproduction steps? The current `0.69.0-rc.6` works when using a project created with the RN template.

**Comment by mfik** [comment]
@fortmarek I just upgraded RN to this version and the error has disappeared

**Comment by mfik** [comment]
The new error is for react-native-webview

<img width="360" alt="image" src="https://user-images.githubusercontent.com/8059774/173410433-3080e39d-ef83-4298-8c4e-bb2bf7dea527.png">

Package:

{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "expo start --dev-client",
    "test": "jest"
  },
  "dependencies": {
    "@config-plugins/react-native-google-cast": "^2.0.0",
    "@expo-google-fonts/poppins": "^0.2.2",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.1",
    "@react-navigation/stack": "^6.2.1",
    "axios": "^0.21.1",
    "expo": "^45.0.5",
    "expo-app-loading": "~2.0.0",
    "expo-av": "~11.2.3",
    "expo-dev-client": "~1.0.0",
    "expo-font": "~10.1.0",
    "expo-image-loader": "~3.2.0",
    "expo-keep-awake": "~10.1.1",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.2",
    "moment": "^2.29.3",
    "react": "18.0.0",
    "react-dom": "17.0.2",
    "react-hook-form": "^6.15.5",
    "react-native": "0.69.0-rc.6",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-google-cast": "^4.2.4",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-sound-player": "^0.12.0",
    "react-native-storage": "^1.0.1",
    "react-native-swift": "^1.2.3",
    "react-native-track-player": "^2.2.0-rc3",
    "react-native-web": "0.17.7",
    "react-native-webview": "^11.22.2",
    "react-player": "^2.10.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-dom": "~17.0.11",
    "@types/react-native": "~0.67.6",
    "babel-preset-expo": "~9.1.0",
    "jest-expo": "^45.0.0",
    "typescript": "~4.3.5"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true,
  "name": "None",
  "version": "1.0.0",
  "isSwift": true
}

**Comment by mfik** [comment]
Placed the file in the folder to see if it would build. Even tho i don't have a case sensitive volume, the next error shows up. The file is in the folder:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/8059774/173411459-49d0a80b-7445-44f2-a4aa-81ec8ec4dfb8.png">

**Comment by mfik** [comment]
Also happening in an almost clean project. @JB-CHAUVIN Is this a priority issue? Haven't been able to build in since monday and i'm seeing a lot of related issues when i search. The error exists in RN 43, 44 and 45 in multiple modules (safe-area-context, webview, Asynstorage).

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/8059774/173810017-afcfbcd2-8a07-424a-9730-fcc51aa1fa54.png">

**Comment by renchap** [comment]
I am seeing the same error when updating my app to RN 0.69-rc6:

```
/Users/renchap/dev/project/node_modules/react-native/Libraries/Text/TextInput/RCTInputAccessoryShadowView.m:17:20: error: use of undeclared identifier 'YGValue'
  subview.width = (YGValue) { RCTScreenSize().width, YGUnitPoint };
```

This seems to be different than https://github.com/facebook/react-native/issues/33648 as I dont have a case-sentitive FS (standard macOS APFS).

**Comment by karatekid430** [comment]
Experiencing this with 0.69.0 release

**Comment by Bardiamist** [comment]
Hmm, I too have this error after update to 0.69.0
Nothing helped as clear pods/clean build
But fresh project built successfully
How to update my project, what can be?

<details> 
  <summary>Output of npx react-native info</summary>

```
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 28.07 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0 => 0.69.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
</details>

**Comment by zhiqingchen** [comment]
same issue

https://github.com/NervJS/taro-native-shell/runs/7024748869?check_suite_focus=true

**Comment by mfik** [comment]
So this has to do with case sensitive file systems. My drive says it isn't, but i believe it was encrypted in the past. The temporary solution is to add this step to the build process, as mentioned : https://github.com/facebook/react-native/issues/33648 

This really needs a fix tho, many hours lost by a lot of people.

```
rm -rf node_modules ios/Pods
yarn
sed -i -e "s/spec.module_name = 'yoga'/spec.module_name = 'Yoga'/g" node_modules/react-native/ReactCommon/yoga/Yoga.podspec
npx pod-install
expo run:ios
```

**Comment by ph4r05** [comment]
I have the same problem but @mfik's workaround is not working for me. 

For some reason, the error is fixed when I rename `RCTInputAccessoryShadowView.m` to `RCTInputAccessoryShadowView.mm` so Obj-C++ is used. 

Ofc I have to change also `node_modules/react-native/Libraries/Text/React-RCTText.podspec` in a way `*.mm` files are taken into account

```
s.source_files           = "**/*.{h,m,mm}"
```

after reinstalling pods, error is fixed. I don't have case-sensitive FS. I am currently investigating why Obj-C++ manages to include `yoga/Yoga.h` types and Obj-C does not.

**Comment by ph4r05** [comment]
@renchap great it works for you as well! The patch renames `RCTBaseTextShadowView.m` to `RCTBaseTextShadowView.mm` too.  I edited the original comment to include also patch to `react-native-safe-area-context` module which was needed on my side as well. But from what I see now, don't we have the same set of changed files?

**Comment by renchap** [comment]
I missed your `RCTBaseTextShadowView.m` renaming!

It now compiles correctly with your 2 patches 🎉

**Comment by lisong996** [comment]
same question after install expo

**Comment by innocodes** [comment]
> Thanks @ph4r05 this indeed makes the build move forward for me (case-insensitive FS as well).
> 
> But it fails a bit later with:
> 
> ```
> /Users/renchap/dev/project/node_modules/react-native/Libraries/Text/BaseText/RCTBaseTextShadowView.m:17:42: error: missing '#include "yoga/Yoga.h"'; 'YGNodeRef' must be declared before it is used
> static void RCTInlineViewYogaNodeDirtied(YGNodeRef node)
>                                          ^
> In module 'React' imported from /Users/renchap/dev/project/node_modules/react-native/Libraries/Text/BaseText/RCTBaseTextShadowView.m:8:
> /Users/renchap/dev/project/packages/mobile/ios/Pods/Headers/Public/Yoga/yoga/Yoga.h:34:24: note: declaration here is not visible
> typedef struct YGNode* YGNodeRef;
> ```
> 
> Once this file has been renamed to `RCTBaseTextShadowView.mm`, it proceeds until:
> 
> ```
> /Users/renchap/dev/notos/node_modules/react-native-safe-area-context/ios/RNCSafeAreaShadowView.m:25:3: error: missing '#include "yoga/YGValue.h"'; 'YGValue' must be declared before it is used
>   YGValue _paddingMetaProps[META_PROP_COUNT];
>   ^
> In module 'React' imported from /Users/renchap/dev/notos/node_modules/react-native-safe-area-context/ios/RNCSafeAreaShadowView.h:1:
> /Users/renchap/dev/notos/packages/mobile/ios/Pods/Headers/Public/Yoga/yoga/YGValue.h:35:3: note: declaration here is not visible
> } YGValue;
>   ^
> ```
> 
> It seems to be the same kind of error. Might it be that those `.m` files are included by libraries, but somehow are no longer correctly picked up by the build system?
> 
> This would explain why it does not happen on a newly created app, and I am hitting more of those than you.

I have a similar issue.

After renaming the affected file in my own case, I am getting an error:

`error: Build input file cannot be found: '/Users/username/initialDesktop/RN-select-country/app-name/node_modules/expo-updates/ios/EXUpdates/AppLoader/EXUpdatesFileDownloader.m'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'EXUpdates' from project 'Pods')
`

Did you run patch-package first before running build iOS command again?

**Comment by innocodes** [comment]
> > Thanks @ph4r05 this indeed makes the build move forward for me (case-insensitive FS as well).
> > But it fails a bit later with:
> > ```
> > /Users/renchap/dev/project/node_modules/react-native/Libraries/Text/BaseText/RCTBaseTextShadowView.m:17:42: error: missing '#include "yoga/Yoga.h"'; 'YGNodeRef' must be declared before it is used
> > static void RCTInlineViewYogaNodeDirtied(YGNodeRef node)
> >                                          ^
> > In module 'React' imported from /Users/renchap/dev/project/node_modules/react-native/Libraries/Text/BaseText/RCTBaseTextShadowView.m:8:
> > /Users/renchap/dev/project/packages/mobile/ios/Pods/Headers/Public/Yoga/yoga/Yoga.h:34:24: note: declaration here is not visible
> > typedef struct YGNode* YGNodeRef;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Once this file has been renamed to `RCTBaseTextShadowView.mm`, it proceeds until:
> > ```
> > /Users/renchap/dev/notos/node_modules/react-native-safe-area-context/ios/RNCSafeAreaShadowView.m:25:3: error: missing '#include "yoga/YGValue.h"'; 'YGValue' must be declared before it is used
> >   YGValue _paddingMetaProps[META_PROP_COUNT];
> >   ^
> > In module 'React' imported from /Users/renchap/dev/notos/node_modules/react-native-safe-area-context/ios/RNCSafeAreaShadowView.h:1:
> > /Users/renchap/dev/notos/packages/mobile/ios/Pods/Headers/Public/Yoga/yoga/YGValue.h:35:3: note: declaration here is not visible
> > } YGValue;
> >   ^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems to be the same kind of error. Might it be that those `.m` files are included by libraries, but somehow are no longer correctly picked up by the build system?
> > This would explain why it does not happen on a newly created app, and I am hitting more of those than you.
> 
> I have a similar issue.
> 
> > (node_modules/expo-updates/ios/EXUpdates/AppLoader/EXUpdatesFileDownloader.m:96:35)
> > 94 | {
> > 95 |   [self downloadDataFromURL:url extraHeaders:extraHeaders successBlock:^(NSData *data, NSURLResponse *response) {
> > 96 |     NSString *hashBase64String = [EXUpdatesUtils base64UrlEncodedSHA256WithData:data];
> > |                                   ^ use of undeclared identifier 'EXUpdatesUtils'
> > 97 |     if (expectedBase64URLEncodedSHA256Hash && ![expectedBase64URLEncodedSHA256Hash isEqualToString:hashBase64String]) {
> > 98 |       errorBlock([NSError errorWithDomain:EXUpdatesFileDownloaderErrorDomain
> > 99 |                                      code:EXUpdatesFileDownloaderErrorCodeFileHashMismatchError
> 
> So I renamed EXUpdatesFileDownloader.m to EXUpdatesFileDownloader.mm
> 
> After renaming the affected file in my own case, I am getting an error:
> 
> `error: Build input file cannot be found: '/Users/username/initialDesktop/RN-select-country/app-name/node_modules/expo-updates/ios/EXUpdates/AppLoader/EXUpdatesFileDownloader.m'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'EXUpdates' from project 'Pods') `
> 
> Did you run patch-package first before running build iOS command again?

I solved the new error by running pod deintegrate, and pod install.

However, this led to more errors in the code after running 'npm run ios' command.

Any fix for this yet?
