### ISSUE TITLE
upgrade from v0.28 to 0.29.0-rc.00.29-rc.0 causes immediate crash on Android

### ISSUE THREAD

**Issue by kulicuu** [facebook/react-native#8491]
Super fresh install with `react-native init <name>`, works.  This with version 0.28.  Then with upgrade in package.json to 0.29.0-rc.0 (and React 15.2.0-rc.1 which works with the RN v0.28) and `react-native run-android` crashes immediately in the emulator.  

(already React v15.2.0-rc.1 working with RN v0.28; so the only thing I need to do to switch from working app to immediate crash is change package.json entry version for RN to 0.29.0-rc.0)

Terminal output on the `react-native run-android` command:
```
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/home/wylie/Projects_Park/ReactNative/Sergata/proto_002/android/app/src/main/java/com/proto_002/MainActivity.java:34: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
```

`adb logcat [...]` gives nothing.

This part of the issue can be repaired by running `react-native upgrade` and permitting the cued file overwrites, then restarting `react-native start` and `react-native run-android` no longer gives those errors on the build but the app crashes immediately in the emulator with the message "Unfortunately, <name> has stopped."  Still no log output.

**Comment by satya164** [comment]
Please refer to the release notes on upgrading - https://github.com/facebook/react-native/releases/tag/v0.29.0-rc.0

**Comment by kulicuu** [comment]
thanks !

**Comment by davidcurras** [comment]
I just upgraded to v0.30 and I'm getting the same error. Running `react-native upgrade` and permitting the cued file overwrites, then restarting `react-native start` and `react-native run-android` no longer gives those errors on the build but the app crashes immediately in the emulator with the message "Unfortunately, has stopped."
How you did you solved it on v0.29 @kulicuu ?
