### ISSUE TITLE
duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by rao1220** [facebook/react-native#32016]
I got this when build with latest version of react-native 

duplicate symbol 'folly::detail::str_to_bool(folly::Range<char const*>*)' in:
    /Users/charlier/Library/Developer/Xcode/DerivedData/BanjaraWedding-hhgkttbaoprqvgftffbbkscdmncr/Build/Products/Debug-iphonesimulator/Flipper-Folly/libFlipper-Folly.a(Conv.o)
    /Users/charlier/Library/Developer/Xcode/DerivedData/BanjaraWedding-hhgkttbaoprqvgftffbbkscdmncr/Build/Products/Debug-iphonesimulator/RCT-Folly/libRCT-Folly.a(Conv.o)
duplicate symbol 'folly::makeConversionError(folly::ConversionCode, folly::Range<char const*>)' in:
    /Users/charlier/Library/Developer/Xcode/DerivedData/BanjaraWedding-hhgkttbaoprqvgftffbbkscdmncr/Build/Products/Debug-iphonesimulator/Flipper-Folly/libFlipper-Folly.a(Conv.o)
    /Users/charlier/Library/Developer/Xcode/DerivedData/BanjaraWedding-hhgkttbaoprqvgftffbbkscdmncr/Build/Products/Debug-iphonesimulator/RCT-Folly/libRCT-Folly.a(Conv.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

1.react-native: 0.64
2.xcode :12.5.1
3.React :17

PodFile look like 

platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

def flipper_pods()
  flipperkit_version = '0.90.0'
  pod 'FlipperKit', '~>' + flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  file_name = Dir.glob("*.xcodeproj")[0]
  app_project = Xcodeproj::Project.open(file_name)
  app_project.native_targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
      unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
        puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
        cflags << '-DFB_SONARKIT_ENABLED=1'
      end
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
    app_project.save
  end
  installer.pods_project.save
end

target 'Example' do
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React-perflogger', :path => '../node_modules/react-native/ReactCommon/reactperflogger'
  pod 'React-runtimeexecutor', :path => '../node_modules/react-native/ReactCommon/runtimeexecutor'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
  pod 'Google-Mobile-Ads-SDK'
  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"

  flipper_pods()
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # use_flipper!({ 'Flipper' => '0.90.0', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' }) 
   post_install do |installer|
   flipper_post_install(installer)
  end
  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

**Comment by marcosrdz** [comment]
Getting the same with RN 0.65

**Comment by wjaykim** [comment]
For me, `use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })` in Podfile fixed this.

**Comment by hahtml** [comment]
Same here

**Comment by akinncar** [comment]
Still having this error with React Native 0.66.1

> For me, `use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })` in Podfile fixed this.

This solves here
```sh
Installing Flipper-DoubleConversion 1.1.7 (was 3.1.7)
```

**Comment by jefawks3** [comment]
After upgrading XCode & RN I got the same error. I'm not sure if my project settings are different than @fiznool which is why I'm getting an error and not a warning, but @wjaykim fix worked for me as well.

React 17.0.2
React-Native 0.66.3
XCode 13.1

**Comment by tscharke** [comment]
Get the same error with React-Native **0.66.3** and the tipp…

> For me, `use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })` in Podfile fixed this.

from @wjaykim solved it.
😎🙏

**Comment by douglasjunior** [comment]
I don't understand why the Flipper version and its dependencies are not fixed inside React Native.

Every RN update has some conflict in Flipper libraries that require several hours of research to resolve. 

Sorry for the outburst.

**Comment by mikehardy** [comment]
Apparently altering DEAD_CODE_STRIPPING setting (to either remove a 'NO' setting from pbxproj.proj, or add a 'YES' value for this setting) will resolve this. Experimental results from people that test this would be welcome.

https://stackoverflow.com/a/69565059/9910298

**Comment by alfonsojbro** [comment]
> Apparently altering DEAD_CODE_STRIPPING setting (to either remove a 'NO' setting from pbxproj.proj, or add a 'YES' value for this setting) will resolve this. Experimental results from people that test this would be welcome.
> 
> https://stackoverflow.com/a/69565059/9910298

Worked for me! Thanks

**Comment by chrisheninger** [comment]
> Apparently altering DEAD_CODE_STRIPPING setting (to either remove a 'NO' setting from pbxproj.proj, or add a 'YES' value for this setting) will resolve this. Experimental results from people that test this would be welcome.

Setting the debug value to "YES" resolved this issue for me.

<img width="497" alt="Screen Shot 2022-06-04 at 9 41 17 AM" src="https://user-images.githubusercontent.com/5051745/172016938-d613390a-f925-4f7d-a16a-27dc6636fd9b.png">

Thanks @mikehardy – you're in a bunch of the troubleshooting threads I come across and you seem to always have the answer along with an explanation. Much appreciated as always! 🙇

**Comment by mikehardy** [comment]
@chrisheninger turns out maintaining a bunch of popular repos is less about adding features and more about just figuring out compile errors for everyone - an unexpected result but that explains my presence in all the compile errors threads. Wish I could generate the fixes in non-regressive-for-other-cases ways and get people to upgrade to the versions with fixes though. Mostly these days all the compile issues are sorted out but some people are on old versions or we don't have an upstream fix we're 100% sure on yet. Bit by bit we get it working though...

**Comment by nialldbarber** [comment]
Has anyone that has either **a)** removed `DEAD_CODE_STRIPPING = NO;` or **b)** changed the value to `YES` noticed any implications from this? I can't quite figure out what it does (although, judging from the name I can take a guess! 😄). But removing it seems to work.

**Comment by mikehardy** [comment]
I have not heard any negatives of setting it to NO but there is of course the direct negative implication that your final .ipa will be larger.

Negative of not specifying the flag or setting it to YES is that you cannot even compile for macCatalyst+Flipper, so it's a hard stop on developing. Other use cases in this thread indicate there may be other situations it leads to build-time link failure.

I just attempted to read through known literature on the subject and it turns out there is a sub-flag that *may* work for those affected. What is it?

It's turning DEAD_CODE_STRIPPING to YES (which previously would crash macCatalyst + Flipper builds, at least) but then turn [PRESERVE_DEAD_CODE_INITS_AND_TERMS](https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW5) to YES (normally it would default to NO).

Maybe that allows things to still work but diminishes the size impact of not even attempting to determine dead code and strip it at link time. Unknown, test results would be needed.

**Comment by ibobo** [comment]
> It's turning DEAD_CODE_STRIPPING to YES (which previously would crash macCatalyst + Flipper builds, at least) but then turn [PRESERVE_DEAD_CODE_INITS_AND_TERMS](https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW5) to YES (normally it would default to NO).

It seems this doesn't work, I get an error saying:
`ld: option -no_dead_strip_inits_and_terms is obsolete and being ignored`
and then all the `duplicate symbol` errors.

**Comment by ibobo** [comment]
Never mind... I had a different issue that prevented the build from working.

**Comment by Azaz0723** [comment]
> > Apparently altering DEAD_CODE_STRIPPING setting (to either remove a 'NO' setting from pbxproj.proj, or add a 'YES' value for this setting) will resolve this. Experimental results from people that test this would be welcome.
> 
> Setting the debug value to "YES" resolved this issue for me.
> 
> <img alt="Screen Shot 2022-06-04 at 9 41 17 AM" width="497" src="https://user-images.githubusercontent.com/5051745/172016938-d613390a-f925-4f7d-a16a-27dc6636fd9b.png">
> 
> Thanks @mikehardy – you're in a bunch of the troubleshooting threads I come across and you seem to always have the answer along with an explanation. Much appreciated as always! 🙇

 in my case its previously yes selected but still I am facing same issue

**Comment by akashkrshukla** [comment]
None of this working for me. Xcode 14 and react-native 0.68

**Comment by brianangulo** [comment]
> For me, `use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })` in Podfile fixed this.

In my case: `use_flipper!({'Flipper' => '0.140.0', "Flipper-DoubleConversion" => "1.1.7"})`

Okay so this worked on my end with RN 0.67.5 but it is a bit of a hack IMO. Does anyone know what the underlying cause is for this? I suspect it could be related to past RN upgrades done incorrectly as our app came from 0.59 to 0.63 to 0.67.

**Comment by mikehardy** [comment]
At this point even discussing Flipper implies you're two major versions behind here and failing steadily further back as it doesn't work with use_frameworks. I don't see Flipper prioritized for fixing yet (fixing new architecture + use_frameworks is a higher priority for react-native crew) so I'd say it's probably time to device a different troubleshooting strategy, disable flipper and get on current versions. But that's me....

**Comment by brianangulo** [comment]
> At this point even discussing Flipper implies you're two major versions behind here and failing steadily further back as it doesn't work with use_frameworks. I don't see Flipper prioritized for fixing yet (fixing new architecture + use_frameworks is a higher priority for react-native crew) so I'd say it's probably time to device a different troubleshooting strategy, disable flipper and get on current versions. But that's me....

Thanks @mikehardy, I see your point. We are trying to catch up as fast as we can. Regarding this issue, I've been digging into it a bit more and although I don't have full clarity just yet I did find that selecting `Yes` for both `Dead Code Stripping` and `Don't Dead-Strip Inits and Terms` also works in my case without the need to explicitly select a `Flipper-DoubleConversion` version.

<img width="389" alt="Screen Shot 2022-12-01 at 3 44 22 PM" src="https://user-images.githubusercontent.com/59832188/205165875-f4f40c33-17bc-4681-a53d-76d050a8eafb.png">

**Comment by kamatsuoka** [comment]
I was having this problem on an m1 mac, so the symbols are for arm64, but I think the solution might be the same. After spending a few hours trying out different solutions to this, I solved this by removing `/opt/homebrew/opt/coreutils/libexec/gnubin/` from my path. That's right, I had `gnu coreutils` set as my default for commands like `cp`, which react-native's build scripts use. The net result was that extra files were being copied, due to subtle differences in how directories are copied between the gnu and the builtin `cp`.

**Comment by leoslf** [comment]
> I was having this problem on an m1 mac, so the symbols are for arm64, but I think the solution might be the same. After spending a few hours trying out different solutions to this, I solved this by removing `/opt/homebrew/opt/coreutils/libexec/gnubin/` from my path. That's right, I had `gnu coreutils` set as my default for commands like `cp`, which react-native's build scripts use. The net result was that extra files were being copied, due to subtle differences in how directories are copied between the gnu and the builtin `cp`.


This saved my life, thanks a lot!


### Quickfix

For those who encounter the same problem, this is a hack to exclude the `gnu coreutils` from your `$PATH` without actually removing it from your `~/.bash_profile`.

#### Option 1: wrapping npx react-native calls into a wrapper for now
```bash
# react-native-wrapper
#!/usr/bin/env bash
PATH="$(echo "$PATH" | tr ':' '\n' | grep -v 'coreutils/libexec/gnubin' | paste -sd:)" npx react-native "$@"
```

#### Option 2: just remember to exclude it before calling any ios related commands
```bash
# *before* calling any ios related commands
export PATH="$(echo "$PATH" | tr ':' '\n' | grep -v 'coreutils/libexec/gnubin' | paste -sd:)"
# otherwise you might have to somehow delete the ~/Library/Developer/Xcode/DerivedData and/or ios/build and start over (the goal is to clean up the object files and the statically linked libraries)
```

----

As it appears to work if we exclude the `gnu coreutils`, one possible fix for the problem would be using POSIX-compliant options of the coreutils.

**Comment by NoodleOfDeath** [comment]
> For me, `use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })` in Podfile fixed this.

just put it anywhere?

**Comment by alexeystrakh** [comment]
I have this in my pod already
```
use_flipper!({ 'Flipper' => '0.125.0' }, configurations: ['Debug'])
```

and adding another line like this:
```
use_flipper!({ 'Flipper' => '0.125.0' }, configurations: ['Debug'])
use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
```

breaks the pod installation process:
```
[!] CocoaPods could not find compatible versions for pod "Flipper-DoubleConversion":
  In Podfile:
    Flipper-DoubleConversion (= 1.1.7)

    Flipper-DoubleConversion (= 3.2.0)

None of your spec sources contain a spec satisfying the dependencies: `Flipper-DoubleConversion (= 3.2.0), Flipper-DoubleConversion (= 1.1.7)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

[!] There are duplicate dependencies on `Flipper-DoubleConversion` in `Podfile`:

- Flipper-DoubleConversion (= 3.2.0)
- Flipper-DoubleConversion (= 1.1.7)
```

Is there a way to merge these two `use_flipper!` instructions?

**Comment by nikolasvasconcelos** [comment]
> I have this in my pod already
> 
> ```
> use_flipper!({ 'Flipper' => '0.125.0' }, configurations: ['Debug'])
> ```
> 
> and adding another line like this:
> 
> ```
> use_flipper!({ 'Flipper' => '0.125.0' }, configurations: ['Debug'])
> use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
> ```
> 
> breaks the pod installation process:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "Flipper-DoubleConversion":
>   In Podfile:
>     Flipper-DoubleConversion (= 1.1.7)
> 
>     Flipper-DoubleConversion (= 3.2.0)
> 
> None of your spec sources contain a spec satisfying the dependencies: `Flipper-DoubleConversion (= 3.2.0), Flipper-DoubleConversion (= 1.1.7)`.
> 
> You have either:
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> [!] There are duplicate dependencies on `Flipper-DoubleConversion` in `Podfile`:
> 
> - Flipper-DoubleConversion (= 3.2.0)
> - Flipper-DoubleConversion (= 1.1.7)
> ```
> 
> Is there a way to merge these two `use_flipper!` instructions?

yes, I believe you can use use_flipper!({ 'Flipper' => '0.125.0' , "Flipper-DoubleConversion" => "1.1.7"},  configurations: ['Debug']) to merge them

**Comment by furby-tm** [comment]
Best solution here is to delete React Native and with it; your entire existing app. Switch to a competent framework, such as:

* [SwiftUI](https://developer.apple.com/documentation/swiftui) for iOS
* [Jetpack Compose](https://developer.android.com/jetpack/compose) for Android

These frameworks are comprehensive, maintained by competent developers, and future proof - which is far more than I can say for the mess in which React Native has turned itself into, it's:

Consistent usage on deprecated frameworks such as UIKit (Apple has long-since shifted their focus onwards to SwiftUI)

Horrendously written code, an actual example:
https://github.com/facebook/react-native/blob/a6690bfb7b43120608ef17d1e7f08c9eb111e98f/packages/react-native/React/Fabric/RCTSurfacePresenter.mm#L186-L191

Duplicate symbols as you find in this issue ticket today.

Autogenerated garbage C++ code they call ✨ "Native" ✨ "turbo modules" and "new architecture" which are just marketing buzzwords they throw around for some pretty horrendous looking C++ code that is not maintainable by humans and is subject to all sorts of delightful compiler errors (`..."window" is not available in this iOS version...`) that you will have no control of fixing yourself because the build forces autogenerated junk at build time.

Senseless hours wasting your time trying to fix all the things Meta/Facebook (will not/cannot) fix.

To have a barely functioning app, built on a foundation of deprecated UI frameworks which will inevitably become obsolete in an upcoming flagship release, rendering all your efforts here as useless.

I don't know what happened here, but for the sake of developer sanity and everyone involved, it's time to let this project go. I hope Meta/Facebook can take this as a learning oppurtunity moving forward.

**Comment by arancauchi** [comment]
> Best solution here is to delete React Native and with it; your entire existing app. 

This issue isn't your personal soapbox.

**Comment by MuhammadAbdullah54321** [comment]
I am facing the same issues with react-native version 0.71.3

**Comment by jhjdev** [comment]
Experienced the same issue when adding Expo to an existing React Native project.
RN version: 0.72.4

The solution proposed by @wjaykim worked like a charm!

**Comment by vidurajith-darshana** [comment]
experienced the same issue. it happened due to the `@react-native-community/viewpager` fix the issue by replacing it with latest `react-native-pager-view`

**Comment by saad277** [comment]
@vidurajith-darshana saved my day ! spent like 6 hours and could not figure it out

**Comment by itzyashh** [comment]
> > For me, `use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })` in Podfile fixed this.
> 
> just put it anywhere?

Put this above target {projectname} do

**Comment by budiadiono** [comment]
I have similar issue after installing react-native-gesture-handler and following by react-native-reanimated.

![image](https://github.com/facebook/react-native/assets/796331/472b1bcb-b301-4a3c-8ad2-2f60be0606de)

I can't use `..use_flipper!(..` solution since I disabled the flipper, so I ended up with:

1. Under ios folder:
```
pod deintegrate
RCT_NEW_ARCH_ENABLED=1 pod install
```
2. Open workspace with xcode and do "Clean Build Folder"
3. Delete derived data: `rm -rf Library/Developer/Xcode/DerivedData`
4. Build project using XCode.

 And the errors gone, I can run the project normally.

**Comment by alimurad-1** [comment]
> I am facing the same issues with react-native version 0.71.3
> 
> Update: If you're encountering a similar issue of duplicate symbols .... I discovered that my problem stemmed from having both `rn-fetch-blob` and `react-native-blob-util` installed. These packages essentially serve the same purpose, so installing both is unnecessary. Opt for just one of them. I recommend using `react-native-blob-util`.

after two hours of debugging, I just had to do this. Thanks for saving my weekend. please let me know how did you find out the exact issue, the errors Xcode showed weren't helpful at all

**Comment by enzzoperez** [comment]
It happened to me when I installed aws-amplify and I had to run the command `npx pod-install` in the root of project, run `pod install` in ios folder doesnt worked for me

**Comment by djguruwap** [comment]
@mikehardy Thank you very much. You are life saver.

God bless you !!

**Comment by niki-bri** [comment]
After updating to react-native 0.76.2 and expo 52 I am facing the same issue.

This is the error message: 
[RUN_FASTLANE] ⚠️  ld: ignoring duplicate libraries: '-lc++'
[RUN_FASTLANE] ❌  duplicate symbol 'facebook::react::NativeCompressorSpecJSI::NativeCompressorSpecJSI(facebook::react::ObjCTurboModule::InitParams const&)' in
┌─ libReactCodegen.a[55](RNVideoCompressorSpec-generated.o)
└─ libReactCodegen.a[37](RNCompressorSpec-generated.o)

[RUN_FASTLANE] ❌  duplicate symbol '_OBJC_METACLASS_$_NativeCompressorSpecBase' in
┌─ libReactCodegen.a[55](RNVideoCompressorSpec-generated.o)
└─ libReactCodegen.a[37](RNCompressorSpec-generated.o)

[RUN_FASTLANE] ❌  duplicate symbol '_OBJC_CLASS_$_NativeCompressorSpecBase' in
┌─ libReactCodegen.a[55](RNVideoCompressorSpec-generated.o)
└─ libReactCodegen.a[37](RNCompressorSpec-generated.o)

[RUN_FASTLANE] ❌  duplicate symbol 'facebook::react::NativeCompressorSpecJSI::NativeCompressorSpecJSI(facebook::react::ObjCTurboModule::InitParams const&)' in
┌─ libReactCodegen.a[55](RNVideoCompressorSpec-generated.o)
└─ libReactCodegen.a[37](RNCompressorSpec-generated.o)

[RUN_FASTLANE] ❌  duplicate symbol '_OBJC_IVAR_$_NativeCompressorSpecBase._eventEmitterCallback' in
┌─ libReactCodegen.a[55](RNVideoCompressorSpec-generated.o)
└─ libReactCodegen.a[37](RNCompressorSpec-generated.o)

[RUN_FASTLANE] 
❌  ld: 5 duplicate symbols

So far, I could not solve the error using any fixes suggested here. Any help is greatly appreciated!
Thanks.

**Comment by niki-bri** [comment]
I am using react-native-compressor 1.9.0 but not react-native-video-compressor in my project so I am not sure why react-native-video compressor is even included?

**Comment by niki-bri** [comment]
@mikehardy  I am sorry for any confusion I caused. I just found the appropriate issue in the react-native-compressor directory. Thanks for your quick answer though.
