### ISSUE TITLE
RN new arch library not working with apps having RN 0.70 or below

### ISSUE THREAD

**Issue by Anush-Shand** [facebook/react-native#46258]
### Description

`JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clevertap/react/NativeCleverTapModuleSpec;`

Pertaining to this [library](https://github.com/CleverTap/clevertap-react-native/pull/396) and this [pr in particular](https://github.com/CleverTap/clevertap-react-native/pull/396) when integrating into an app with RN 0.71+ things work smoothly but I run into the above error when integrating into an app with RN 0.70-

### Steps to reproduce

1. Integrate the library on a raw app with RN 0.70-
2. App crashes on launch with below logs

### React Native Version

0.73.0

### Affected Platforms

Runtime - Android

### Areas

JSI - Javascript Interface

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 80.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.2.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2024.1 AI-241.18034.62.2411.12169540
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
java_vm_ext.cc:591] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clevertap/react/NativeCleverTapModuleSpec;
                                                                                                    java_vm_ext.cc:591]   at java.util.ArrayList com.facebook.react.PackageList.getPackages() (PackageList.java:59)
                                                                                                    java_vm_ext.cc:591]   at java.util.List com.oldproject4.newarchitecture.MainApplicationReactNativeHost.getPackages() (MainApplicationReactNativeHost.java:47)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.createReactInstanceManager() (ReactNativeHost.java:86)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.getReactInstanceManager() (ReactNativeHost.java:42)
                                                                                                    java_vm_ext.cc:591]   at void com.oldproject4.MainApplication.onCreate() (MainApplication.java:63)
                                                                                                    java_vm_ext.cc:591]   at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1316)
                                                                                                    java_vm_ext.cc:591]   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:6998)
                                                                                                    java_vm_ext.cc:591]   at void android.app.ActivityThread.-$$Nest$mhandleBindApplication(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
                                                                                                    java_vm_ext.cc:591]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2236)
                                                                                                    java_vm_ext.cc:591]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
                                                                                                    java_vm_ext.cc:591]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
                                                                                                    java_vm_ext.cc:591]   at void android.os.Looper.loop() (Looper.java:294)
                                                                                                    java_vm_ext.cc:591]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8177)
                                                                                                    java_vm_ext.cc:591]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
                                                                                                    java_vm_ext.cc:591]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:552)
                                                                                                    java_vm_ext.cc:591]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:971)
                                                                                                    java_vm_ext.cc:591] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.react.NativeCleverTapModuleSpec" on path: DexPathList[[zip file "/data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/lib/arm64, /data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    java_vm_ext.cc:591]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:259)
                                                                                                    java_vm_ext.cc:591]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
                                                                                                    java_vm_ext.cc:591]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
                                                                                                    java_vm_ext.cc:591]   at java.util.ArrayList com.facebook.react.PackageList.getPackages() (PackageList.java:59)
                                                                                                    java_vm_ext.cc:591]   at java.util.List com.oldproject4.newarchitecture.MainApplicationReactNativeHost.getPackages() (MainApplicationReactNativeHost.java:47)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.createReactInstanceManager() (ReactNativeHost.java:86)
                                                                                                    java_vm_ext.cc:591]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.getReactInstanceManager() (ReactNativeHost.java:42)
                                                                                                    java_vm_ext.cc:591]   at void com.oldproject4.MainApplication.onCreate() (MainApplication.java:63)
                                                                                                    java_vm_ext.cc:591]   at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1316)
2024-08-29 11:37:54.836 11173-11247 com.oldproject4         com.oldproject4                      A  runtime.cc:691]   native: #122 pc 0050a2f8  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+1648) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #123 pc 003797d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #124 pc 000703a8  <anonymous:77b5170000> (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run)
                                                                                                    runtime.cc:691]   native: #125 pc 0037cde0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute +356) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #126 pc 0049120c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>+4152) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #127 pc 0050aca4  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+4124) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #128 pc 003797d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #129 pc 0010ee0c  /apex/com.android.art/javalib/core-oj.jar (java.lang.Thread.run)
                                                                                                    runtime.cc:691]   native: #130 pc 0037cde0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute +356) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #131 pc 0037c560  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+672) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #132 pc 00377168  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #133 pc 003605a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #134 pc 0034b8a4  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke+144) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #135 pc 004f3e30  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback+1888) (BuildId: b10f5696fea1b32039b162aef3850ed3)
                                                                                                    runtime.cc:691]   native: #136 pc 000cb6a8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208) (BuildId: a87908b48b368e6282bcc9f34bcfc28c)
                                                                                                    runtime.cc:691]   native: #137 pc 0006821c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: a87908b48b368e6282bcc9f34bcfc28c)
                                                                                                    runtime.cc:691]   at com.facebook.jni.NativeRunnable.run(Native method)
                                                                                                    runtime.cc:691]   at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    runtime.cc:691]   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    runtime.cc:691]   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    runtime.cc:691]   at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    runtime.cc:691]   at android.os.Looper.loop(Looper.java:294)
                                                                                                    runtime.cc:691]   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    runtime.cc:691]   at java.lang.Thread.run(Thread.java:1012)
                                                                                                    runtime.cc:691] Pending exception java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clevertap/react/NativeCleverTapModuleSpec;
                                                                                                    runtime.cc:691]   at java.util.ArrayList com.facebook.react.PackageList.getPackages() (PackageList.java:59)
                                                                                                    runtime.cc:691]   at java.util.List com.oldproject4.newarchitecture.MainApplicationReactNativeHost.getPackages() (MainApplicationReactNativeHost.java:47)
                                                                                                    runtime.cc:691]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.createReactInstanceManager() (ReactNativeHost.java:86)
                                                                                                    runtime.cc:691]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.getReactInstanceManager() (ReactNativeHost.java:42)
                                                                                                    runtime.cc:691]   at void com.oldproject4.MainApplication.onCreate() (MainApplication.java:63)
2024-08-29 11:37:54.836 11173-11247 com.oldproject4         com.oldproject4                      A  runtime.cc:691]   at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1316)
                                                                                                    runtime.cc:691]   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:6998)
                                                                                                    runtime.cc:691]   at void android.app.ActivityThread.-$$Nest$mhandleBindApplication(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
                                                                                                    runtime.cc:691]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2236)
                                                                                                    runtime.cc:691]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
                                                                                                    runtime.cc:691]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
                                                                                                    runtime.cc:691]   at void android.os.Looper.loop() (Looper.java:294)
                                                                                                    runtime.cc:691]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8177)
                                                                                                    runtime.cc:691]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
                                                                                                    runtime.cc:691]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:552)
                                                                                                    runtime.cc:691]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:971)
                                                                                                    runtime.cc:691] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.react.NativeCleverTapModuleSpec" on path: DexPathList[[zip file "/data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/lib/arm64, /data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    runtime.cc:691]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:259)
                                                                                                    runtime.cc:691]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
                                                                                                    runtime.cc:691]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
                                                                                                    runtime.cc:691]   at java.util.ArrayList com.facebook.react.PackageList.getPackages() (PackageList.java:59)
                                                                                                    runtime.cc:691]   at java.util.List com.oldproject4.newarchitecture.MainApplicationReactNativeHost.getPackages() (MainApplicationReactNativeHost.java:47)
                                                                                                    runtime.cc:691]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.createReactInstanceManager() (ReactNativeHost.java:86)
                                                                                                    runtime.cc:691]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.getReactInstanceManager() (ReactNativeHost.java:42)
                                                                                                    runtime.cc:691]   at void com.oldproject4.MainApplication.onCreate() (MainApplication.java:63)
                                                                                                    runtime.cc:691]   at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1316)
                                                                                                    runtime.cc:691]   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:6998)
                                                                                                    runtime.cc:691]   at void android.app.ActivityThread.-$$Nest$mhandleBindApplication(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
                                                                                                    runtime.cc:691]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2236)
                                                                                                    runtime.cc:691]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
                                                                                                    runtime.cc:691]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
                                                                                                    runtime.cc:691]   at void android.os.Looper.loop() (Looper.java:294)
                                                                                                    runtime.cc:691]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8177)
                                                                                                    runtime.cc:691]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
                                                                                                    runtime.cc:691]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:552)
2024-08-29 11:37:54.836 11173-11247 com.oldproject4         com.oldproject4                      A  runtime.cc:699] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clevertap/react/NativeCleverTapModuleSpec;
                                                                                                    runtime.cc:699]   at java.util.ArrayList com.facebook.react.PackageList.getPackages() (PackageList.java:59)
                                                                                                    runtime.cc:699]   at java.util.List com.oldproject4.newarchitecture.MainApplicationReactNativeHost.getPackages() (MainApplicationReactNativeHost.java:47)
                                                                                                    runtime.cc:699]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.createReactInstanceManager() (ReactNativeHost.java:86)
                                                                                                    runtime.cc:699]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.getReactInstanceManager() (ReactNativeHost.java:42)
                                                                                                    runtime.cc:699]   at void com.oldproject4.MainApplication.onCreate() (MainApplication.java:63)
                                                                                                    runtime.cc:699]   at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1316)
                                                                                                    runtime.cc:699]   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:6998)
                                                                                                    runtime.cc:699]   at void android.app.ActivityThread.-$$Nest$mhandleBindApplication(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
                                                                                                    runtime.cc:699]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2236)
                                                                                                    runtime.cc:699]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
                                                                                                    runtime.cc:699]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
                                                                                                    runtime.cc:699]   at void android.os.Looper.loop() (Looper.java:294)
                                                                                                    runtime.cc:699]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8177)
                                                                                                    runtime.cc:699]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
                                                                                                    runtime.cc:699]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:552)
                                                                                                    runtime.cc:699]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:971)
                                                                                                    runtime.cc:699] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.react.NativeCleverTapModuleSpec" on path: DexPathList[[zip file "/data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/lib/arm64, /data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    runtime.cc:699]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:259)
                                                                                                    runtime.cc:699]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
                                                                                                    runtime.cc:699]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
                                                                                                    runtime.cc:699]   at java.util.ArrayList com.facebook.react.PackageList.getPackages() (PackageList.java:59)
                                                                                                    runtime.cc:699]   at java.util.List com.oldproject4.newarchitecture.MainApplicationReactNativeHost.getPackages() (MainApplicationReactNativeHost.java:47)
                                                                                                    runtime.cc:699]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.createReactInstanceManager() (ReactNativeHost.java:86)
                                                                                                    runtime.cc:699]   at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.getReactInstanceManager() (ReactNativeHost.java:42)
                                                                                                    runtime.cc:699]   at void com.oldproject4.MainApplication.onCreate() (MainApplication.java:63)
                                                                                                    runtime.cc:699]   at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1316)
                                                                                                    runtime.cc:699]   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:6998)
2024-08-29 11:37:55.192 11275-11275 DEBUG                   pid-11275                            A  Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clevertap/react/NativeCleverTapModuleSpec; (Ask Gemini)
                                                                                                      at java.util.ArrayList com.facebook.react.PackageList.getPackages() (PackageList.java:59)
                                                                                                      at java.util.List com.oldproject4.newarchitecture.MainApplicationReactNativeHost.getPackages() (MainApplicationReactNativeHost.java:47)
                                                                                                      at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.createReactInstanceManager() (ReactNativeHost.java:86)
                                                                                                      at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.getReactInstanceManager() (ReactNativeHost.java:42)
                                                                                                      at void com.oldproject4.MainApplication.onCreate() (MainApplication.java:63)
                                                                                                      at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1316)
                                                                                                      at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:6998)
                                                                                                      at void android.app.ActivityThread.-$$Nest$mhandleBindApplication(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
                                                                                                      at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2236)
                                                                                                      at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
                                                                                                      at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
                                                                                                      at void android.os.Looper.loop() (Looper.java:294)
                                                                                                      at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8177)
                                                                                                      at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
                                                                                                      at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:552)
                                                                                                      at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.react.NativeCleverTapModuleSpec" on path: DexPathList[[zip file "/data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/lib/arm64, /data/app/~~NDE_A__qzSq7_G-1Hx5Uxw==/com.oldproject4-nGXGHbEbFnO1wY6K6DCfAQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                      at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:259)
                                                                                                      at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
                                                                                                      at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
                                                                                                      at java.util.ArrayList com.facebook.react.PackageList.getPackages() (PackageList.java:59)
                                                                                                      at java.util.List com.oldproject4.newarchitecture.MainApplicationReactNativeHost.getPackages() (MainApplicationReactNativeHost.java:47)
                                                                                                      at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.createReactInstanceManager() (ReactNativeHost.java:86)
                                                                                                      at com.facebook.react.ReactInstanceManager com.facebook.react.ReactNativeHost.getReactInstanceManager() (ReactNativeHost.java:42)
                                                                                                      at void com.oldproject4.MainApplication.onCreate() (MainApplication.java:63)
                                                                                                      at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1316)
                                                                                                      at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:6998)
                                                                                                      at void android.app.ActivityThread.-$$Nest$mhandleBindApplication(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
                                                                                                      at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2236)
                                                                                                      at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
                                                                                                      at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
                                                                                                      at void android.os.Looper.loop() (Looper.java:294)
```

### Reproducer

https://github.com/CleverTap/clevertap-react-native/pull/396

### Screenshots and Videos

None

**Comment by cipolleschi** [comment]
Hi @Anush-Shand sorry but 0.70 is not supported anymore. Also, we always advise to use the new architecture on the latest version of React Native as it is in Beta so far and we can ensure it working on older versions, although we try our best to backport fixes when it's possible.

For your app on 0.70, I strongly advise to migrate to 0.75.

**Comment by Anush-Shand** [comment]
@cipolleschi Thanks for the prompt response. Things work perfectly fine on the latest versions. (0.71+)
As a library maintainer should I be also adding support for new architecture with react-native 0.70 and below to support a wider audience?
I am currently unable to gauge what change is causing this issue on older builds

**Comment by cipolleschi** [comment]
That's up to you, but given that 0.70 is not supported I would not go that far as we don't have capacity to support those old versions.
Our policy is to support latest -2, so we are currently support 0.73, 0.74 and 0.75. 
The policy for new architecture, so far, is the latest version only, but 0.74 is not that different than 0.75, so most things work for both versions.

I would not push myself below the React Native supported window, tbh
