### ISSUE TITLE
after i update react native 0.64.2 to 0.68.2 than react native every input box hit this error. ERROR TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({

### ISSUE THREAD

**Issue by kaialsh705** [facebook/react-native#33875]
### Description

ERROR TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({
      x: x,
      y: y,
      animated: animated
     })', 'responder.scrollResponderScrollTo' is undefined)\\
     
Please help me with what I do.
     
     

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 11.6.6
    CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
    Memory: 1.04 GB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Click on TextInput multiple times, then hit this error.

**Comment by cipolleschi** [comment]
Hi @kaialsh705. Thanks for reporting the issue. Could you please provide a small repo with the repro of the problem?

**Comment by erickcrus** [comment]
Same here
