### ISSUE TITLE
 Can't build with new architecture on 0.69.5 (error: cannot find symbol reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);

### ISSUE THREAD

**Issue by lordkyle0** [facebook/react-native#34628]
### Description

I get those error when I upgrade to react 0.69.5 with expo sdk 46. I app was fine

error : cannot find symbol if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) { 
symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
location: class BuildConfig

located  /home/expo/workingdir/build/android/app/src/main/java/com/lordisasi/nduleafrik/**MainApplication.java:**62:

/home/expo/workingdir/build/android/app/src/main/java/com/lordisasi/nduleafrik/MainActivity.java:34: error: cannot find symbol
       return reactRootView;
              ^
symbol:   variable reactRootView
 location: class MainActivity
/home/expo/workingdir/build/android/app/src/main/java/com/lordisasi/nduleafrik/MainActivity.java:36: error: method does not override or implement a method from a supertype
 @Override
  ^
**MainApplication.java**
> package com.lordisasi.nduleafrik;
> 
> import android.content.res.Configuration;
> import expo.modules.ApplicationLifecycleDispatcher;
> import expo.modules.ReactNativeHostWrapper;
> 
> import android.app.Application;
> import android.content.Context;
> import android.content.res.Configuration;
> import androidx.annotation.NonNull;
> 
> import com.facebook.react.PackageList;
> import com.facebook.react.ReactApplication;
> import com.reactnativecommunity.picker.RNCPickerPackage;
> import com.reactnativecommunity.picker.RNCPickerPackage;
> import com.reactnativecommunity.picker.RNCPickerPackage;
> import com.facebook.react.ReactInstanceManager;
> import com.facebook.react.BuildConfig;
> import com.facebook.react.ReactNativeHost;
> import com.facebook.react.ReactPackage;
> import com.facebook.react.config.ReactFeatureFlags;
> import com.facebook.soloader.SoLoader;
> import com.lordisasi.nduleafrik.newarchitecture.MainApplicationReactNativeHost;
> 
> import android.content.res.Configuration;
> import expo.modules.ApplicationLifecycleDispatcher;
> import expo.modules.ReactNativeHostWrapper;
> 
> import java.lang.reflect.InvocationTargetException;
> import java.util.List;
> 
> public class MainApplication extends Application implements ReactApplication {
>   private final ReactNativeHost mReactNativeHost = new ReactNativeHostWrapper(
>     this,
>     new ReactNativeHostWrapper(this, new ReactNativeHost(this) {
>     @Override
>     public boolean getUseDeveloperSupport() {
>       return BuildConfig.DEBUG;
>     }
> 
>     @Override
>     protected List<ReactPackage> getPackages() {
>       @SuppressWarnings("UnnecessaryLocalVariable")
>       List<ReactPackage> packages = new PackageList(this).getPackages();
>       // Packages that cannot be autolinked yet can be added manually here, for example:
>       
> 
>       return packages;
>     }
> 
>     @Override
>     protected String getJSMainModuleName() {
>       return "index";
>     }
>   }));
> 
>   private final ReactNativeHost mNewArchitectureNativeHost =
>       new ReactNativeHostWrapper(this, new MainApplicationReactNativeHost(this));
> 
>   @Override
>   public ReactNativeHost getReactNativeHost() {
>     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
>       return mNewArchitectureNativeHost;
>     } else {
>       return mReactNativeHost;
>     }
>   }
> 
>   @Override
>   public void onCreate() {
>     super.onCreate();
>     // If you opted-in for the New Architecture, we enable the TurboModule system
>     ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
>     SoLoader.init(this, /* native exopackage */ false);
> 
>     initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
>     ApplicationLifecycleDispatcher.onApplicationCreate(this);
>   }
> 
>   @Override
>   public void onConfigurationChanged(@NonNull Configuration newConfig) {
>     super.onConfigurationChanged(newConfig);
>     ApplicationLifecycleDispatcher.onConfigurationChanged(this, newConfig);
>   }
> 
>   /**
>    * Loads Flipper in React Native templates. Call this in the onCreate method with something like
>    * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
>    *
>    * @param context
>    * @param reactInstanceManager
>    */
>   private static void initializeFlipper(
>       Context context, ReactInstanceManager reactInstanceManager) {
>     if (BuildConfig.DEBUG) {
>       try {
>         /*
>          We use reflection here to pick up the class that initializes Flipper,
>         since Flipper library is not available in release mode
>         */
>         Class<?> aClass = Class.forName("com.lordisasi.nduleafrik.ReactNativeFlipper");
>         aClass
>             .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
>             .invoke(null, context, reactInstanceManager);
>       } catch (ClassNotFoundException e) {
>         e.printStackTrace();
>       } catch (NoSuchMethodException e) {
>         e.printStackTrace();
>       } catch (IllegalAccessException e) {
>         e.printStackTrace();
>       } catch (InvocationTargetException e) {
>         e.printStackTrace();
>       }
>     }
>   }
> }
> 

**MainActivity.java**

> package com.lordisasi.nduleafrik;
> 
> import android.os.Build;
> import android.os.Bundle;
> 
> import com.facebook.react.ReactActivity;
> import com.facebook.react.ReactActivityDelegate;
> import com.facebook.react.ReactRootView;
> 
> import expo.modules.ReactActivityDelegateWrapper;
> 
> public class MainActivity extends ReactActivity {
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     // Set the theme to AppTheme BEFORE onCreate to support 
>     // coloring the background, status bar, and navigation bar.
>     // This is required for expo-splash-screen.
>     setTheme(R.style.AppTheme);
>     super.onCreate(null);
>   }
> 
>   /**
>    * Returns the name of the main component registered from JavaScript.
>    * This is used to schedule rendering of the component.
>    */
>   @Override
>   protected String getMainComponentName() {
>     return "main";
>   }
> 
>   /**
>    * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
>    * you can specify the renderer you wish to use - the new renderer (Fabric) or the old renderer
>    * (Paper).
>    */
>   @Override
>   protected ReactActivityDelegate createReactActivityDelegate() {  
>       reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
>       return reactRootView;
>     }
>     @Override
>     protected boolean isConcurrentRootEnabled() {
>       // If you opted-in for the New Architecture, we enable Concurrent Root (i.e. React 18).
>       // More on this on https://reactjs.org/blog/2022/03/29/react-v18.html
>       return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
>     }
> 
>   /**
>    * Align the back button behavior with Android S
>    * where moving root activities to background instead of finishing activities.
>    * @see <a href="https://developer.android.com/reference/android/app/Activity#onBackPressed()">onBackPressed</a>
>    */
>   @Override
>   public void invokeDefaultOnBackPressed() {
>     if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.R) {
>       if (!moveTaskToBack(false)) {
>         // For non-root activities, use the default implementation to finish them.
>         super.invokeDefaultOnBackPressed();
>       }
>       return;
>     }
> 
>     // Use the default back button implementation on Android S
>     // because it's doing more than {@link Activity#moveTaskToBack} in fact.
>     super.invokeDefaultOnBackPressed();
>   }
> }
> 

### Version

0.69.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
    Memory: 2.66 GB / 7.90 GB
  Binaries:
    Node: 18.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: Not Found
  Languages:
    Java: 11.0.11
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.5 => 0.69.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.70.0 is now available (your project is running on v0.69.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.5.
info To upgrade, run "react-native upgrade".

### Steps to reproduce

npx expo run:android

### Snack, code example, screenshot, or link to a repository

> Task :app:compileReleaseJavaWithJavac FAILED
D:\ReactNative\Projects\JoTune\UI\NduleAfrik\android\app\src\main\java\com\lordisasi\nduleafrik\MainActivity.java:38: error: cannot find symbol
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      ^
  symbol:   variable reactRootView
  location: class MainActivity
D:\ReactNative\Projects\JoTune\UI\NduleAfrik\android\app\src\main\java\com\lordisasi\nduleafrik\MainActivity.java:39: error: cannot find symbol
      return reactRootView;
             ^
  symbol:   variable reactRootView
  location: class MainActivity
D:\ReactNative\Projects\JoTune\UI\NduleAfrik\android\app\src\main\java\com\lordisasi\nduleafrik\MainActivity.java:41: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\ReactNative\Projects\JoTune\UI\NduleAfrik\android\app\src\main\java\com\lordisasi\nduleafrik\MainApplication.java:62: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
                   ^
  symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
  location: class BuildConfig
D:\ReactNative\Projects\JoTune\UI\NduleAfrik\android\app\src\main\java\com\lordisasi\nduleafrik\MainApplication.java:62: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
D:\ReactNative\Projects\JoTune\UI\NduleAfrik\android\app\src\main\java\com\lordisasi\nduleafrik\MainApplication.java:73: error: cannot find symbol
    ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
                                                   ^
  symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
  location: class BuildConfig
6 errors
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build failed with an exception

**Comment by cortinico** [comment]
> IS_NEW_ARCHITECTURE_ENABLED

This usually happens if you forgot to update your `build.gradle`. You're probably missing this line:

https://github.com/facebook/react-native/blob/49c90f7a7ee1290bc694184873bdc0e06318ba98/template/android/app/build.gradle#L143

**Comment by Mmferry** [comment]
I upgraded to version 0.69.6 but i got build faild 

`> Task :app:compileReleaseJavaWithJavac
D:\Work\data-extraction-mobile-app\android\app\src\main\java\com\red\sa\dataextraction\MainApplication.java:59: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
                   ^
  symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
  location: class BuildConfig
D:\Work\data-extraction-mobile-app\android\app\src\main\java\com\red\sa\dataextraction\MainApplication.java:59: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
D:\Work\data-extraction-mobile-app\android\app\src\main\java\com\red\sa\dataextraction\MainApplication.java:60: error: cannot find symbol
      return mNewArchitectureNativeHost;
             ^
  symbol:   variable mNewArchitectureNativeHost
  location: class MainApplication
D:\Work\data-extraction-mobile-app\android\app\src\main\java\com\red\sa\dataextraction\MainApplication.java:70: error: cannot find symbol
    ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
                                                   ^
  symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
  location: class BuildConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

> Task :app:compileReleaseJavaWithJavac FAILED`

**Comment by jeetvani** [comment]
Change to React Native Version

Main Activitty .java

`package packageName;

import android.os.Build;
import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactActivityDelegate;

import expo.modules.ReactActivityDelegateWrapper;

public class MainActivity extends ReactActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    // Set the theme to AppTheme BEFORE onCreate to support 
    // coloring the background, status bar, and navigation bar.
    // This is required for expo-splash-screen.
    setTheme(R.style.AppTheme);
    super.onCreate(null);
  }

  /**
   * Returns the name of the main component registered from JavaScript.
   * This is used to schedule rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "main";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. Here we use a util class {@link
   * DefaultReactActivityDelegate} which allows you to easily enable Fabric and Concurrent React
   * (aka React 18) with two boolean flags.
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
        this,
        getMainComponentName(),
        // If you opted-in for the New Architecture, we enable the Fabric Renderer.
        DefaultNewArchitectureEntryPoint.getFabricEnabled()));
  }

  /**
   * Align the back button behavior with Android S
   * where moving root activities to background instead of finishing activities.
   * @see <a href="https://developer.android.com/reference/android/app/Activity#onBackPressed()">onBackPressed</a>
   */
  @Override
  public void invokeDefaultOnBackPressed() {
    if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.R) {
      if (!moveTaskToBack(false)) {
        // For non-root activities, use the default implementation to finish them.
        super.invokeDefaultOnBackPressed();
      }
      return;
    }

    // Use the default back button implementation on Android S
    // because it's doing more than {@link Activity#moveTaskToBack} in fact.
    super.invokeDefaultOnBackPressed();
  }
}`


Main Application.java 

`
package yourpackagename;

import android.app.Application;
import android.content.res.Configuration;
import androidx.annotation.NonNull;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.config.ReactFeatureFlags;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactNativeHost;
import com.facebook.soloader.SoLoader;

import expo.modules.ApplicationLifecycleDispatcher;
import expo.modules.ReactNativeHostWrapper;

// import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
// import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
    new ReactNativeHostWrapper(this, new DefaultReactNativeHost(this) {
      @Override
      public boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
      }

      @Override
      protected List<ReactPackage> getPackages() {
        @SuppressWarnings("UnnecessaryLocalVariable")
        List<ReactPackage> packages = new PackageList(this).getPackages();
        // Packages that cannot be autolinked yet can be added manually here, for example:
        // packages.add(new MyReactNativePackage());
        // packages.add(new RNFirebaseMessagingPackage());
        // packages.add(new RNFirebaseNotificationsPackage());
        return packages;
      }

      @Override
      protected String getJSMainModuleName() {
        return ".expo/.virtual-metro-entry";
      }

      @Override
      protected boolean isNewArchEnabled() {
        return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
      }

      @Override
      protected Boolean isHermesEnabled() {
        return BuildConfig.IS_HERMES_ENABLED;
      }
  });

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    if (!BuildConfig.REACT_NATIVE_UNSTABLE_USE_RUNTIME_SCHEDULER_ALWAYS) {
      ReactFeatureFlags.unstable_useRuntimeSchedulerAlways = false;
    }
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      DefaultNewArchitectureEntryPoint.load();
    }
    ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    ApplicationLifecycleDispatcher.onApplicationCreate(this);
  }

  @Override
  public void onConfigurationChanged(@NonNull Configuration newConfig) {
    super.onConfigurationChanged(newConfig);
    ApplicationLifecycleDispatcher.onConfigurationChanged(this, newConfig);
  }
}
`


Works For Me !!!!
