### PR TITLE
Don't strip NativeRunnable constructor. Fixes #6624

### LINKED ISSUE #6624: Android release build with proguard enabled throws exception at start
I get following exception on my release APK with proguard enabled after upgrading RN to 0.22.+. Disabling proguard solves the issue.

```
java.lang.NoSuchMethodError: no non-static method "Lcom/facebook/react/bridge/queue/NativeRunnable;.<init>(Lcom/facebook/jni/HybridData;)V"
   at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
   at com.facebook.react.bridge.CatalystInstanceImpl.callFunction(CatalystInstanceImpl.java:189)
   at com.facebook.react.bridge.JavaScriptModuleRegistry$JavaScriptModuleInvocationHandler.invoke(JavaScriptModuleRegistry.java:97)
   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
   at $Proxy5.emit(Unknown Source)
   at com.facebook.react.modules.appstate.AppStateModule.sendAppStateChangeEvent(AppStateModule.java:73)
   at com.facebook.react.modules.appstate.AppStateModule.onHostResume(AppStateModule.java:51)
   at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:147)
   at com.facebook.react.ReactInstanceManagerImpl.moveToResumedLifecycleState(ReactInstanceManagerImpl.java:559)
   at com.facebook.react.ReactInstanceManagerImpl.moveReactContextToCurrentLifecycleState(ReactInstanceManagerImpl.java:904)
   at com.facebook.react.ReactInstanceManagerImpl.setupReactContext(ReactInstanceManagerImpl.java:728)
   at com.facebook.react.ReactInstanceManagerImpl.access$800(ReactInstanceManagerImpl.java:104)
   at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:210)
   at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:183)
   at android.os.AsyncTask.finish(AsyncTask.java:636)
   at android.os.AsyncTask.access$500(AsyncTask.java:177)
   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5254)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

### PR DESCRIPTION
**Pull request by dgladkov**
Fixes proguard in RN 0.22.+. Closes #6624

### CODE REVIEW

**Comment by satya164** [comment]
Awesome. Thanks a lot for the PR.

**Comment by satya164** [comment]
@facebook-github-bot shipit
