### ISSUE TITLE
Promise.allSettled is still undefined in 0.70.6 on iOS and Android with Hermes

### ISSUE THREAD

**Issue by Elolawyn** [facebook/react-native#35363]
### Description

Promise.allSettled is still undefined on iOS and Android with Hermes when you have installed both latests versions of react native and expo (on a bare react native project).

It seems to work fine when executing tests with jest, however.

```bash
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "promise"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "promise@8.3.0"
info Reasons this module exists
   - "react-native" depends on it
   - Hoisted from "react-native#promise"
info Disk size without dependencies: "244KB"
info Disk size with unique dependencies: "296KB"
info Disk size with transitive dependencies: "296KB"
info Number of shared dependencies: 1
=> Found "fbjs#promise@7.3.1"
info This module exists because "expo#fbemitter#fbjs" depends on it.
info Disk size without dependencies: "220KB"
info Disk size with unique dependencies: "272KB"
info Disk size with transitive dependencies: "272KB"
info Number of shared dependencies: 1
✨  Done in 0.25s.
```

### Version

`0.70.6`

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 658.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.16.0/bin/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.09.19.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/rarroyo/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
````

### Steps to reproduce

1.- Have react native 0.70.6 installed.
2.- Have expo installed on a bare react native application following their documentation.
3.- Use Promise.allSettled.
4.- Get [TypeError: undefined is not a function].

### Snack, code example, screenshot, or link to a repository

```js
const results = await Promise.allSettled([promise1, promise2])
```

**Comment by jkadamczyk** [comment]
I have to agree with the issue. My setup is slightly different. I use 0.68.5 in a project, along with `hermes-engine` version 0.11.0.
It should've been fixed in 0.68.4, which makes me assume that it should also work in 0.68.5, but it doesn't work.

**Comment by retyui** [comment]
`promise@8.3.0` will be used for a `JSC` engine, as I understand latest `Hermes` has own implementation      


see: 
https://github.com/facebook/react-native/blob/436da18fce99af6361bae5719cfce0ed4539a3f7/Libraries/Core/polyfillPromise.js#L25-L38


to test:
```tsx
console.log(' --- debug',{allSettled:Promise.allSettled,any:Promise.any, hermes_hasPromise:global?.HermesInternal?.hasPromise?.()})

 --- debug {"allSettled": undefined, "any": undefined, "hermes_hasPromise": true}
```

---

So, better to create issue in [an appropriate repo](https://github.com/facebook/hermes/issues/new/choose)

**Comment by BrandonYuen** [comment]
This still seems to be an issue for me on `0.71.8`, when using the exact example from [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled#using_promise.allsettled):
```
Promise.allSettled([
  Promise.resolve(33),
  new Promise((resolve) => setTimeout(() => resolve(66), 0)),
  99,
  Promise.reject(new Error("an error")),
]).then((values) => console.log(values));
```

It seems to never log any values and only shows me this warning:
```
Possible Unhandled Promise Rejection (id: 3):
Error: an error
```

**Comment by cesargdm** [comment]
Appears to still be an issue in `0.72.6`

**Comment by oidoug** [comment]
I'm getting loads of crashes reported on Sentry for `TypeError: undefined is not a function` when calling ` Promise.allSettled(promises)`

All issues are on Android and Hermes for RN 0.72.4.

**Comment by MohammadAzimi** [comment]
I'm using `"expo": "~49.0.6"` and `"react-native": "0.72.6"` and the issue is remaining only in production.
I found a temporary workaround in [here](https://stackoverflow.com/a/70114114/7178860)

**Comment by weese** [comment]
I also observing this issue with React Native 0.75 in our non-debug builds. My workaround was to replace all occurrences of `Promise.allSettled` with `promiseAllSettled` and define this helper function somewhere:
```
const promiseAllSettled = <T>(promises: Promise<T>[]): Promise<Array<{ status: "fulfilled"; value: T } | { status: "rejected"; reason: any }>> => 
  Promise.all(
    promises.map(p => 
      p.then(value => ({
        status: "fulfilled" as const,
        value
      }))
      .catch(reason => ({
        status: "rejected" as const,
        reason
      }))
    )
  );
```

**Comment by williamliangwl** [comment]
We are also experiencing the same error when using `Promise.allSettled`. It somehow only happens with production build. The production build is using Hermes and we are using React Native v0.74.5

**Comment by Andre-3rd-Viking** [comment]
Same here:
- not observable in development mode
- only happens in production builds 🤔

**Comment by obasille** [comment]
I'm getting this error on iOS & Android, for production builds and development build (using expo dev client)
expo: 51.0.38
expo-dev-client: 4.0.29
react-native: 0.74.5

**Comment by itsramiel** [comment]
I ran into this, and the reason was Sentry. They patch the global Promise 🙃

If you use sentry and disable it in development, that's how you end up with a production only crash.

Check [this sentry issue](https://github.com/getsentry/sentry-react-native/issues/3957) and [their troubleshooting guide](https://docs.sentry.io/platforms/react-native/troubleshooting/#disable-auto-patching)

**Comment by joxxoxo** [comment]
Does it look like a good solution?
```typescript
  const allSettled = Promise.allSettled
  Sentry.init({ dsn: SENTRY_DSN })
  Promise.allSettled = allSettled.bind(Promise)
```

**Comment by LMakshow** [comment]
On the React Native 0.76 with Expo 52, if you use Yarn the fix is to add the following resolution to your package.json. No other steps from the sentry troubleshooting guide are required (no need to disable auto-patching).
```
  "resolutions": {
    "promise": "^8.3.0"
  },
```

**Comment by lochstar** [comment]
on React Native 0.77 and Expo 52 you can use:

```
  "overrides": {
    "promise": "^8.3.0"
  }
```
