### ISSUE TITLE
Issue testing via mocha + babel after 0.30 upgrade

### ISSUE THREAD

**Issue by joshualcoffee** [facebook/react-native#8971]
After upgrading to 0.30 I can no longer run mocha test compiled via babel.  I did a good bit of research yesterday and it looks like babel has a problem with the way react native handles dependencies.   I realized node-haste handles the path differently than the standard path using `@providesModule`.

If i set up a test project with minimal setup and run react-native through babel I receive `Cannot find module 'AssetRegistry'` corresponding line https://github.com/facebook/react-native/blob/master/Libraries/Image/AssetSourceResolver.js#L21  . 

 The only way I can think to get aroudn this is to mock everything.  If i go that route we have an unreliable test suite.  Im curious if anyone else has had this issue and how you solved it.

**Comment by joshualcoffee** [comment]
Figured out I can port some things over to react-native-mock and get everything working correctly.

**Comment by joncursi** [comment]
@joshualcoffee could you explain how you resolved this? I ran into the same issue today on `react-native@0.32.1` and `react-native-mock@latest`

**Comment by joshualcoffee** [comment]
@joncursi The issue I kept running in to was a third party library (react native maps I believe) was not being mocked.  I installed mockery and just mock the library in my test setup using
`mockery.registerMock('react-native-maps', () => {return(null)});` .  This is not the cleanest solution as react native maps will always be mocked.

**Comment by joncursi** [comment]
@joshualcoffee thanks for your quick response! I'm in the same boat as you, as importing `MapView` from `react-native-maps` was what produced the error. However, I'm still running into the same issue when I tried out your snippet above.

At the risk of getting a bit off-topic from react-native core, I was wondering if you had any ideas what could be wrong here with my mocha setup?

Start command:
```
./node_modules/.bin/mocha --require setup.js --compilers js:babel-register --recursive imports/**/*.tests.js
```

setup.js:
```js
import fs from 'fs';
import mockery from 'mockery';
import path from 'path';
import register from 'babel-core/register';

// Ignore all node_modules except these
const modulesToCompile = [
  'react-native',
  'react-native-linear-gradient',
  'react-native-maps', // this doesn't seem to have an effect
  'react-native-material-design',
  'react-native-mock',
  'react-native-search-bar',
].map((moduleName) => new RegExp(`/node_modules/${moduleName}`));

const rcPath = path.join(__dirname, '../../../..', '.babelrc');
const source = fs.readFileSync(rcPath).toString();
const config = JSON.parse(source);

config.ignore = (filename) => {
  if ((/\/node_modules\//).test(filename)) {
    const matches = modulesToCompile.filter((regex) => regex.test(filename));
    const shouldIgnore = matches.length === 0;
    return shouldIgnore;
  }
  return false;
};

register(config);

// Setup globals
global.ReactNativeMock = require('react-native-mock');

// Setup mocks
require('react-native-mock/mock');
mockery.registerSubstitute('react-native-maps', () => null); // neither did this
```

Anything you can see that would make this still fail? The line that produces the error is, in one of my components:

```
import MapView from 'react-native-maps';
```

Thanks!

**Comment by joshualcoffee** [comment]
@joncursi 

You need to enable mockery.  So here is the gotcha this will enable mockery for your entire suite.  I have not found a work around for enabling mockery for certain test at this point.

```javascript
mockery.enable({
    warnOnReplace: false,
    warnOnUnregistered: false
});
```

**Comment by joncursi** [comment]
That did the trick! Thank you for your help @joshualcoffee!
