### ISSUE TITLE
Error: NetInfo.isConnected.fetch(...).done is not a function

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#2022]
I'm getting this after upgrading react-native to 0.7.1.

     Error: NetInfo.isConnected.fetch(...).done is not a function
     stack: 
      Store.Reflux.createStore.init                                                index.ios.bundle:63454
      new                                                                          index.ios.bundle:43816
      Object.module.exports [as createStore]                                       index.ios.bundle:43828
      <unknown>                                                                    index.ios.bundle:63440

The code is this

        NetInfo.isConnected.fetch().done(
    	(connected) => {this._changeConnectionStatus(connected); }
    );

**Comment by mschipperheyn** [comment]
Interesting, when I make sure the first require call to this connectionstore is moved to within the componentDidMount of the React Class using it, the problem goes away. Seems like it wasn't ready yet, which must be some kind of change from 0.6.0.

**Comment by brentvatne** [comment]
@mschipperheyn - did you manage to resolve this? It looks like it is working as expected with UIExplorer on 0.8.0. Make sure you restart your packager and perhaps even XCode! Ping me if that doesn't fix it and I'll reopen.

**Comment by mschipperheyn** [comment]
Yeah, I still get this issue. I execute the function within a Reflux Store init statement. 

If I use 

    NetInfo.isConnected.fetch().then(
    	(connected) => {this._changeConnectionStatus(connected); }
    );

it seems to work

**Comment by pyadav** [comment]
@brentvatne I also getting this NetInfo.isConnected.fetch(...).done is not a function using "react-native": 0.12.0
