### ISSUE TITLE
Android app  collapsed after upload to 0.26

### ISSUE THREAD

**Issue by dunhuang** [facebook/react-native#7905]
React native code is integrated into Android app, works fine with react-native 0.25.+,
After uploaded to 0.26, unable to work anymore, as the following:
"unfortunately, xxxxx(app name) has stopped"

react 15.0.1
react-native 0.26.2
osx 10.11.4
gradle:   compile "com.android.support:appcompat-v7:23.0.1"

**Comment by charpeni** [comment]
Can you check the crash log with Logcat?

**Comment by charpeni** [comment]
@facebook-github-bot label Needs more information

**Comment by dunhuang** [comment]
Unable to load script from assets: index.android.bundle
06-04 10:03:25.992 18310-18544/com.kenny.embedded E/ReactNative: Got JS Exception: ReferenceError: Can't find variable: __fbBatchedBridge
06-04 10:03:26.014 18310-18310/com.kenny.embedded D/AndroidRuntime: Shutting down VM @charpeni

**Comment by dunhuang** [comment]
I just make it works in 0.26.2, while I think there are there problems needs to be solved.

1. I just realized the correct peer dependence of 0.26.2 is react 15.0.2 instead of 15.0.1, according to #7697 
2. It is still not able to run app with Android Studio directly. Log is as mentioned previously. I have to type in terminal "react-native bundle"  to generate bundle file.
3. After step 2, app still crash with new log "undefined is not a function (evaluating 'UIManager.setChildren(containerTag,createdTags)')", I changed the UIManager.js under node_modules/react-native/Libraries/Utilities following #7409, finally app works.

any better solutions?

**Comment by charpeni** [comment]
> I just realized the correct peer dependence of 0.26.2 is react 15.0.2 instead of 15.0.1, according to #7697

It should be fixed with 0.26.3.

**Comment by dunhuang** [comment]
@charpeni you meant 0.27+ ? I tried with 0.26.3 do not work with #7409

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-app-collapsed-after-upload-to-026

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by ravirupareliya** [comment]
After upgrading from version 0.38.0 to 0.42.0 i am getting the same error

    java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
     at com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
     at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:198)
     at com.facebook.react.cxxbridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:33)
     at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:216)
     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:994)
     at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
     at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:746)
     at java.lang.Thread.run(Thread.java:761)
