### ISSUE TITLE
[0.48.0]: Error: Redefinition of RCTMethodInfo

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#15775]
After upgrading from `0.47.2` -> `0.48.0`, I can't get XCode to build anymore. I've tried clearing out derived data, cleaning the project, etc. It's consistently failing with this error, across various `react-native-*` modules I have installed.

![screen shot 2017-09-03 at 3 46 44 pm](https://user-images.githubusercontent.com/4974609/30006130-7c46a09a-90bf-11e7-8e6b-3f07f788b427.png)

**Comment by joncursi** [comment]
FWIW, I downgraded to `0.47.2`, cleared derived data, cleaned the project, and now I'm operational again. There's something funky going on in the new `0.48.0` release.

**Comment by fabriziogiordano** [comment]
Probably dupe for https://github.com/facebook/react-native/issues/15762

**Comment by joncursi** [comment]
Hmm. I saw that but didn't think so because the project in #15762 actually compiles, and then crashes, whereas this straight up won't compile.

**Comment by grabbou** [comment]
Not a duplicate - I couldn't reproduce this issue.

**Comment by robertmerten** [comment]
React Native 0.48.1

Same issue here with a third party module

![bildschirmfoto 2017-09-04 um 11 56 23](https://user-images.githubusercontent.com/675081/30021626-462ab92a-9168-11e7-8133-3da3ec13e803.png)

**Comment by iegik** [comment]
Previous definition is here: https://github.com/facebook/react-native/blob/master/React/Base/RCTBridgeModule.h#L54

**Comment by iegik** [comment]
Resolved, by changing import priority: https://github.com/yonahforst/react-native-permissions/issues/137

**Comment by exentrich** [comment]
Same issue

**Comment by iegik** [comment]
@exentrich clean project, rebuild [CMD] + [CTRL] + [SHIFT] + [K]

**Comment by MatthieuPeyrot** [comment]
I fix the issue by changing in all module #import "RCTBridgeModule.h" into #import <React/RCTBridgeModule.h>

**Comment by iegik** [comment]
Fixed in https://github.com/facebook/react-native/pull/15783

**Comment by MatthieuPeyrot** [comment]
Even with this fix i try #import <React/RCTDevMenu.h> and #import "RCTDevMenu.h" clean rebuild nothing change i still have the issues and the parallelize build is disabled.

**Comment by iegik** [comment]
@MatthieuPeyrot Please, review https://github.com/facebook/react-native/pull/15788

**Comment by MatthieuPeyrot** [comment]
Even with this I have RCTDevMenu.h file not found

**Comment by kozillla** [comment]
@iegik , I have applied your fix how ever it didnt work for me , still have redefinition of RCTMethodInfo,

**Comment by iegik** [comment]
@kozillla do you have react-native-permissions in your project included?
https://github.com/yonahforst/react-native-permissions/pull/138/files

**Comment by kozillla** [comment]
@iegik no,I do not use it.

**Comment by jorgefspereira** [comment]
@kozillla I had the same issue. I dont know if its the correct way to fix the issue but here it is: change the React.podspec (node_modules/react-native) line "React/DevSupport/*" in ss.exclude_files of subspec "Core" to "React/DevSupport/*.{c,m,mm,S}". Run pod install and should work.

**Comment by fungilation** [comment]
Same error here with RCTDevMenu.h, when upgraded RN from 0.47 to 0.48.1. From XCode:
```
[project]/node_modules/react-native/React/Base/RCTTVRemoteHandler.m:25:9: 'RCTDevMenu.h' file not found
```

@jorgefspereira's workaround works and my app builds! Though obviously not a proper fix.

**Comment by fungilation** [comment]
@grabbou please note that RN 0.48.1 seems to have fixed this issue's original `RCTMethodInfo` error, but error with `RCTDevMenu.h` is persisting in 0.48.1 and is a showstopper

**Comment by kozillla** [comment]
@jorgefsereira thx for sugestion but I dont use pods to manage react-native, also problem persist in RN 0.48.1

**Comment by iegik** [comment]
@kozillla I was right, you found that module, which conflicts with React Native.
Whatever, the problem, that third-partly modules import React Native modules as `#import "RCTBridgeModule.h"` first and `<React/RCTBridgeModule.h>` as failback. But should be otherwise.

**Comment by kinber95** [comment]
I had the same issue from a Ble lib. If I change the imports from the header module from: 
```

#import "RCTBridgeModule.h"
#import "RCTEventEmitter.h"
```

to:

```
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
```

it fix my problem.

**Comment by iegik** [comment]
https://github.com/Polidea/react-native-ble-plx/pull/136

**Comment by kozillla** [comment]
@iegik ,thanks for pointing issue, you are right, fixing import sequence in third part modules resolve this problem

**Comment by fhad-getmaple** [comment]
+1 - RCTDevMenu.h file not found

**Comment by arminsal1** [comment]
RCTDevMenu.h file not found is happening for me too, in RCTTVRemoteHandler.m

**Comment by fungilation** [comment]
Is this issue getting looked at? No tag or assignment, and this should be priority considering it's build breaking.

Shouldn't RN releases pass basic build tests before being released in the first place? 😢

**Comment by ggsrivas** [comment]
as per latest [document](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html)
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    **'DevSupport'**, # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

Adding **DevSupport** in Podfile fixed RCTDevMenu.h not found issue.
As point out by others, Changing 
`import "RCTBridgeModule.h"` to `import <React/RCTBridgeModule.h>` fixed the RCTBridgeModule not found error.

**Comment by fungilation** [comment]
Confirmed fix, with adding `'DevSupport'` line to `pod 'React'` in Podfile fixes `RCTDevMenu.h` not found issue.

This needs to be better documented, as previous to RN 0.48, build didn't break without the `'DevSupport'` line in Podfile.

**Comment by joncursi** [comment]
Thanks for the comments everyone, I was able to get past this issue by using some code forks that the community has created the various third-party modules that are not yet compatible with RN `0.48.x`. For me, it was these two:

```json
"react-native-oauth": "git+ssh://git@github.com/exentrich/react-native-oauth#patch-1",
```

```json
"react-native-permissions": "git+ssh://git@github.com/vinnyjth/react-native-permissions",
```

I will use these forks for now, until official fixes land on the `master` branch for these two projects.

**Comment by dotansimha** [comment]
Also possible to just add `DevSupport` instead of specifying all modules from the `React` pod:
```
  pod 'React', :path => '../node_modules/react-native'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport'
  ]
```

**Comment by rodrigoxavier** [comment]
To solve this issue I updated all my dependencies and link again. Then, I change all  #import "RCTBridgeModule.h" to #import <React/RCTBridgeModule.h>.

**Comment by pincheira** [comment]
@joncursi are you still using the patched version for react-native-oauth? Cheers!

**Comment by joncursi** [comment]
Yes

**Comment by snarang2** [comment]
@kinber95 - in which file do we have to change the import order? I am not able to find it

**Comment by andela-cofor** [comment]
@iegik I get `ld: framework not found DCTAuth`

**Comment by prateekm33** [comment]
FWIW I made the change shown here : https://github.com/yonahforst/react-native-permissions/issues/137

It didn't work. So I reverted the changes, rebuilt, and the app is running now. Ofc, I also had manually linked `libOAuthManager.a` prior to all of this.

**Comment by chandanyadav7** [comment]
just write 
#ifndef CODE  
#define CODE               //  at the top of the file 
.
.
.
.
#endif                            //at  last

**Comment by aino-gautam** [comment]
Refer to this SO Q/A for an accurate solution - 

https://stackoverflow.com/questions/46813090/react-native-error-redefinition-of-rctmethodinfo-after-installing-the-plugin
