### PR TITLE
fix: use consistent version of glob in react-native

### LINKED ISSUE #44712: [codegen]: TypeError: glob.sync is not a function
### Description

```
TypeError: glob.sync is not a function
    at extractSupportedApplePlatforms (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:176:25)
    at generateSchemaInfo (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:398:35)
    at Array.map (<anonymous>)
    at generateSchemaInfos (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:449:20)
    at Object.execute (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:653:27)
    at Object.<anonymous> (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/generate-codegen-artifacts.js:31:10)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
```

### Steps to reproduce

pod-install in a react-native-cli app after upgrading to 0.74.1

Prev version: 0.69.4

### React Native Version

0.74.1

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
warn Package @react-native-community/google-signin contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 92.73 MB / 32.00 GB
  Shell:
    version: 3.7.0
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 20.10.0
    path: ~/Library/Caches/fnm_multishells/91556_1717035899948/bin/node
  Yarn:
    version: 3.6.4
    path: ~/Library/Caches/fnm_multishells/91556_1717035899948/bin/yarn
  npm: Not Found
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
```


### Stacktrace or Logs

```text
➜  ios git:(feat-rn-0.74.1) ✗ pod install
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `ceres`: BVLinearGradient, CodePush, MixpanelReactNative, RNCAsyncStorage, RNCClipboard, RNCMaskedView, RNColorMatrixImageFilters, RNDeviceInfo, RNFBAnalytics, RNFBApp, RNFBDatabase, RNFBDynamicLinks, RNFBPerf, RNFBRemoteConfig, RNFS, RNFastImage, RNFingerprintjsPro, RNFlashList, RNGestureHandler, RNGoogleSignin, RNInAppBrowser, RNLocalize, RNPermissions, RNReanimated, RNSVG, RNScreens, RNSentry, RNShare, RNSharedElement, ReactNativeLocalization, WatermelonDB, headout-aer, headout-aqua, headout-brok, lottie-ios, lottie-react-native, react-native-blob-util, react-native-config, react-native-fbsdk, react-native-maps, react-native-mmkv, react-native-netinfo, react-native-pdf, react-native-render-html, react-native-safe-area-context, react-native-slider, react-native-text-input-mask, react-native-track-player, react-native-video, react-native-webengage, and react-native-webview
Framework build type is static library
[Codegen] Adding script_phases to React-Codegen.
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json

[!] Invalid `Podfile` file: [!] /Users/regalstreak/Library/Caches/fnm_multishells/91556_1717035899948/bin/node ./../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /Users/regalstreak/dev/headout/proteus/ios/.. -o /Users/regalstreak/dev/headout/proteus/ios -t ios

[Codegen] Analyzing /Users/regalstreak/dev/headout/proteus/package.json
[Codegen] Searching for codegen-enabled libraries in the app.
[Codegen] The "codegenConfig" field is not defined in package.json. Assuming there is nothing to generate at the app level.
[Codegen] Searching for codegen-enabled libraries in the project dependencies.
[Codegen] Found @react-native-clipboard/clipboard
[Codegen] Found @react-native-community/slider
[Codegen] Found @sentry/react-native
[Codegen] Found react-native
[Codegen] Found react-native-gesture-handler
[Codegen] Found react-native-mmkv
[Codegen] Found react-native-pdf
[Codegen] Found react-native-permissions
[Codegen] Found react-native-reanimated
[Codegen] Found react-native-safe-area-context
[Codegen] Found react-native-screens
[Codegen] Found react-native-svg


[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
[Codegen] Processing rnclipboard
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Done.
TypeError: glob.sync is not a function
    at extractSupportedApplePlatforms (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:176:25)
    at generateSchemaInfo (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:398:35)
    at Array.map (<anonymous>)
    at generateSchemaInfos (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:449:20)
    at Object.execute (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:653:27)
    at Object.<anonymous> (/Users/regalstreak/dev/headout/proteus/node_modules/react-native/scripts/generate-codegen-artifacts.js:31:10)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
.

 #  from /Users/regalstreak/dev/headout/proteus/ios/Podfile:67
 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :production => production,
 #  -------------------------------------------
```

### Reproducer

-

### Screenshots and Videos

_No response_

### PR DESCRIPTION
**Pull request by regalstreak**
https://github.com/isaacs/node-glob/issues/493

Fixes #44712 

## Changelog:
[General][Fixed] - Use consistent version of glob in react-native

### CODE REVIEW

**Comment by regalstreak** [comment]
Let me know if this needs to be done in all places, I can see 4 other occurrences in scripts/

**Comment by NickGerleman** [comment]
It seems like the real bug here is that we are resolving from `react-native` package, which does not explicitly depend on `glob`. That means a random version is pulled in. 

@regalstreak does this issue go away if we update `packages/react-native/package.json` to consistent glob version as used elsewhere in repo?

https://github.com/search?q=repo%3Afacebook%2Freact-native+glob+language%3Ajson&type=code

**Comment by regalstreak** [comment]
@NickGerleman it does indeed, `glob@^7.1.1` works.

Our app uses `glob@^9.2.1`, guessing the apps version is being picked

**Comment by regalstreak** [comment]
@NickGerleman done!
