### ISSUE TITLE
this._nativeModule.addListener is not a function (iOS, RN v0.27.2)

### ISSUE THREAD

**Issue by oureta** [facebook/react-native#8025]
I'm encountering this issue when upgrading to v0.27.2 (iOS)

I think I have the same issue as this: https://github.com/fbsamples/f8app/issues/62

**Comment by oureta** [comment]
This is due to `KeyboardObserver` native module

`rnpm link` fixes the problem

**Comment by simonbdev** [comment]
this unforunately didn't fix this error for me after upgrading from v0.24.0 to v0.29.0 (iOS). I also tried removing node_module and re-running `npm install` to no avail :(

Anyone found a solution that works for v0.29.0?

**Comment by Maxyss** [comment]
Same on 0.29. Any updates here?

**Comment by Alejandro-Glooko** [comment]
+1 for RN 0.29

**Comment by esauter5** [comment]
I was able to resolve this by restarting the app in XCode.

**Comment by mebinum** [comment]
+1 for RN 0.30 anybody know why this is happening

**Comment by sgwilym** [comment]
Also having this problem with RN 0.30.0-rc.0.

**Comment by n8stowell82** [comment]
I have been having this problem as well.  here is what I have done to try and fix.  Please let me know if this helps you in any way.

1.) follow the steps above with `rm -rf node_modules && npm install` and then `rnpm link`
2.) make sure to follow the upgrade instructions on the 0.27 release notes post -> [https://github.com/facebook/react-native/releases/tag/v0.27.0](url)
     a.) specifically replace any references to `DeviceEventEmitter` with `Keyboard`
3.) run from Xcode not command line.  This worked for me as a way to get the project up and running.  The project would run fine from Xcode but fail when run with `react-native run-ios`
4.) if project runs from xcode but will not run from command line you most likely have a cached version of the build that needs to be killed.
    a.) Navigate to your project in finder and locate the iOS/build folder and open it
    b.) Destroy the contents of this folder (you can probably get by just deleting the "Intermediates"        folders, but make sure to check inside nested folders to find all instances of "Intermediates".  This is why I just kill the whole thing
    c.) run `sudo react-native run-ios` to rebuild the project and run it
    d.) if you get a message saying "no devices booted" then run `react-native run-ios` after running previous command

If this didn't work for you then try running `react-native upgrade` before step walking through step 4.  Be careful with the upgrade command if you have any custom logic outside of RN in you xcode project as this command will reset the project to default settings.  You can evaluate each question with hitting `d` to see what changes are trying to be made.


Hopefully this helps someone

**Comment by zo-chu** [comment]
unfortunately,  this doesn't work for my case... rn 0.31 trying to set up PushNotifications and each time see this red screen 'this._nativeModule.addListener is not a function'

Any thoughts what can cause it?

**Comment by amaanmemon** [comment]
@zo-chu : did you find any solutions, same issue here
If found, please post the solution, Thanks

**Comment by kkkelicheng** [comment]
I have found that 
if in nativeModule do not sendEventWithName：eventA
but in ReactNative  nativeEventEmitter.addListener： eventA。
could occur that error
I think it may help who have this issue
