### ISSUE TITLE
React Native 0.43 upgrade error

### ISSUE THREAD

**Issue by jinlong** [facebook/react-native#13309]
### Description

When my project upgrade to React Native 0.43，hint errors as follow:

```
├── UNMET PEER DEPENDENCY react@15.4.2
├── react-addons-pure-render-mixin@15.4.2
├── react-native@0.43.0
├── react-native-extended-stylesheet@0.3.2
└── react-native-scrollable-tab-view@0.6.0

npm ERR! peer dep missing: react@16.0.0-alpha.6, required by react-native@0.43.0
npm ERR! peer dep missing: react@^15.5.0, required by react-addons-shallow-compare@15.5.0-alpha.0
```

How to resolve it?

### Reproduction Steps and Sample Code

I use `npm install --save react-native@0.43` to upgrade React Native

### Additional Information

* React Native version: 0.43
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio 2.2.3

**Comment by ide** [comment]
You need to install `react@16.0.0-alpha.6`. You can safely ignore the warning about `react-addons-shallow-compare@15.5.0-alpha.0`, it is harmless and will be fixed in 0.43.1.

(cc @grabbou, I merged a commit to 0.43-stable that removes react-addons-shallow-compare [unused] from package.json)

**Comment by grabbou** [comment]
Thanks, I'll be at work in a while and will pick it.

**Comment by Jazz747** [comment]
I'm having the same issue with react-native-maps@0.14.0 (latest)

react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed.

**Comment by kelset** [comment]
So 0.43 is already running Fiber?
(react@16 = fiber right?)

**Comment by npomfret** [comment]
43.1 failed for me with: Unable to resolve module `react/lib/shallowCompare`

**Comment by SudoPlz** [comment]
I get `UNMET PEER DEPENDENCY react@16.0.0-alpha.6` even though react@16.0.0-alpha.6 is installed.

**Comment by MarsHuang123** [comment]
I also met this issue, 'UNMET PEER DEPENDENCY react@16.0.0-alpha.6'

**Comment by Lxxyx** [comment]
@npomfret Got same issue. Do you fixed?

**Comment by jinlong** [comment]
Thanks ! 

As @ide say, i installed `react@16.0.0-alpha.6`, then my project could run normally.

Errors as follow are harmless, they will be fixed.

```
npm ERR! peer dep missing: react@^15.5.0, required by react-addons-shallow-compare@15.5.0-alpha.0
npm ERR! peer dep missing: react@^0.13.0 || ^0.14.0 || ^15.0.0, required by react-static-container@1.0.1
```

**Comment by iroshanAV** [comment]
@jinlong but still getting the Unmet peer error :(

**Comment by iroshanAV** [comment]
In fact  after install react@16.0.0 i get this error

```
camerahere@0.0.1 H:\reactp\reactN\cam\camerahere
`-- UNMET PEER DEPENDENCY react@16.0.0-alpha.6

npm WARN react-native-camera@0.6.0 requires a peer of react@>=15.4.0 but none was installed.
npm ERR! code 1
```

**Comment by liftyourgame** [comment]
I get the same issue with react@16.0.0-alpha.6 installed
I even tried removing node_modules first and then installing react@16.0.0-alpha.6 first before running npm install

**Comment by liftyourgame** [comment]
Upgrading npm seems to fix the issue:

`npm install npm@latest -g`

**Comment by iroshanAV** [comment]
@liftyourgame yes, that solved my problem too :D

**Comment by ericchuawc** [comment]
@liftyourgame his approach works for me too :) hooray

just i got a warning, not sure is there any side effect?

npm WARN react-test-renderer@15.4.2 requires a peer of react@^15.4.2 but none was installed.

hmm?

**Comment by iroshanAV** [comment]
@ericchuawc  surely that error has side effects, can you install it separately ?

**Comment by ericchuawc** [comment]
@iroshanAV any tips how to solve this warning? as i am using the latest react 16 alpha due to react native 0.43.

**Comment by petersuwara** [comment]
Removed NPM, REACT-NATIVE-CLI and WATCHMAN. Reinstalled everything and created a new project. Now it seems to work.

**Comment by iroshanAV** [comment]
@ericchuawc as @petersuwara  suggest try to install from the beginning, else reinstall the  react-test-renderer@15.4.2  separately

**Comment by dcp12345678** [comment]
Did not work for me, even after upgrading npm. Previous versions of react-native seemed to work ok until 43.  Here is the error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve com.facebook.fresco:fresco:1.0.1.
     Required by:
         testproj:app:unspecified > com.facebook.react:react-native:0.43.3
      > Could not resolve com.facebook.fresco:fresco:1.0.1.
         > Could not get resource 'https://jcenter.bintray.com/com/facebook/fresco/fresco/1.0.1/fresco-1.0.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/facebook/fresco/fresco/1.0.1/fresco-1.0.1.pom'.
               > jcenter.bintray.com
   > Could not resolve com.facebook.fresco:imagepipeline-okhttp3:1.0.1.
     Required by:
         testproj:app:unspecified > com.facebook.react:react-native:0.43.3
      > Could not resolve com.facebook.fresco:imagepipeline-okhttp3:1.0.1.
         > Could not get resource 'https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp3/1.0.1/imagepipeline-okhttp3-1.0.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp3/1.0.1/imagepipeline-okhttp3-1.0.1.pom'.
               > jcenter.bintray.com

**Comment by fanxuricky** [comment]
@liftyourgame amazing solution, and thanks for the solution too.

**Comment by cbartondock** [comment]
It's kind of frustrating that react-native seems to skip React 15.5.0, when this is precisely the version which is required by several different plugins. 

react-native@0.42.3 requires a peer of react@~15.4.1
react-native@0.43.0 requires a peer of react@16.0.0-alpha.6

No room at all for react@^15.5.0

**Comment by cdkd123** [comment]
when i exe npm install react-native@16.0.0-alpha.6 --save, success.

**Comment by githubmss** [comment]
I was getting the same error initially , then i run following commands :- 

1. npm install npm@latest -g (This makes my npm version from 3.10.8 to 5.0.1)
2. rm -rf node_modules/
3. sudo npm install --save
4. sudo npm install react-native-side-menu --save 
Now when i run **react-native run-android** i start getting this bellow error :-  

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'anymatch'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mss/Desktop/cakenew25_aug/MagentoLatest/Rdemo/node_modules/jest-haste-map/node_modules/sane/src/common.js:3:16)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mss/Desktop/cakenew25_aug/MagentoLatest/Rdemo/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```
Any help please , i have been fighting with it from last 2 days.

**Comment by petersuwara** [comment]
@githubmss have you tried a new project with out react-native-side-menu ? 

Does it still work ?

**Comment by githubmss** [comment]
@petersuwara , let me uninstall that package and try it

**Comment by githubmss** [comment]
yes , still getting same error

**Comment by petersuwara** [comment]
Remove NPM, NODE, REACT-NATIVE-CLI.

NODE/NPM -> https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

Reinstall everything and create a new project. 
https://facebook.github.io/react-native/docs/getting-started.html

- Install NPM
- Install react-native-cli (global)
- Install Watchman

Run react-native init testproj
Run react-native run-android

Does the fresh project work ?

**Comment by githubmss** [comment]
@petersuwara , i am not very much familiar with the commands , will it be possible for you if you can type all those commands for me . when i run "**brew info node**" command from the link provided by you

it displays something like this :-

**brew info node**

```
========================================================================
You may want to update following environments after installed linuxbrew.

  PATH, MANPATH, INFOPATH 

(example: /usr/share/doc/linuxbrew-wrapper/examples/profile)
========================================================================
==> This script will install:
/home/mss/.linuxbrew/bin/brew
/home/mss/.linuxbrew/Library/...
/home/mss/.linuxbrew/share/man/man1/brew.1

Press RETURN to continue or any other key to abort

```

**Comment by petersuwara** [comment]
@githubmss you should look at ->

**brew info npm**

Suggest **brew uninstall npm** then find where your node_modules directory is and delete that.

**Comment by githubmss** [comment]
i got something like this :- 

brew info npm 

```
node: stable 8.0.0, HEAD
Platform built on V8 to build network applications
https://nodejs.org/
Conflicts with: node@0.10, node@0.12
Not installed
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/node.rb
==> Dependencies
Build: xz ✘, pkg-config ✘
Recommended: icu4c ✘
Error: Unsupported special dependency :perl
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/mss/.linuxbrew/Library/Homebrew/dependency_collector.rb:123:in `parse_symbol_spec'
/home/mss/.linuxbrew/Library/Homebrew/compat/dependency_collector.rb:17:in `parse_symbol_spec'
/home/mss/.linuxbrew/Library/Homebrew/dependency_collector.rb:73:in `parse_spec'
/home/mss/.linuxbrew/Library/Homebrew/dependency_collector.rb:61:in `build'
/home/mss/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/home/mss/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/home/mss/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/home/mss/.linuxbrew/Library/Homebrew/dependency_collector.rb:38:in `add'
/home/mss/.linuxbrew/Library/Homebrew/software_spec.rb:155:in `depends_on'
/home/mss/.linuxbrew/Library/Homebrew/formula.rb:1862:in `block in depends_on'
/home/mss/.linuxbrew/Library/Homebrew/formula.rb:1862:in `each'
/home/mss/.linuxbrew/Library/Homebrew/formula.rb:1862:in `depends_on'
/home/mss/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:36:in `<class:Openssl>'
/home/mss/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:4:in `load_formula'
/home/mss/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/mss/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/mss/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/mss/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/mss/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/mss/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/mss/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/mss/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/mss/.linuxbrew/Library/Homebrew/dependency.rb:38:in `installed?'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:142:in `block in decorate_dependencies'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:141:in `collect'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:141:in `decorate_dependencies'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:127:in `block in info_formula'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:125:in `map'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:125:in `info_formula'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:35:in `block in print_info'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:29:in `each'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:29:in `each_with_index'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:29:in `print_info'
/home/mss/.linuxbrew/Library/Homebrew/cmd/info.rb:18:in `info'
/home/mss/.linuxbrew/Library/brew.rb:84:in `<main>'
```

**Comment by petersuwara** [comment]
@githubmss please e-mail me on peter@realityworks.com.au I can help you there.

**Comment by githubmss** [comment]
@petersuwara , i have mailed you , please let me know if you require any further information.Thanks for your support . Appreciate it!!!!

**Comment by ahilton** [comment]
@githubmss, I had the same error [Cannot find module 'anymatch'] after upgrading from RN 0.41.2 to 0.44.1.

After re-installing NPM, NODE & REACT-NATIVE-CLI as per @petersuwara suggestion, I also had to delete '**package-lock.json**' in the project directory in order to resolve. No idea why.

**Comment by Kosai106** [comment]
I've been getting the same issue as @githubmss after upgrading to NPM 5.0.2, but luckily, like @ahilton suggested, deleting *'package-lock.json'* solved it.

**Comment by fengerzh** [comment]
Just delete `package-lock.json` solved the problem. Don't worry, after you run `npm install`, `package-lock.json` will come back. I am not familiar with `yarn`, but I guess the file was generated by `yarn` to keep packages consistent.

**Comment by heckchuckman** [comment]
Confirming that deleting `package-lock.json` and then running `npm install` clears the issue for me. Thanks!

**Comment by catyku** [comment]
I fixed with reinstall nodejs
choco install nodejs

**Comment by sandeepeswar** [comment]
i have a problem react-native like
"""""" react-native run-android
Command `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project."'''
 # _**ofter install npm like_** 
its  shows 
""""" npm install
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-test-renderer@16.0.0-alpha.12 requires a peer of react@^16.0.0-alpha.12 but none was installed.

removed 9 packages in 44.208s"""""

can you ples replay  me how to solve this problem

**Comment by andrewschreiber** [comment]
Removing `yarn.lock` and `package-lock.json` then running `yarn` worked for me.
