### ISSUE TITLE
InternalError react-packager has encountered an internal error

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#9969]
I'm developing on the master branch and every time I change the file I get the follow error on both iOS and Android, I think it would be introduced in https://github.com/facebook/react-native/commit/b62ed2f291ad86d3d8192fe360fab4bfd5774576 
```
[Hot Module Replacement] File change detected (15:56:35:677)
[2016-09-18 15:56:37] <START> Finding dependencies
TypeError: bundle.setRamGroups is not a function
    at /Users/Neo/rn/react-native/packager/react-packager/src/Bundler/index.js:396:14
    at tryCallOne (/Users/Neo/rn/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/Neo/rn/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/Neo/rn/react-native/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
[Hot Module Replacement] Sending HMR update to client (15:56:37:614)
```
![image](https://cloud.githubusercontent.com/assets/2595058/18614058/5861d452-7db9-11e6-8187-07e85ef25775.png)

**Comment by nihgwu** [comment]
ping @davidaurelio

**Comment by nihgwu** [comment]
close as be resolved in #9982
