### PR TITLE
Fix ListView render error

### PR DESCRIPTION
**Pull request by eapache**
`getInnerViewNode` is a method and needs to be called with parentheses.

cc @boourns

### CODE REVIEW

**Comment by boourns** [comment]
For more context: we were experiencing the following error when initially rendering a custom component that extended `ScrollView`:
image

We tracked that back to the method in PR.  `scrollComponent.getInnerViewNode` exists as a function so this guard passes, but it returns `null` which fails the expectation on the native bridge side.  So I *think* the solution is to actually check the guard.

**Comment by mkonicek** [comment]
@sahrens What do you think?

**Comment by ide** [comment]
@sahrens i'm a bit confused about the original check since ListView always implements `getScrollResponder`, and the only time I expect it would return null is if there were an error mounting the scrollable component. So I'd propose something like this:

```js
if (!scrollComponent) {
  console.error('ListView does not have a scrollable component. Ensure that ' +
    'its scrollable component was rendered and mounted successfully.'
  );
  return;
}
if (!scrollComponent.getInnerViewNode || !scrollComponent.getInnerViewNode()) {
  console.error('The scrollable component does not implement getInnerViewNode ' +
    'correctly. Ensure that this method returns the scroll content container.'
  );
  return;
}
```

**Comment by boourns** [comment]
@ide our component that extends ScrollView doesn't implement `getInnerViewNode`.  It's implementation is just some base styling:

```
var styles = StyleSheet.create({
  listView: {backgroundColor: Branding.slateLightest},
});

class ShopifyScrollView extends ScrollView {
  render(): ReactElement {
    return <ScrollView {...this.props} style={[styles.listView, this.props.style]} />;
  }
}
```

It seemed that it was possible during the instantiation of our component that it would hit that guard before it was ready to return a valid value for `getInnerViewNode`.

Also to note, this error started happening when we bumped our project from react-native 0.9.0 to 0.11.0 without changing the implementation of `ShopifyScrollView`.

**Comment by ide** [comment]
@boourns I recommend implementing getInnerViewNode as that is part of the contract of a Scrollable component. Also you should extend React.Component instead of ScrollView -- I think it works but was designed much more for composition than inheritance.

**Comment by sahrens** [comment]
I don't understand what this fixes - does your component have a getInnerScrollNode function that returns a falsey value?  This diff will potentially introduce crashes if getInnerScrollNode is not defined at all.

I think @ide's comments are probably a better way to address the issues you're having.

**Comment by boourns** [comment]
@sahrens no, my component extends `ScrollView` and only has a `render` function defined, so I expected it to just inherit all existing ScrollView functionality.  I pasted the implementation a few comments above.

But you both are right that our extended class is not working properly as a ScrollView.  If I use the class provided by React Native, the error goes away.  I'll keep digging.

**Comment by ide** [comment]
@boourns I wrote this module https://github.com/exponentjs/react-native-scrollable-mixin to help with this use case. Except in very specific circumstances (none of which come to mind right now...) you always should extend `React.Component`. Anyway...

```js
class X extends React.Component {
  getScrollResponder() {
    return this._scrollView;
  }
  render() {
    return <ScrollView ref={c => { this._scrollView = c; }} />;
  }
}
Object.assign(X.prototype, ScrollableMixin);
```

**Comment by boourns** [comment]
@ide amazing, thanks James!
