### ISSUE TITLE
Unable to use static contextType in react native

### ISSUE THREAD

**Issue by rohit-daffodil** [facebook/react-native#22365]
Unable to use static contextType=ReactContextType in react native

```
import React from "react";
import View from "react-components/lib/View";
import Text from "react-components/lib/Text";

const ThemeContext = React.createContext({ name: "Rohit Garg" });

class DemoButton extends React.Component {
  static contextType = ThemeContext;
  render() {
    const name = this.context.name;
    return <Text>{name}</Text>;
  }
}

class App extends React.Component {
  render() {
    return (
      <ThemeContext.Provider value={{ name: "Rohit Kumar" }}>
        <View>
          <Text>This is demo app</Text>
          <DemoButton />
        </View>
      </ThemeContext.Provider>
    );
  }
}

export default App;

```

package.json

"react": "^16.6.0",
"react-native": "0.57.4",

Error : TypeError : undefined is not a function (evalutating 'contextType.unstable_read')
![screenshot from 2018-11-21 13-32-02](https://user-images.githubusercontent.com/4848123/48827112-3da48380-ed92-11e8-8a1e-92b67a5e744c.png)

**Comment by jmrossy** [comment]
FYI I hit this same error with react: 16.6.3 and react-native: 0.57.4 but it seems to work with react-native 0.57.7

**Comment by jacoblukose** [comment]
@rohit-daffodil  
      react: ^16.6.1 => 16.6.3
      react-native: ^0.57.7 => 0.57.7

You can try the contextType with these versions. Working for me :)
