### ISSUE TITLE
[0.16.0-rc/Master] Error on start: "SyntaxError: Unexpected identifier 'c1x'. Expected ')' to end a compound expression"

### ISSUE THREAD

**Issue by dsibiski** [facebook/react-native#4459]
**UPDATE**: Please upvote this bug on ProductPains: https://productpains.com/post/react-native/bug-error-on-start-syntaxerror-unexpected-identifier-c1x-expected-to-end-a-compound-expression/

Happens on both iOS & Android with a basic sample app on a fresh install of 0.16.0-rc:

`SyntaxError: Unexpected identifier 'c1x'. Expected ')' to end a compound expression`

In Android, it tells me a line number from the bundle which was line 26841:

```javascript
26838 if(ex==null){
26839 this._pivotX=+c1x;this._pivotY=+c1y;
26840 ex=+c2x;ey=+c2y;
26841 c2x=(ex++c1x*2)/3;c2y=(ey++c1y*2)/3;
26842 c1x=(x++c1x*2)/3;c1y=(y++c1y*2)/3}else 
26843 {
26844 this._pivotX=+c2x;this._pivotY=+c2y}
```

This seems to be coming from React Art, which hasn't been updated in a while so I think it's just a false positive of some other issue.

Any thoughts?

**Comment by TerranTian** [comment]
got the some problem, how to fixed it?

**Comment by satya164** [comment]
Facing same issue with master.

**Comment by Alphmega** [comment]
+1 how to fixed it ?

**Comment by huix9527** [comment]
+1, stuck, can't build now.

**Comment by reddol18** [comment]
+1 Me Too. Does not work after changing popup menu.

**Comment by casperin** [comment]
+1

**Comment by inickel** [comment]
+1,mark

**Comment by Sas0ri** [comment]
+1

**Comment by rashmi-chachan** [comment]
facing the same issue. how to fixed it ?

**Comment by mariusk** [comment]
+1

**Comment by yeziahehe** [comment]
mark

**Comment by watzak** [comment]
+1

**Comment by dsibiski** [comment]
Hey everyone, I created a post on ProductPains here: https://productpains.com/post/react-native/bug-error-on-start-syntaxerror-unexpected-identifier-c1x-expected-to-end-a-compound-expression/

Please upvote this over there as it seems like our +1's here may not be very effective anymore.

**Comment by dsibiski** [comment]
@ide @brentvatne @mkonicek Any thoughts on this? Seems like it is just a broken dependency or something...

**Comment by mariusk** [comment]
I doubt it's anything like a broken dependency. I took a brief look at the source for the code that breaks, which is `art/core/path.js`:

```javascript
	curveTo: function(c1x, c1y, c2x, c2y, ex, ey){
		var x = this.penX, y = this.penY;
		if (c2x == null){
			c2x = +c1x; c2y = +c1y;
			c1x = (x * 2) - (this._pivotX || 0); c1y = (y * 2) - (this._pivotY || 0);
		}
		if (ex == null){
			this._pivotX = +c1x; this._pivotY = +c1y;
			ex = +c2x; ey = +c2y;
			c2x = (ex + (+c1x) * 2) / 3; c2y = (ey + (+c1y) * 2) / 3;
			c1x = (x + (+c1x) * 2) / 3; c1y = (y + (+c1y) * 2) / 3;
		} else {
			this._pivotX = +c2x; this._pivotY = +c2y;
		}
		if (this.penDownX == null){ this.penDownX = x; this.penDownY = y; }
		this.onBezierCurve(x, y, +c1x, +c1y, +c2x, +c2y, this.penX = +ex, this.penY = +ey);
		return this;
	},
```

My best guess is one of the babel transforms involved is a bit too aggressive removing those parentheses. Now which one and why is another question.

**Comment by mariusk** [comment]
Looks like there may be some unfortunate cirumstances related to babel removing parentheses and something else cleaning up whitespace. For instance `(a+(+b))` gets transformed to `(a+ +b)` which works fine in javascript. But if something removes that space, then it becomes `(a++b)` which is invalid.

**Comment by rmevans9** [comment]
Not sure if it helps any but if you set "compact" to false in .babelrc in /node_modules/react-native/packager/react-packager it appears to work fine. I bet there are downstream effects but I got a basic app running on Android with that change.

**Comment by szhu** [comment]
**TEMPORARY WORKAROUND** for people who just want to revert to version 0.15.0:

```
curl -L http://git.io/vBxKw | patch -p0 `which react-native`
```

Check out the patch details here: http://git.io/vBxKw
All I did was add @0.15.0 where needed.

**Comment by mariusk** [comment]
Great workaround. I guess that pretty much points to the bug being in babel (`babel-generator/src/generators/expressions.js` or similar), triggered by an update of `art` from the looks of it.

**Comment by jsntghf** [comment]
how to fixed it?

**Comment by szhu** [comment]
@jsntghf, see my comment above https://github.com/facebook/react-native/issues/4459#issuecomment-160971744 for a quick way to fix it. Just run that command in your terminal.

**Comment by nicoecheza** [comment]
@szhu I tried that command, but it throws about not found modules. EX: Module not found 'chalk'.

**Comment by szhu** [comment]
Hi @nicoecheza, sorry I forgot to include a step: if you created your project with react-native 0.16.0, you need to delete it or move it aside, and `react-native init` your project again. If you made changes to `index.android.js`, you can move it back into the newly-inited project.

**Comment by nicoecheza** [comment]
hey @szhu 

I did that, but when I run `react-native init` it fails since it doesn't find some modules.
If I reinstall `npm i -g react-native-cli` again, it works fine, but it installs react-native 0.16.0, and that version doesn't work :(.

Thanks!

**Comment by szhu** [comment]
@nicoecheza My patch changes the executable script provided by `react-native-cli`, so definitely reinstalling that will undo the patch. I didn't get dependency errors when I tried it though. Can you paste the entire output into a [gist](https://gist.github.com/) and link to it here?

**Comment by nicoecheza** [comment]
@szhu Sure. Here is the [gist](https://gist.github.com/nicoecheza/7e7b9522f17ca9c8ef5c)

**Comment by nicoecheza** [comment]
I'm thinking, maybe the problem is I'm using nvm, what do you think?

**Comment by mariusk** [comment]
The absolute simplest method I have found so far is simply to patch art with the following patch:

```diff
--- node_modules/art/core/path.js.org	2015-12-01 15:43:21.000000000 +0100
+++ node_modules/art/core/path.js	2015-12-01 15:50:24.000000000 +0100
@@ -95,8 +95,8 @@
 		if (ex == null){
 			this._pivotX = +c1x; this._pivotY = +c1y;
 			ex = +c2x; ey = +c2y;
-			c2x = (ex + (+c1x) * 2) / 3; c2y = (ey + (+c1y) * 2) / 3;
-			c1x = (x + (+c1x) * 2) / 3; c1y = (y + (+c1y) * 2) / 3;
+			c2x = (ex + (c1x) * 2) / 3; c2y = (ey + (c1y) * 2) / 3;
+			c1x = (x + (c1x) * 2) / 3; c1y = (y + (c1y) * 2) / 3;
 		} else {
 			this._pivotX = +c2x; this._pivotY = +c2y;
 		}
@@ -279,4 +279,4 @@
 		this.onLine(sx, sy, ex, ey);
 	}

-});
\ No newline at end of file
+});
```
I've put it up as a gist at https://gist.github.com/mariusk/3a71fa779311311b00b3.

To apply the patch, download the patch into your react native app directory and run:

```
patch -p0 < art-patch.diff
```

**Comment by nowaits** [comment]
+1, master and 0.16-rc

**Comment by mariusk** [comment]
Yeah, looks like `art` hasn't been updated for a while. Something else must have changed; react-native packager or babel. Definitively looks like a minification artifact.

**Comment by szhu** [comment]
@nicoecheza, my bad, I didn't test it on a clean setup. The problem is that `patch` reads through the symlink but it overwrites the symlink instead of its referrent, causing all kinds of working-directory issues. I've updated the command above. This should now work:

```shell
npm install -g react-native-cli
curl -L http://git.io/vBp9H | patch "$(which react-native | xargs dirname | xargs dirname)"/lib/node_modules/react-native-cli/index.js
```

The command is long simply because there is no portable way to follow a symlink in one line. `readlink -f` is what I'm looking for but Macs' `readlink` does not have it.

**Comment by rmevans9** [comment]
@mariusk according to the release page they upgraded to Babel 6. My guess is that is where the problem is stemming from.

https://github.com/facebook/react-native/releases

**Comment by jasonmerino** [comment]
I'm also seeing this when upgrading to 0.16.0-rc. 

For those who haven't yet make sure you go and [up vote this issue on Product Pains](https://productpains.com/post/react-native/bug-error-on-start-syntaxerror-unexpected-identifier-c1x-expected-to-end-a-compound-expression/).

**Comment by christopherdro** [comment]
+1

**Comment by chirag04** [comment]
+1 

cc @sebmck  also

**Comment by sunvooker** [comment]
+1

**Comment by mariusk** [comment]
This gotta be a babel issue:

```
echo '(a+(+b)*2)' | babel --compact
```
outputs:
```
a++b*2;
```

**Comment by mariusk** [comment]
Filed minimal sample and bug with BabelJS here:

https://phabricator.babeljs.io/T6736

**Comment by amasad** [comment]
Just published a fix, if you npm install you should get it. Sorry about that.

**Comment by gmhewett** [comment]
Thanks for the fix! Just tried to see the update at https://www.npmjs.com/package/react-native, but nothing there yet. Any idea how long until we can update the version, "npm install", and "react-native upgrade"?

**Comment by amasad** [comment]
It's in Babel. But you should get it with a fresh install of react native.
Just rm your node_modules and npm install

**Comment by jasonmerino** [comment]
@amasad That seemed to fix that issue for me. Thanks! I had to go through and remove import statements for the time being from one module in my project because of the `babelHelpers.interopRequireDefault is not a function` issue that looks to be resolved by #4327 but now things are up and running for me.

Thanks again!

**Comment by gmhewett** [comment]
@amasad Thanks! However, I am still getting the error. Is there anything else I need to update? My react native version is still 0.16.0-rc.

**Comment by amasad** [comment]
@gmhewett With a fresh npm install you would get the new babel version. `rm -rf node_mdoules && npm install`

**Comment by thsig** [comment]
@amasad I've tried `rm -rf node_modules && npm install`, still getting the same error.

Do I need to take any special precautions to ensure that the newest version of Babel is being installed and used?

Thanks!

**Comment by mariusk** [comment]
Try `babel --version` and see what it outputs. At my end it says `6.2.4 (babel-core 6.2.4)`. Then there's the possibility that some globally installed version of `babel` is being used, without being updated. You could always try `npm install -g babel@latest` or similar to make sure you've got the latest installed globally as well (if that is causing issues).

**Comment by thsig** [comment]
@mariusk That did it, thanks! When trying out your suggestion I noticed that my version of npm was out of date, which probably explains why it didn't install the latest version of babel.

**Comment by gmhewett** [comment]
Got it working, thanks so much!

**Comment by jvlobo** [comment]
I'm having the same trouble.

When I do babel --version I get: 6.2.0 (babel-core 6.2.1)

If I do npm install -g babel@latest: http://puu.sh/lGSHA/93ba58326f.png

My npm version is 3.5.0

I don't know what else I can do, any help?

Thanks.

**Comment by mariusk** [comment]
@jvlobo Ok, my assumptions were a bit wrong. "latest" is tagged as 6.1.18. I have no idea if that version has the same problem. Regardless, try `npm install -g babel@prerelease` instead, or alternatively `npm install -g babel@6.2.4` and see if that helps.

**Comment by jvlobo** [comment]
Thanks @mariusk I deleted my message because I drop the project and download the repo again and after npm install all went well... so I don't know what happened. Thanks.
