### ISSUE TITLE
YGConfig::YGConfig ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by cihati** [facebook/react-native#23218]
## Environment

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 358.79 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.3 => 0.58.3
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
## Description

I'm trying to upgrade to RN 0.58.3 from 0.57.5. As part of this upgrade, I need to modify `Podfile` to increase Stripe version (because I need to upgrade to tipsi-stripe 7.2.0, which is the only compatible version of RN 0.58.x). As part of this, I ran `pod install`, and got a bunch of errors and then I realized I needed to make some changes into Podfile, per https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies 

(adding `CxxBridge`, `DoubleConversion`, `glog`, `Folly`. Once I realized this, I actually tried to make these changes onto a branch with RN 0.57.5 and I got the same error as I get in 0.58.3. I believe we should have done these when upgrading to 0.57.5 in the first place originally, but somehow we missed it and everything worked fine since we didn't have to run `pod install`)

I've done those changes, and now I'm having this issue when I run `react-native run-ios`:
```
Undefined symbols for architecture x86_64:
  "YGConfig::YGConfig(int (*)(YGConfig*, YGNode*, YGLogLevel, char const*, __va_list_tag*))", referenced from:
      _YGConfigNew in libyoga.a(Yoga.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've spent many hours trying to fix this issue (Found https://github.com/facebook/react-native/issues/18714 to be the most relevant, but per @hramos suggestion, created this new ticket). Tried nuking `node_modules/`, `ios/build/` with no luck. Any ideas?

Here's our Podfile
```
# Uncomment the next line to define a global platform for your project

target 'mobile' do
  platform :ios, '9.0'

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Stripe', '~> 14.0.0'
  pod 'Intercom'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'
  pod 'Firebase/Core', '~> 4.0.0'
  pod 'Firebase/Messaging'
  pod 'Mixpanel'

  # Pods for mobile
  pod 'AppCenter/Crashes', '~> 1.6.0'
  pod 'AppCenter/Analytics', '~> 1.6.0'
  pod 'AppCenterReactNativeShared', '~> 1.5.0'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

    pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  end

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

```

**Comment by tiffanym19** [comment]
having this issue... help me plss
