### ISSUE TITLE
com.facebook.react.config.defaults does not exist after upgrade to 0.72.1

### ISSUE THREAD

**Issue by nsdonev** [facebook/react-native#38272]
### New Version

0.72.1

### Old Version

0.69.7

### Build Target(s)

Android

### Output of `react-native info`

System:
  OS: macOS 13.3
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 48.33 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.16.0
    path: ~/.nvm/versions/node/v16.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.16.0/bin/yarn
  npm:
    version: 8.11.0
    path: ~/.nvm/versions/node/v16.16.0/bin/npm
  Watchman:
    version: 2023.05.01.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /Users/user/.rvm/rubies/ruby-2.7.4/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/user/.rvm/rubies/ruby-2.7.4/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Issue and Reproduction Steps

I am getting this error when building for Android after upgrading RN from 0.69.7 to 0.72.1 using the upgrade tool:

/Users/user/Documents/Projects/test-react-native/android/app/src/main/java/com/app/testApp/MainApplication.java:14: error: package com.facebook.react.config.defaults does not exist
import com.facebook.react.config.defaults.DefaultNewArchitectureEntryPoint;
                                         ^
/Users/user/Documents/Projects/test-react-native/android/app/src/main/java/com/app/testApp/MainApplication.java:86: error: cannot find symbol
      DefaultNewArchitectureEntryPoint.load();
      ^
  symbol:   variable DefaultNewArchitectureEntryPoint
  location: class MainApplication
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 34s
info Run CLI with --verbose flag for more details.

The default packages are not found:

Gradle sync fails in Android Studio as well.

**Comment by cortinico** [comment]
You're having a wrong import in your `MainApplication` file

```diff
-import com.facebook.react.config.defaults.DefaultNewArchitectureEntryPoint;
+import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
```
