### ISSUE TITLE
Task :app:buildCMakeDebug[arm64-v8a] Where is rncli.h file ?? I am trying to build the app and the build always fails

### ISSUE THREAD

**Issue by AdhamMahmoud98** [facebook/react-native#35189]
### Description

I enabled the new architecture after upgrading from 0.65.1 to 0.70.3 and I am trying to build the app and it always fails !!! Any idea what is the issue here ?
 Task :app:buildCMakeDebug[arm64-v8a]
C/C++: ninja: Entering directory `/Users/adham/MobileX/android/app/.cxx/Debug/66286b3x/arm64-v8a'
C/C++: /Users/adham/MobileX/android/app/src/main/jni/MainApplicationModuleProvider.cpp:3:10: fatal error: 'rncli.h' file not found
C/C++: /Users/adham/MobileX/android/app/src/main/jni/MainComponentsRegistry.cpp:7:10: fatal error: 'rncli.h' file not found

### Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 45.17 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/MobileX/node_modules/.bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cd android & ./gradlew clean then yarn react-native run-android --active-arch-only

### Snack, code example, screenshot, or link to a repository

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/46315255/199737191-fb0f6b61-a0de-4b76-b288-0b06ea0c4098.png">

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/46315255/199737355-a2e8b547-2536-49fa-ac53-b6abca92dfab.png">

<img width="469" alt="image" src="https://user-images.githubusercontent.com/46315255/199741532-005731b7-62cc-4ce1-b0b1-ce55ed76222f.png">

**Comment by cortinico** [comment]
CLosing as duplicate of https://github.com/facebook/react-native/issues/35239
