### ISSUE TITLE
Requiring module 'NativeModules' by name - arguments[0].indexOf is undefined

### ISSUE THREAD

**Issue by ben-snaize** [facebook/react-native#14364]
Hi,

Seeing an odd issue in RN 0.42 (since upgrading from 0.38, I believe).

I can't replicate the crash locally in debug or release which makes things difficult, but on both iOS and Android I'm seeing the following logged from Crashlytics. Both apps run through flawlessly locally, on device and via TestFlight / Play Store beta, yet something like like 1 in 20 users of the live Apps are crashing due to this:

`RCTFatalException: Unhandled JS Exception: arguments[0].indexOf is not a function. (In 'arguments[0].indexOf("Requiring module 'NativeModules' by name")', 'arguments[0].indexOf' is undefined)`

This seems to be stemming from here in `index.[os].bundle.js` where `arguments[0].indexOf` is called.

```
console.warn = function () {
    if (arguments[0] && arguments[0].indexOf('Requiring module \'NativeModules\' by name') > -1) return;
    return originalWarn.apply(console, arguments);
};
```

Does anyone have an idea of what could the cause of this? Why would `arguments[0].indexOf` be undefined at this stage?

I know the crash is very context dependent but some sort of pointer would be of great help.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by ben-snaize** [comment]
Thanks, I'm active on SO. I'll post there.

**Comment by IrinaCodixis** [comment]
Hi @ben-snaize . 
I am experiencing the same issue. Did you manage to find the solution?

**Comment by ben-snaize** [comment]
For out production code, removing all calls to `console.warn` was the solution.

**Comment by koenpunt** [comment]
FYI, it's probably because of this module: https://github.com/jhen0409/rn-host-detect/blob/master/index.js#L44
