### ISSUE TITLE
[CI] Test failure - Various tests failing on master

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#23108]
Tests help us prevent regressions, and without a clear signal, maintainers are unable to properly review pull requests. The following jobs are failing on `master`, and will need to be fixed before any new contributions can be considered:

- [x] `test_detox_end_to_end`
- [x] `test_android` (potential fix in https://github.com/facebook/react-native/pull/23106)
- [ ] `test_ios` (several failures fixed in https://github.com/facebook/react-native/commit/27617be9bb2083a58a56c1d9d20a45e9af069f42, one remaining failure)

## test_detox_end_to_end

[The job is failing with:](https://circleci.com/gh/facebook/react-native/68100)

```
Cannot find module 'react-native/jest/hasteImpl'

Error: Cannot find module 'react-native/jest/hasteImpl'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (internal/module.js:18:19)
    at load (/Users/distiller/react-native/node_modules/@react-native-community/cli/build/util/loadMetroConfig.js:89:51)
    at <anonymous>
```

## test_ios

Failing tests:

- [X] [RNTesterSnapshotTests testLayoutExample](https://circleci.com/gh/facebook/react-native/68366)
- [X] [RNTesterSnapshotTests testScrollViewExample](https://circleci.com/gh/facebook/react-native/68366)
- [X] [RNTesterSnapshotTests testSliderExample](https://circleci.com/gh/facebook/react-native/68366)
- [X] [RNTesterSnapshotTests testSwitchExample](https://circleci.com/gh/facebook/react-native/68366)
- [X] [RNTesterSnapshotTests testTextExample](https://circleci.com/gh/facebook/react-native/68366)
- [X] [RNTesterSnapshotTests testViewExample](https://circleci.com/gh/facebook/react-native/68366)
- [ ] [RNTesterSnapshotTests testTabBarExample](https://circleci.com/gh/facebook/react-native/68426)

**Comment by dulmandakh** [comment]
Android CI is green https://github.com/facebook/react-native/pull/23109

**Comment by guhungry** [comment]
For test_ios is it related to ios simulator 12 since `RNTesterSnapshotTests`'s `_runner` have only ios 10 and 11 condition

**Comment by guhungry** [comment]
Somehow layout of snapshot is changed i'm uploading image for comparison

**Comment by guhungry** [comment]
iOS CI is also green #23152

**Comment by hramos** [comment]
Thanks @guhungry! It looks like `test_ios` [switched to green](https://circleci.com/gh/facebook/react-native/68380) in 27617be9bb2083a58a56c1d9d20a45e9af069f42, but is [failing again](https://circleci.com/gh/facebook/react-native/68426) as of b905548a3b43b2130c35360c3602eda722f82e7f. It's just the one failing job so far, so perhaps it's flaky, but we might need to update snapshots again.

That last failure was for a single snapshot test:

```
Failing tests:
	-[RNTesterSnapshotTests testTabBarExample]
```

**Comment by hramos** [comment]
I'm unable to repro the testTabBarExample failure locally. I'll re-run https://circleci.com/workflow-run/03a88f51-0ca8-4adc-9994-7bbb0ea41caa and see if that was a one-off failure.

**Comment by hramos** [comment]
I finally reproduced this locally. #23161 fixes it for me, though I can't even tell what's different in the snapshot.

**Comment by hramos** [comment]
My PR failed test_ios as well.

**Comment by guhungry** [comment]
After I ran unit test many times. Sometimes I found error in ScrollViewExample too (especially run only the test individually). My guess is that ImageView is loading image.

<details>
<img width="400" alt="screen shot 2019-01-26 at 13 26 56" src="https://user-images.githubusercontent.com/4032276/51783551-22793a00-216e-11e9-86f2-04f31a53f1a3.png">
</details>

**Comment by grabbou** [comment]
Detox fix hopefully here: https://github.com/facebook/react-native/pull/23191

**Comment by konmik** [comment]
Wiping modules and lock didn't help for me. --runInBand worked.
