### PR TITLE
return findNodeHandle to public api

### LINKED ISSUE #13688: _reactNative.findNodeHandle is not a function
### Description

Importing `findNodeHandle` from `react-native` broke sometime in the last ~10 days. The function just isn't there anymore.

### Reproduction Steps and Sample Code

In a clean app from `react-native init`, import `findNodeHandle`:

```JavaScript
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  findNodeHandle
} from 'react-native';
```

And then call it:
```JavaScript
  componentDidMount() {
    findNodeHandle();
  }
```
This works fine in 0.43.4 (although the function call is rather pointless). On iOS with the latest master https://github.com/facebook/react-native#1a72d91cb29d24851bf8b8cf36e683740d3945d0 it redboxes, citing `(0, _reactNative.findNodeHandle) is not a function`. Probably Android as well but who even tests that platform.

### Additional Information

* React Native version: https://github.com/facebook/react-native#1a72d91cb29d24851bf8b8cf36e683740d3945d0
* Platform: Definitely iOS, most likely Android
* Development Operating System: macOS
* Dev tools: XCode 8.3.2

### PR DESCRIPTION
**Pull request by skv-headless**
## Motivation (required)

findNodeHandle used in my app few times.
after https://github.com/facebook/react-native/commit/f3dbddcf2bdc0e4f49dd6f5220360b5ff383e16f it is not available.
cc @janicduplessis.
closes #13688 
proof of the publicity of the API https://facebook.github.io/react-native/docs/nativemethodsmixin.html#measurelayout

### CODE REVIEW

**Comment by janicduplessis** [comment]
Oups that was not intended. Can you export it using `require('ReactNative').findNodeHandle` because a different implementation gets used when using fiber.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit
