### ISSUE TITLE
In a CocoaPod build, "Optional.h" will refer to folly/Optional.h unexpectedly

### ISSUE THREAD

**Issue by mhorowitz** [facebook/react-native#14326]
### Description

The CocoaPods setup works, but there are issues integrating it into larger projects.  In particular, header files from folly (and maybe elsewhere?) pollute the user header filespace, and I don't know why. 

### Reproduction Steps and Sample Code

1. check out https://github.com/mhorowitz/native-navigation-boilerplate and apply this:

```
diff --git a/ios/Podfile b/ios/Podfile
index 3474dc5..556aa68 100644
--- a/ios/Podfile
+++ b/ios/Podfile
@@ -26,6 +26,8 @@ target 'ReactNativeStarter' do
     'DevSupport'
   ]

+  pod 'KSCrash'
+
   # Add any other dependencies here, including any 3rd party native libraries that you depend on for
   # React Native.
 end
```

2. To run pod and open in Xcode:
```
cd ios
pod install
open ReactNativeStarter.xcworkspace
```

3. Build it in Xcode.  it will fail, probably in KSCrash's Demangle.cpp with an error about llvm::Optional.  If you dig into this, you will eventually figure out that it is including folly/Optional.h instead.  Xcode is generating a header map like `.../DerivedData/ReactNativeStarter-bzdrkfxifzuvmgduxsjbskaldaxw/Build/Intermediates/Pods.build/Debug-iphonesimulator/KSCrash.build/KSCrash-project-headers.hmap` which maps `optional.h` to `Pods/Folly/folly/Optional.h`, instead of the one inside KSCrash.

### Solution

I have no idea.  I am hoping someone who knows CocoaPods better than I can figure this out.

### Additional Information

* React Native version: 844a18fb25b94ad568e5e715d328bea9d63fe592
* Platform: iOS
* Development Operating System: MacOS Sierra
* Dev tools: Xcode 8.2.1, cocoapods 1.2.0

**Comment by javache** [comment]
I've found the same thing in https://github.com/facebook/react-native/pull/14100, where `pod lib lint $POD_LINT_OPT --use-librarie` would fail for the same reason.

**Comment by nico1510** [comment]
I think I have something related to this. I'm using [react-native-fbsdk](https://github.com/facebook/react-native-fbsdk) and when using `CxxBridge` the project doesn't compile and shows a warning 'non portable path to file Math.h' and an error and doesn't find the `limits` import (limits file not found).
When using the `BatchedBridge` everything compiles.

**Comment by javache** [comment]
For google-ability. This issue also manifests itself as:

Non-portable path to file '<String.h>; specified path differs in case from file name on disk.
No member named 'memcpy' in the global namespace
No member named 'memmove' in the global namespace

**Comment by rclai** [comment]
I've ran into this error when ejecting from create-react-native-app into ExpoKit mode. I added the additional pod specs per [this](https://github.com/facebook/react-native/commit/5aca739cc25949eebc04a0309c2944f92b5b5391).

And I'm now here.

**Comment by sivakumar-cf** [comment]
When I update from react-native 0.44.3 to 0.45.1, I got a build issue in iOS.

> limits File not found
in Folly/Math.h

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTImage',
    'RCTNetwork',
    # Add any other subspecs you want to use in your project
    'DevSupport'
    ]
    # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    
    # Third party deps
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


Please help me to resolve this build error. Thanks in Advance.

**Comment by mhorowitz** [comment]
I'm hopeful I've worked around this.  If you're experiencing this problem, please try your app against a version of RN including the above rev and post what happens.  Thanks!

**Comment by ptomasroos** [comment]
Will try right away and report back!

**Comment by zhunt11** [comment]
I am seeing a similar issue after having gotten updated to v0.45.1. 

`Unable to find a specification for `Folly` depended upon by `React/CxxBridge``

#https://github.com/facebook/react-native/issues/14612

**Comment by ragnorc** [comment]
Any updates on this? Does it now work with 0.46?

**Comment by mhorowitz** [comment]
I've landed fixes for all the CocoaPods+CxxBridge issues I am aware of.  They have just been cherry picked into v0.47.0-rc.1, so if you want to try this out, you *must* be using this version or later.  You can do this in your package.json file like this:

    "react-native": "0.47.0-rc.1"

For any earlier version of React Native, you cannot use CocoaPods with CxxBridge.  You need to use the `BatchedBridge` subspec in your Podfile.  This will continue to work until the CxxBridge CocoaPods podspec is stable.

If you continue to have problems, you *must* post the following information:
* Your Podfile
* The version of react-native you are building against
* The command or Xcode target which failed
* The error messages or other diagnostics.

If it works for you, that would be great to know, too!

**Comment by ragnorc** [comment]
Thanks @mhorowitz! Followed your above-mentioned steps but still getting `limit not found in Math.h` with fbsdk. 
This is my podfile:
`react_native_path = '../node_modules/react-native'

platform :ios, '8.0'

target 'MemoriesApp' do
  
   source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTImage',
    'RCTAnimation',
    'RCTWebSocket',
    'ART',
    'CxxBridge',
    'DevSupport'
]


pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
pod 'RNAudioStreaming', :path => '../node_modules/react-native-audio-streaming'
pod 'CodePush', :path => '../node_modules/react-native-code-push'

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'RSKImageCropper'
pod 'QBImagePickerController'
pod 'GooglePlaces'
pod 'GoogleMaps'
pod 'GooglePlacePicker'
pod 'Fabric'
pod 'Crashlytics'
end

`

**Comment by mhorowitz** [comment]
@ragnorc you didn't say which version of react-native you're building against.

**Comment by ragnorc** [comment]
@mhorowitz I am building against `0.47.0-rc.1`. 
My pod output doesn't seem to differ from yours: https://gist.github.com/ragnorc/c20f36ec79496180049b7255b2854348

But still getting the error.

**Comment by sivakumar-cf** [comment]
++ @ragnorc I am also facing with same issue on 0.47.0-rc.1.
error: 'limits' file not found #include <limits>

**Comment by mhorowitz** [comment]
Ok, this is all helpful.  I have a couple more questions.

1. What version of Xcode are you using?  (I'm using Xcode 8.3.2)
2. What version of pod are you using?  (I'm using 1.2.0)

And now I have a theory.  Both of your ( @ragnorc and @sivakumar-cf ) error messages include header files in `.../ios/build/Build/Products/Debug-iphonesimulator/include`.  The entire contents of the `ios/build` directory is created by Xcode.  Xcode is notorious for being sloppy with the way it handles using and cleaning files in this directory.  I delete my `ios/build` directory regularly, and I do not have the `ios/build/Build/Products/Debug-iphonesimulator/include` subdirectory at all.  I speculate that this directory contains files left behind from previous builds, and these files are being used by Xcode unintentionally, interfering with the current build.  There may be other old files lying around causing trouble.

So, the fix is to clean up after Xcode manually.  Remove this directory: `rm -r ios/build`.  Then try building your app again.

**Comment by sivakumar-cf** [comment]
@mhorowitz I am using XCode 8.3.3, cocoapods 1.2.1.
I have cleared the lib folder before building the project. still the issue persists. In Xcode, I have done additional steps to build  the React Project first. By Changing edit schema->Build->Added the React and unchecked the parallelised build.
And moved the React to Top on my project target.
Issue was not resolved.

**Comment by mhorowitz** [comment]
Which is the lib folder?  After the build fails, what does `ls -l ios/build/Build/Products/Debug-iphonesimulator`say?

If you are building in Xcode, and not from the command line, you may also need to remove the Xcode DerivedData directory.  You can do `rm -rf ~/Library/Developer/Xcode/DerivedData` from the command line, or Option-Shift-Command-K from Xcode.

As another experiment, if you download and build https://github.com/mhorowitz/native-navigation-boilerplate what is the result?

**Comment by ragnorc** [comment]
@mhorowitz I also cleaned my Xcode project several times, deleted all pods and reinstalled them. The issue persists. The funny thing is that I could build https://github.com/mhorowitz/native-navigation-boilerplate without any errors, even after replacing the podfile with mine and adding some npm modules.

**Comment by mhorowitz** [comment]
Well, I'm glad to hear that native-navigation-boilerplate works for you, at least.

Especially given that you can modify that as you described, and it still works, I still am left with the idea there's something weird about your particular build setup which is causing the issue to persist.  I'm not sure how I can help at this point.

The only thing I can imagine left to try is to start moving your code into the functional native-navigation-boilerplate checkout piecemeal until you find a problem which needs to be fixed in RN, or until your entire app builds and runs, in which case you can compare the two trees to see how they differ, and figure out what errant artifact is the problem.

**Comment by mhorowitz** [comment]
Another option is to construct a repro you are willing to post.  The failure is building OSS code, so it should be possible to remove the proprietary bits of your system, confirm it still fails, and post the code (Podfile, sources, etc) so I can see it happen and dig into it.  (And if it doesn't fail, that helps narrow down the culprit.)  Given that this is a build-time failure, if the resulting app is just a plain white screen, that's fine.  If the project is already open source, send me a link to a failing revision.

At this point, absent a repro or a more specific problem identification, I'm going to want to close this issue.  We can open a new issue if we get a repro.

**Comment by ohtangza** [comment]
@ragnorc Did you find the cause for this issue? After upgrading to 0.47.0, I'm also experiencing this issue. Any clue for this?

**Comment by ragnorc** [comment]
@ohtangza @mhorowitz Unfortunately, I haven't solved it yet. But what I just did is rebuild the whole project with `react-native init`and reinstall all modules. The same error appeared again but it worked after unlinking the module `react-native-fbsdk. But since I need this package, it doesn't really help.

**Comment by mhorowitz** [comment]
@ragnorc  That's potentially useful feedback.  Does this mean you have something like this in your Podfile?
```
  pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdk/iOS/core'
  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdk/iOS/login'
  pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdk/iOS/share'
```
If not, can you say what you removed by "unlinking" react-native-fbsdk?  I can try adding just that to my project, and see if I can repro the problem.

**Comment by ragnorc** [comment]
@mhorowitz  Thanks for your quick response. I have this in my podfile:
`pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'`

**Comment by ragnorc** [comment]
![screen shot 2017-08-09 at 23 42 54](https://user-images.githubusercontent.com/6823991/29145224-8f97bc86-7d5c-11e7-81ab-f92c775a8aec.png)
That is the error that I am getting after linking.

**Comment by sivakumar-cf** [comment]
One possible solution is I removed all the React and it subspec Pods from podfile, and did 
react-native-git-upgrade 0.46.4 and pod install. The React libraries are added as library Projects and working fine.
Earlier When I try to create a new project using react-native init Project, and Added the React pods in podfile. I could able to run the project but not able to get the debug menu (tried using shake gesture and cmd+D). I have added DevSupport also as subspec, still not getting the Debug Menu. 
Finally decided to remove the React from cocoapods.

**Comment by ragnorc** [comment]
@mhorowitz any idea?

**Comment by ragnorc** [comment]
Quite sad that react-native projects cannot be pursued because of this major bug.

This is a sample project that reproduces the issue: https://www.dropbox.com/s/9dzew9slctc7kxm/TestReactNative3.zip?dl=0

Run `npm install` and `react-native link react-native-fbsdk` and you will experience the same error.

**Comment by mhorowitz** [comment]
@ragnorc Two of us met today to look into this repro to try to understand what's happening here.  We are still working on it.

In the meantime, is switching to BatchedBridge not a viable workaround until we've fixed this?  We are keeping it around precisely for that purpose, until we've shaken out all the CxxBridge issues.

**Comment by ragnorc** [comment]
@mhorowitz Yes, I am now using BatchedBridge as a temporary solution. Thank you very much for your efforts!

**Comment by ragnorc** [comment]
@mhorowitz @sivakumar-cf @ohtangza 

I submitted a bug report to Facebook and they now managed to find a fix.
Just follow these steps: https://developers.facebook.com/bugs/111079162900447/

**Comment by jemise111** [comment]
@ragnorc Thanks for all of the helpful comments here. I'm having a very similar issue (upgrading from 0.44 -> 0.48). I tried using the `CxxBridge` and now am attempting to revert back to the `BatchedBridge`. Could you describe the steps you took to revert? Did you remove the 3 dependencies from your Podfile as well (Folly, Glog, DoubleConversion)? Any help would be awesome, thanks!

**Comment by nico1510** [comment]
This seems to affect more and more people... In the facebook thread users are reporting problems with react-native-material-kit and react-native-fcm (https://github.com/evollu/react-native-fcm/issues/593). I personally have encountered this error with react-native-fbsdk where I submitted this PR https://github.com/facebook/react-native-fbsdk/pull/363 and with react-native-google-signin https://github.com/devfd/react-native-google-signin/pull/304.

Should we wait for these packages to (hopefully) accept these PRs or is there a general solution for this ?

**Comment by mhorowitz** [comment]
I don't think a general solution is possible.  The pattern of "$(SRCROOT)/../../../ios/**" which is basically "use every header at every level of the hierarchy in the entire source tree" is fundamentally broken.  Unfortunately, this means it will need to be fixed in each package which uses it.  Fortunately, these fixes are simple.  If you do have a suggestion for how to fix this more generally, that would be great.

Thank you @nico1510 for submitting PRs to fix those other projects!
