### PR TITLE
Fix NativeAnimation invalidation & races on iOS

### PR DESCRIPTION
**Pull request by ryangomba**
This diff attempts to fix a number of iOS native animation bugs related to improper node invalidation and a race with view creation. The major issues were presented in #9120 as problems 3 and 3b, but I'll recap here:

### Incomplete node invalidation

The invalidation model we use is overly complicated and incomplete. The proper combination of `_needsUpdate` and `_hasUpdated` will result in nodes values being recomputed. However, we do not invalidate nodes in all the places we should, e.g. if we create a new view and attach it to an existing value node (see example in #9120). This diff chooses to remove the `_hasUpdated` flag, and simply relies on the `_needsUpdate` flag to mark a node as dirty.

We mark nodes as dirty when they are:
- created
- updated
- attached to new parents
- detached from old parents
- attached to a view

Calling `updateNodeIfNecessary` will, if necessary, compute all invalidated parent values before recomputing the node value. It will then apply the update, and mark the node as clean.

Note: the simplification also allows us to remove the `cleanupAnimationUpdate` routine.

### Race condition on view creation

Sometimes, we would attempt to set native animated props on a non-existent view (see example in #9120). This is because we have a race condition with UIManager: sometimes, we run animated updates before UIManager can create the view. To synchronize RCTUIManager and RCTNativeAnimatedModule, we do the following:

- place `RCTNativeAnimatedModule` calls on the UIManager queue
- gather all native animated operations, but don't apply them
- wait for a `batchDidComplete` call to flush the operation queue
- let `RCTNativeAnimatedNodesManager` apply the updates on the main queue

This module + nodeManager structure mimics the one on Android, and I think it works quite well.

### CODE REVIEW

**Comment by ryangomba** [comment]
@janicduplessis here it is!

**Comment by ryangomba** [comment]
fwiw, I'm working on a large application that makes extensive use of the NativeAnimated API. This diff fixed a boatload of hard to track down bugs.

**Comment by janicduplessis** [comment]
Awesome! Tested it and it does fix the node update issues that I had + the weird race conditions that caused some transitions to sometimes not happen at all. Going to review this tomorrow.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@javache Could you have a look at why this import failed?

**Comment by janicduplessis** [comment]
@ryangomba Can you rebase this on top of the extractOffset PR

**Comment by ryangomba** [comment]
Rebased

**Comment by ryangomba** [comment]
Should we try this again? Any context on the failed import @javache ?

**Comment by hramos** [comment]
Looking.

**Comment by nihgwu** [comment]
what's going on this?

**Comment by janicduplessis** [comment]
Ping @hramos

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by nihgwu** [comment]
why the import failed? is anyone looking into it? I've test this PR with my app, it works so great

**Comment by mkonicek** [comment]
Looks like the import failed with an unrelated error. Let's try again.

@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@mkonicek Talked with @hramos and this causes some buck errors internally, someone from fb will have to look at it.

**Comment by mkonicek** [comment]
@janicduplessis @ryangomba I'm not sure it's Buck-related. Here are the errors that blocked this from landing internally. I know little about Obj-C, do they make sense to you?

    Libraries/NativeAnimation/RCTNativeAnimatedModule.m:181:17: error: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Werror,-Wimplicit-retain-self]
    operation(_nodesManager);
                ^
    Libraries/NativeAnimation/RCTNativeAnimatedModule.m:183:6: error: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Werror,-Wimplicit-retain-self]
    [_nodesManager updateAnimations];

**Comment by janicduplessis** [comment]
@mkonicek Looks like we're compiling with different warning flags internally and in OSS. Are you using buck to build objc internally? If so I guess it has its own config that probably add different compiler warning flags as the xcbuild one. You might want to ping some ios person about it as it is easy to fix and would prevent import failures like this.

**Comment by mkonicek** [comment]
Thanks @janicduplessis! Yes we use Buck.

**Comment by mkonicek** [comment]
Is there any way you can make the code compile independently of compiler flags?

**Comment by ryangomba** [comment]
I can follow up on this now that I understand the import error
