### ISSUE TITLE
0.64.0 Xcode 12.5 Build Fail 'No member named XXX in the global namespace' 

### ISSUE THREAD

**Issue by flikQ** [facebook/react-native#31455]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Unable to build after upgrading from 0.61.5 to 0.64.0

## React Native version:
0.64.0

## Steps To Reproduce
Attempt to build via Xcode 12.5
 
## Expected Results
To not fail.

## Snack, code example, screenshot, or link to a repository:
I have had a good chat with the folks on the RealmJS repo & Flipper to try and figure this out but I cannot get any help sadly. Disabling Flipper also has no effect. This is occurring on 3 different machines for consistency purposes (i5 Mac Mini/M1 Mac Mini & i9 Macbook Pro). I am fully at my whits end right now!

Any insight or assistance would warrant many cookies and cuddles (once fully vaccinated of course!)

![image](https://user-images.githubusercontent.com/1992193/116569494-59b49380-a901-11eb-8ca9-1c25a51cc5f1.png)

**Comment by tonypangs** [comment]
Get same issue too, when upgrading from `react native 0.63.4 & react 16.13.1` to `react native 0.65.1 & react 17.0.2`
![image](https://user-images.githubusercontent.com/10650142/131977892-53bda630-7aa6-4515-a01f-5423d3559b88.png)

**Comment by rogel123** [comment]
No solutions yet?
