### ISSUE TITLE
React-Codegen build failure on Xcode 14.3 (iOS 16.4) simulators

### ISSUE THREAD

**Issue by daveslutzkin** [facebook/react-native#36690]
### Description

A clean, empty React Native 0.71.4 project fails to build in Xcode 14.3 (to iOS 16.4) with the following errors:

```
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /<directory>/dev/clean_rn_project/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2065:46: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"screen"] = screen.has_value() ? screen.value().buildUnsafeRawValue() : nil;
                                             ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /<directory>/dev/clean_rn_project/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2067:88: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"windowPhysicalPixels"] = windowPhysicalPixels.has_value() ? windowPhysicalPixels.value().buildUnsafeRawValue() : nil;
                                                                                       ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /<directory>/dev/clean_rn_project/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2069:88: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"screenPhysicalPixels"] = screenPhysicalPixels.has_value() ? screenPhysicalPixels.value().buildUnsafeRawValue() : nil;
                                                                                       ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /<directory>/dev/clean_rn_project/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2080:96: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"isIPhoneX_deprecated"] = isIPhoneX_deprecated.has_value() ? @((BOOL)isIPhoneX_deprecated.value()) : nil;
                                                                                               ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /<directory>/dev/clean_rn_project/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2288:68: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"prerelease"] = prerelease.has_value() ? @((double)prerelease.value()) : nil;
                                                                   ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /<directory>/dev/clean_rn_project/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
/<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2414:110: error: 'value' is unavailable: introduced in iOS 12.0
  d[@"DEFAULT_BACKGROUND_COLOR"] = DEFAULT_BACKGROUND_COLOR.has_value() ? @((double)DEFAULT_BACKGROUND_COLOR.value()) : nil;
                                                                                                             ^
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm:14:
In file included from /<directory>/dev/clean_rn_project/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:19:
In file included from /<directory>/dev/clean_rn_project/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety/RCTConvertHelpers.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
7 errors generated.
```

These errors occur when building from the command line or in Xcode itself:

<img width="538" alt="Screenshot 2023-03-29 at 3 06 18 pm" src="https://user-images.githubusercontent.com/78186/228424092-dd214b83-25c9-4dea-97ab-c8484af6c94b.png">

### Why are we using Xcode 14.3?

Devices which have been upgraded to iOS 16.4 can't be connected to Xcode with anything except the newest version of Xcode, which is 14.3. Unfortunately this is not yet officially released, it's only available currently as a release candidate, so it's entirely possible that the release candidate is somehow broken.

### React Native Version

0.71.4

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 78.23 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/opt/node/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/daveslutzkin/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

* Download and install [Xcode 14.3 RC 2](https://developer.apple.com/news/releases/#article-03272023h)
* Generate a clean React Native 0.71.4 project
  * `npx react-native@latest init clean_rn_project`
* Build the project for iOS
  * `cd clean_rn_project`
  * `npx react-native run-ios`
* The build error occurs during this first build.

### Snack, code example, screenshot, or link to a repository

This is reproduced in a clean RN project so no code is necessary.

**Comment by aleciosouza** [comment]
Same issue here.

**Comment by aleciosouza** [comment]
Having the same issue here.

![image](https://user-images.githubusercontent.com/33957251/228554376-1f492a88-16ca-42f8-a554-a0aef8e06056.png)

**Comment by tuliosciotta** [comment]
Same here.

**Comment by daveslutzkin** [comment]
Oh sorry, my fault, this is a duplicate of https://github.com/facebook/react-native/issues/36635

**Comment by nathannewyen** [comment]
> Having the same issue here.
> 
> ![image](https://user-images.githubusercontent.com/33957251/228554376-1f492a88-16ca-42f8-a554-a0aef8e06056.png)

I got same error any solution for this one ?

**Comment by punjasin** [comment]
i am working and suddenly xcode it auto-update itself now here we are it broke again T^T

**Comment by javier-sibs** [comment]
Same issue when updating the xcode to 14.3

**Comment by javier-sibs** [comment]
Do we have any solution for it?

**Comment by daveslutzkin** [comment]
More details in the linked issue https://github.com/facebook/react-native/issues/36635

Personally I just rolled back to 14.2 until the fix lands.

**Comment by punjasin** [comment]
@daveslutzkin 
There are custom pod script that solve this on duplicates issue above those will be included in next week release as i know

https://github.com/travis-mark/lrn/commit/015854716feadd61a904d5a603b027426472f863

**Comment by CherukuriSiva** [comment]
Goto Pods -> Select React-Codegen and update iOS Deployment Target to iOS 12.4.
<img width="1044" alt="Screenshot 2023-04-03 at 10 40 29 AM" src="https://user-images.githubusercontent.com/6113750/229430935-d603d655-3bcc-44cb-babd-576fb4bbed06.png">

**Comment by blakef** [comment]
Just locking as we've got a bunch of mitigations and a fix landing really soon now.
